// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// ABitOfEverythingNested Nested is nested type.
// Example: {"ok":"TRUE"}
//
// swagger:model ABitOfEverythingNested
type ABitOfEverythingNested struct {

	// amount
	Amount int64 `json:"amount,omitempty"`

	// name is nested field.
	Name string `json:"name,omitempty"`

	// DeepEnum description.
	Ok *NestedDeepEnum `json:"ok,omitempty"`
}

// Validate validates this a bit of everything nested
func (m *ABitOfEverythingNested) Validate(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ABitOfEverythingNested) validateOk(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
	// not required
}

// ContextValidate validate this a bit of everything nested based on the context it is used
func (m *ABitOfEverythingNested) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ABitOfEverythingNested) contextValidateOk(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// not required

// MarshalBinary interface implementation
func (m *ABitOfEverythingNested) MarshalBinary() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalBinary interface implementation
func (m *ABitOfEverythingNested) UnmarshalBinary(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}
