// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// ExamplepbErrorObject examplepb error object
//
// swagger:model examplepbErrorObject
type ExamplepbErrorObject struct {

	// code
	//
	// Response code
	Code int64 `json:"code,omitempty"`

	// message
	//
	// Response message
	// Pattern: ^[a-zA-Z0-9]{1, 32}$
	Message string `json:"message,omitempty"`
}

// Validate validates this examplepb error object
func (m *ExamplepbErrorObject) Validate(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ExamplepbErrorObject) validateMessage(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
	// not required
}

// ContextValidate validates this examplepb error object based on context it is used
func (m *ExamplepbErrorObject) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// MarshalBinary interface implementation
	return nil
}

func (m *ExamplepbErrorObject) MarshalBinary() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalBinary interface implementation
func (m *ExamplepbErrorObject) UnmarshalBinary(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}
