// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/strfmt"
)

// OneofenumExampleEnum oneofenum example enum
//
// swagger:model oneofenumExampleEnum
type OneofenumExampleEnum string

func NewOneofenumExampleEnum(value OneofenumExampleEnum) *OneofenumExampleEnum {
	_ = "STUB: not implemented"

	// Pointer returns a pointer to a freshly-allocated OneofenumExampleEnum.
	return nil
}

func (m OneofenumExampleEnum) Pointer() *OneofenumExampleEnum {
	_ = "STUB: not implemented"
	return nil

	// OneofenumExampleEnumEXAMPLEENUMUNSPECIFIED captures enum value "EXAMPLE_ENUM_UNSPECIFIED"
}

const (
	OneofenumExampleEnumEXAMPLEENUMUNSPECIFIED OneofenumExampleEnum = "EXAMPLE_ENUM_UNSPECIFIED"

	// OneofenumExampleEnumEXAMPLEENUMFIRST captures enum value "EXAMPLE_ENUM_FIRST"
	OneofenumExampleEnumEXAMPLEENUMFIRST OneofenumExampleEnum = "EXAMPLE_ENUM_FIRST"
)

// for schema
var oneofenumExampleEnumEnum []any

func init() {
	var res []OneofenumExampleEnum
	if err := json.Unmarshal([]byte(`["EXAMPLE_ENUM_UNSPECIFIED","EXAMPLE_ENUM_FIRST"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		oneofenumExampleEnumEnum = append(oneofenumExampleEnumEnum, v)
	}
}

func (m OneofenumExampleEnum) validateOneofenumExampleEnumEnum(path, location string, value OneofenumExampleEnum) error {
	_ = "STUB: not implemented"
	return nil
}

// Validate validates this oneofenum example enum
func (m OneofenumExampleEnum) Validate(formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// value enum
	return nil
}

// ContextValidate validates this oneofenum example enum based on context it is used
func (m OneofenumExampleEnum) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}
