// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/strfmt"
)

// PathenumPathEnum pathenum path enum
//
// swagger:model pathenumPathEnum
type PathenumPathEnum string

func NewPathenumPathEnum(value PathenumPathEnum) *PathenumPathEnum {
	_ = "STUB: not implemented"

	// Pointer returns a pointer to a freshly-allocated PathenumPathEnum.
	return nil
}

func (m PathenumPathEnum) Pointer() *PathenumPathEnum { _ = "STUB: not implemented"; return nil }

const (

	// PathenumPathEnumABC captures enum value "ABC"
	PathenumPathEnumABC PathenumPathEnum = "ABC"

	// PathenumPathEnumDEF captures enum value "DEF"
	PathenumPathEnumDEF PathenumPathEnum = "DEF"
)

// for schema
var pathenumPathEnumEnum []any

func init() {
	var res []PathenumPathEnum
	if err := json.Unmarshal([]byte(`["ABC","DEF"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		pathenumPathEnumEnum = append(pathenumPathEnumEnum, v)
	}
}

func (m PathenumPathEnum) validatePathenumPathEnumEnum(path, location string, value PathenumPathEnum) error {
	_ = "STUB: not implemented"
	return nil
}

// Validate validates this pathenum path enum
func (m PathenumPathEnum) Validate(formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// value enum
	return nil
}

// ContextValidate validates this pathenum path enum based on context it is used
func (m PathenumPathEnum) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}
