// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// ProtoExamplepbFoo proto examplepb foo
//
// swagger:model protoExamplepbFoo
type ProtoExamplepbFoo struct {

	// bar
	// Required: true
	Bar *ExamplepbBar `json:"bar"`
}

// Validate validates this proto examplepb foo
func (m *ProtoExamplepbFoo) Validate(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ProtoExamplepbFoo) validateBar(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// ContextValidate validate this proto examplepb foo based on the context it is used
func (m *ProtoExamplepbFoo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ProtoExamplepbFoo) contextValidateBar(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// MarshalBinary interface implementation
func (m *ProtoExamplepbFoo) MarshalBinary() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalBinary interface implementation
func (m *ProtoExamplepbFoo) UnmarshalBinary(b []byte) error { _ = "STUB: not implemented"; return nil }
