// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// SubStringMessage sub string message
//
// swagger:model subStringMessage
type SubStringMessage struct {

	// value
	Value string `json:"value,omitempty"`
}

// Validate validates this sub string message
func (m *SubStringMessage) Validate(formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// ContextValidate validates this sub string message based on context it is used
	return nil
}

func (m *SubStringMessage) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// MarshalBinary interface implementation
	return nil
}

func (m *SubStringMessage) MarshalBinary() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalBinary interface implementation
func (m *SubStringMessage) UnmarshalBinary(b []byte) error { _ = "STUB: not implemented"; return nil }
