// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// ExamplepbGenerateUnboundMethodsSimpleMessage GenerateUnboundMethodsSimpleMessage represents a simple message sent to the unannotated GenerateUnboundMethodsEchoService service.
//
// swagger:model examplepbGenerateUnboundMethodsSimpleMessage
type ExamplepbGenerateUnboundMethodsSimpleMessage struct {

	// duration
	Duration string `json:"duration,omitempty"`

	// Id represents the message identifier.
	ID string `json:"id,omitempty"`

	// num
	Num string `json:"num,omitempty"`
}

// Validate validates this examplepb generate unbound methods simple message
func (m *ExamplepbGenerateUnboundMethodsSimpleMessage) Validate(formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// ContextValidate validates this examplepb generate unbound methods simple message based on context it is used
	return nil
}

func (m *ExamplepbGenerateUnboundMethodsSimpleMessage) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// MarshalBinary interface implementation
	return nil
}

func (m *ExamplepbGenerateUnboundMethodsSimpleMessage) MarshalBinary() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalBinary interface implementation
func (m *ExamplepbGenerateUnboundMethodsSimpleMessage) UnmarshalBinary(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}
