// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// ProtobufAny protobuf any
//
// swagger:model protobufAny
type ProtobufAny struct {

	// at type
	AtType string `json:"@type,omitempty"`

	// protobuf any
	ProtobufAny map[string]any `json:"-"`
}

// UnmarshalJSON unmarshals this object with additional properties from JSON
func (m *ProtobufAny) UnmarshalJSON(data []byte) error {
	_ = "STUB: not implemented"
	// stage 1, bind the properties
	return nil
}

// at type

// stage 2, remove properties and add to map

// stage 3, add additional properties values

// MarshalJSON marshals this object with additional properties into a JSON object
func (m ProtobufAny) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil,

		// at type
		nil
}

// make JSON object for known properties

// no additional properties

// make JSON object for the additional properties

// "{}": only additional properties

// concatenate the 2 objects

// Validate validates this protobuf any
func (m *ProtobufAny) Validate(formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// ContextValidate validates this protobuf any based on context it is used
	return nil
}

func (m *ProtobufAny) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// MarshalBinary interface implementation
	return nil
}

func (m *ProtobufAny) MarshalBinary() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// UnmarshalBinary interface implementation
func (m *ProtobufAny) UnmarshalBinary(b []byte) error { _ = "STUB: not implemented"; return nil }
