// Code generated by go-swagger; DO NOT EDIT.

package generate_unbound_methods_echo_service

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new generate unbound methods echo service API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	_ = "STUB: not implemented"
	return *new(ClientService)
}

// New creates a new generate unbound methods echo service API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	_ = "STUB: not implemented"
	return *new(ClientService)
}

// New creates a new generate unbound methods echo service API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	_ = "STUB: not implemented"
	return *new(ClientService)
}

/*
Client for generate unbound methods echo service API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GenerateUnboundMethodsEchoServiceEcho(params *GenerateUnboundMethodsEchoServiceEchoParams, opts ...ClientOption) (*GenerateUnboundMethodsEchoServiceEchoOK, error)

	GenerateUnboundMethodsEchoServiceEchoBody(params *GenerateUnboundMethodsEchoServiceEchoBodyParams, opts ...ClientOption) (*GenerateUnboundMethodsEchoServiceEchoBodyOK, error)

	GenerateUnboundMethodsEchoServiceEchoDelete(params *GenerateUnboundMethodsEchoServiceEchoDeleteParams, opts ...ClientOption) (*GenerateUnboundMethodsEchoServiceEchoDeleteOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
	GenerateUnboundMethodsEchoServiceEcho echos method receives a simple message and returns it

	The message posted as the id parameter will also be

returned.
*/
func (a *Client) GenerateUnboundMethodsEchoServiceEcho(params *GenerateUnboundMethodsEchoServiceEchoParams, opts ...ClientOption) (*GenerateUnboundMethodsEchoServiceEchoOK, error) {
	_ = "STUB: not implemented"
	// NOTE: parameters are not validated before sending
	return nil, nil
}

// only one success response has to be checked

// unexpected success response.
//
// a default response is provided: fill this and return an error

/*
GenerateUnboundMethodsEchoServiceEchoBody echos body method receives a simple message and returns it
*/
func (a *Client) GenerateUnboundMethodsEchoServiceEchoBody(params *GenerateUnboundMethodsEchoServiceEchoBodyParams, opts ...ClientOption) (*GenerateUnboundMethodsEchoServiceEchoBodyOK, error) {
	_ = "STUB: not implemented"
	// NOTE: parameters are not validated before sending
	return nil, nil
}

// only one success response has to be checked

// unexpected success response.
//
// a default response is provided: fill this and return an error

/*
GenerateUnboundMethodsEchoServiceEchoDelete echos delete method receives a simple message and returns it
*/
func (a *Client) GenerateUnboundMethodsEchoServiceEchoDelete(params *GenerateUnboundMethodsEchoServiceEchoDeleteParams, opts ...ClientOption) (*GenerateUnboundMethodsEchoServiceEchoDeleteOK, error) {
	_ = "STUB: not implemented"
	// NOTE: parameters are not validated before sending
	return nil, nil
}

// only one success response has to be checked

// unexpected success response.
//
// a default response is provided: fill this and return an error

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) { _ = "STUB: not implemented"; return }
