// Code generated by go-swagger; DO NOT EDIT.

package echo_rpc

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// NewABitOfEverythingServiceEcho2Params creates a new ABitOfEverythingServiceEcho2Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewABitOfEverythingServiceEcho2Params() *ABitOfEverythingServiceEcho2Params {
	_ = "STUB: not implemented"
	return nil
}

// NewABitOfEverythingServiceEcho2ParamsWithTimeout creates a new ABitOfEverythingServiceEcho2Params object
// with the ability to set a timeout on a request.
func NewABitOfEverythingServiceEcho2ParamsWithTimeout(timeout time.Duration) *ABitOfEverythingServiceEcho2Params {
	_ = "STUB: not implemented"
	return nil
}

// NewABitOfEverythingServiceEcho2ParamsWithContext creates a new ABitOfEverythingServiceEcho2Params object
// with the ability to set a context for a request.
func NewABitOfEverythingServiceEcho2ParamsWithContext(ctx context.Context) *ABitOfEverythingServiceEcho2Params {
	_ = "STUB: not implemented"
	return nil
}

// NewABitOfEverythingServiceEcho2ParamsWithHTTPClient creates a new ABitOfEverythingServiceEcho2Params object
// with the ability to set a custom HTTPClient for a request.
func NewABitOfEverythingServiceEcho2ParamsWithHTTPClient(client *http.Client) *ABitOfEverythingServiceEcho2Params {
	_ = "STUB: not implemented"
	return nil
}

/*
ABitOfEverythingServiceEcho2Params contains all the parameters to send to the API endpoint

	for the a bit of everything service echo2 operation.

	Typically these are written to a http.Request.
*/
type ABitOfEverythingServiceEcho2Params struct {

	// Value.
	Value string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the a bit of everything service echo2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ABitOfEverythingServiceEcho2Params) WithDefaults() *ABitOfEverythingServiceEcho2Params {
	_ = "STUB: not implemented"
	return nil

	// SetDefaults hydrates default values in the a bit of everything service echo2 params (not the query body).
	//
	// All values with no default are reset to their zero value.
}

func (o *ABitOfEverythingServiceEcho2Params) SetDefaults() {
	_ = "STUB: not implemented"
	// no default values defined for this parameter
	return
}

// WithTimeout adds the timeout to the a bit of everything service echo2 params
func (o *ABitOfEverythingServiceEcho2Params) WithTimeout(timeout time.Duration) *ABitOfEverythingServiceEcho2Params {
	_ = "STUB: not implemented"
	return nil
}

// SetTimeout adds the timeout to the a bit of everything service echo2 params
func (o *ABitOfEverythingServiceEcho2Params) SetTimeout(timeout time.Duration) {
	_ = "STUB: not implemented"
	return

	// WithContext adds the context to the a bit of everything service echo2 params
}

func (o *ABitOfEverythingServiceEcho2Params) WithContext(ctx context.Context) *ABitOfEverythingServiceEcho2Params {
	_ = "STUB: not implemented"
	return nil
}

// SetContext adds the context to the a bit of everything service echo2 params
func (o *ABitOfEverythingServiceEcho2Params) SetContext(ctx context.Context) {
	_ = "STUB: not implemented"

	// WithHTTPClient adds the HTTPClient to the a bit of everything service echo2 params
	return
}

func (o *ABitOfEverythingServiceEcho2Params) WithHTTPClient(client *http.Client) *ABitOfEverythingServiceEcho2Params {
	_ = "STUB: not implemented"
	return nil
}

// SetHTTPClient adds the HTTPClient to the a bit of everything service echo2 params
func (o *ABitOfEverythingServiceEcho2Params) SetHTTPClient(client *http.Client) {
	_ = "STUB: not implemented"
	return

	// WithValue adds the value to the a bit of everything service echo2 params
}

func (o *ABitOfEverythingServiceEcho2Params) WithValue(value string) *ABitOfEverythingServiceEcho2Params {
	_ = "STUB: not implemented"
	return nil
}

// SetValue adds the value to the a bit of everything service echo2 params
func (o *ABitOfEverythingServiceEcho2Params) SetValue(value string) {
	_ = "STUB: not implemented"

	// WriteToRequest writes these params to a swagger request
	return
}

func (o *ABitOfEverythingServiceEcho2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}
