// Code generated by go-swagger; DO NOT EDIT.

package echo_rpc

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new echo rpc API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	_ = "STUB: not implemented"
	return *new(ClientService)
}

// New creates a new echo rpc API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	_ = "STUB: not implemented"
	return *new(ClientService)
}

// New creates a new echo rpc API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	_ = "STUB: not implemented"
	return *new(ClientService)
}

/*
Client for echo rpc API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// This client is generated with a few options you might find useful for your swagger spec.
//
// Feel free to add you own set of options.

// WithContentType allows the client to force the Content-Type header
// to negotiate a specific Consumer from the server.
//
// You may use this option to set arbitrary extensions to your MIME media type.
func WithContentType(mime string) ClientOption {
	_ = "STUB: not implemented"
	return *new(ClientOption)
}

// WithContentTypeApplicationJSON sets the Content-Type header to "application/json".
func WithContentTypeApplicationJSON(r *runtime.ClientOperation) { _ = "STUB: not implemented"; return }

// WithContentTypeApplicationxFooMime sets the Content-Type header to "application/x-foo-mime".
func WithContentTypeApplicationxFooMime(r *runtime.ClientOperation) {
	_ = "STUB: not implemented"
	return
}

// WithAccept allows the client to force the Accept header
// to negotiate a specific Producer from the server.
//
// You may use this option to set arbitrary extensions to your MIME media type.
func WithAccept(mime string) ClientOption { _ = "STUB: not implemented"; return *new(ClientOption) }

// WithAcceptApplicationJSON sets the Accept header to "application/json".
func WithAcceptApplicationJSON(r *runtime.ClientOperation) { _ = "STUB: not implemented"; return }

// WithAcceptApplicationxFooMime sets the Accept header to "application/x-foo-mime".
func WithAcceptApplicationxFooMime(r *runtime.ClientOperation) { _ = "STUB: not implemented"; return }

// ClientService is the interface for Client methods
type ClientService interface {
	ABitOfEverythingServiceEcho(params *ABitOfEverythingServiceEchoParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ABitOfEverythingServiceEchoOK, error)

	ABitOfEverythingServiceEcho2(params *ABitOfEverythingServiceEcho2Params, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ABitOfEverythingServiceEcho2OK, error)

	ABitOfEverythingServiceEcho3(params *ABitOfEverythingServiceEcho3Params, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ABitOfEverythingServiceEcho3OK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
ABitOfEverythingServiceEcho summaries echo rpc

Description Echo
*/
func (a *Client) ABitOfEverythingServiceEcho(params *ABitOfEverythingServiceEchoParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ABitOfEverythingServiceEchoOK, error) {
	_ = "STUB: not implemented"
	// NOTE: parameters are not validated before sending
	return nil, nil
}

// only one success response has to be checked

// unexpected success response.
//
// a default response is provided: fill this and return an error

/*
ABitOfEverythingServiceEcho2 summaries echo rpc

Description Echo
*/
func (a *Client) ABitOfEverythingServiceEcho2(params *ABitOfEverythingServiceEcho2Params, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ABitOfEverythingServiceEcho2OK, error) {
	_ = "STUB: not implemented"
	// NOTE: parameters are not validated before sending
	return nil, nil
}

// only one success response has to be checked

// unexpected success response.
//
// a default response is provided: fill this and return an error

/*
ABitOfEverythingServiceEcho3 summaries echo rpc

Description Echo
*/
func (a *Client) ABitOfEverythingServiceEcho3(params *ABitOfEverythingServiceEcho3Params, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ABitOfEverythingServiceEcho3OK, error) {
	_ = "STUB: not implemented"
	// NOTE: parameters are not validated before sending
	return nil, nil
}

// only one success response has to be checked

// unexpected success response.
//
// a default response is provided: fill this and return an error

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) { _ = "STUB: not implemented"; return }
