// Code generated by go-swagger; DO NOT EDIT.

package unannotated_echo_service

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/grpc-ecosystem/grpc-gateway/v2/examples/internal/clients/unannotatedecho/models"
)

// UnannotatedEchoServiceEcho2Reader is a Reader for the UnannotatedEchoServiceEcho2 structure.
type UnannotatedEchoServiceEcho2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UnannotatedEchoServiceEcho2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

// NewUnannotatedEchoServiceEcho2OK creates a UnannotatedEchoServiceEcho2OK with default headers values
func NewUnannotatedEchoServiceEcho2OK() *UnannotatedEchoServiceEcho2OK {
	_ = "STUB: not implemented"
	return nil
}

/*
UnannotatedEchoServiceEcho2OK describes a response with status code 200, with default header values.

A successful response.
*/
type UnannotatedEchoServiceEcho2OK struct {
	Payload *models.ExamplepbUnannotatedSimpleMessage
}

// IsSuccess returns true when this unannotated echo service echo2 o k response has a 2xx status code
func (o *UnannotatedEchoServiceEcho2OK) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this unannotated echo service echo2 o k response has a 3xx status code
	return false
}

func (o *UnannotatedEchoServiceEcho2OK) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this unannotated echo service echo2 o k response has a 4xx status code
	return false
}

func (o *UnannotatedEchoServiceEcho2OK) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this unannotated echo service echo2 o k response has a 5xx status code
	return false
}

func (o *UnannotatedEchoServiceEcho2OK) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this unannotated echo service echo2 o k response a status code equal to that given
	return false
}

func (o *UnannotatedEchoServiceEcho2OK) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the unannotated echo service echo2 o k response
}

func (o *UnannotatedEchoServiceEcho2OK) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *UnannotatedEchoServiceEcho2OK) Error() string { _ = "STUB: not implemented"; return "" }

func (o *UnannotatedEchoServiceEcho2OK) String() string { _ = "STUB: not implemented"; return "" }

func (o *UnannotatedEchoServiceEcho2OK) GetPayload() *models.ExamplepbUnannotatedSimpleMessage {
	_ = "STUB: not implemented"
	return nil
}

func (o *UnannotatedEchoServiceEcho2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// response payload

// NewUnannotatedEchoServiceEcho2Forbidden creates a UnannotatedEchoServiceEcho2Forbidden with default headers values
func NewUnannotatedEchoServiceEcho2Forbidden() *UnannotatedEchoServiceEcho2Forbidden {
	_ = "STUB: not implemented"
	return nil
}

/*
UnannotatedEchoServiceEcho2Forbidden describes a response with status code 403, with default header values.

Returned when the user does not have permission to access the resource.
*/
type UnannotatedEchoServiceEcho2Forbidden struct {
	Payload any
}

// IsSuccess returns true when this unannotated echo service echo2 forbidden response has a 2xx status code
func (o *UnannotatedEchoServiceEcho2Forbidden) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this unannotated echo service echo2 forbidden response has a 3xx status code
	return false
}

func (o *UnannotatedEchoServiceEcho2Forbidden) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this unannotated echo service echo2 forbidden response has a 4xx status code
	return false
}

func (o *UnannotatedEchoServiceEcho2Forbidden) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this unannotated echo service echo2 forbidden response has a 5xx status code
	return false
}

func (o *UnannotatedEchoServiceEcho2Forbidden) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this unannotated echo service echo2 forbidden response a status code equal to that given
	return false
}

func (o *UnannotatedEchoServiceEcho2Forbidden) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the unannotated echo service echo2 forbidden response
}

func (o *UnannotatedEchoServiceEcho2Forbidden) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *UnannotatedEchoServiceEcho2Forbidden) Error() string { _ = "STUB: not implemented"; return "" }

func (o *UnannotatedEchoServiceEcho2Forbidden) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *UnannotatedEchoServiceEcho2Forbidden) GetPayload() any {
	_ = "STUB: not implemented"
	return *new(any)
}

func (o *UnannotatedEchoServiceEcho2Forbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// response payload
	return nil
}

// NewUnannotatedEchoServiceEcho2NotFound creates a UnannotatedEchoServiceEcho2NotFound with default headers values
func NewUnannotatedEchoServiceEcho2NotFound() *UnannotatedEchoServiceEcho2NotFound {
	_ = "STUB: not implemented"
	return nil
}

/*
UnannotatedEchoServiceEcho2NotFound describes a response with status code 404, with default header values.

Returned when the resource does not exist.
*/
type UnannotatedEchoServiceEcho2NotFound struct {
	Payload int64
}

// IsSuccess returns true when this unannotated echo service echo2 not found response has a 2xx status code
func (o *UnannotatedEchoServiceEcho2NotFound) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this unannotated echo service echo2 not found response has a 3xx status code
	return false
}

func (o *UnannotatedEchoServiceEcho2NotFound) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this unannotated echo service echo2 not found response has a 4xx status code
	return false
}

func (o *UnannotatedEchoServiceEcho2NotFound) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this unannotated echo service echo2 not found response has a 5xx status code
	return false
}

func (o *UnannotatedEchoServiceEcho2NotFound) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this unannotated echo service echo2 not found response a status code equal to that given
	return false
}

func (o *UnannotatedEchoServiceEcho2NotFound) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the unannotated echo service echo2 not found response
}

func (o *UnannotatedEchoServiceEcho2NotFound) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *UnannotatedEchoServiceEcho2NotFound) Error() string { _ = "STUB: not implemented"; return "" }

func (o *UnannotatedEchoServiceEcho2NotFound) String() string { _ = "STUB: not implemented"; return "" }

func (o *UnannotatedEchoServiceEcho2NotFound) GetPayload() int64 {
	_ = "STUB: not implemented"
	return 0
}

func (o *UnannotatedEchoServiceEcho2NotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// response payload
	return nil
}

// NewUnannotatedEchoServiceEcho2ServiceUnavailable creates a UnannotatedEchoServiceEcho2ServiceUnavailable with default headers values
func NewUnannotatedEchoServiceEcho2ServiceUnavailable() *UnannotatedEchoServiceEcho2ServiceUnavailable {
	_ = "STUB: not implemented"
	return nil
}

/*
UnannotatedEchoServiceEcho2ServiceUnavailable describes a response with status code 503, with default header values.

Returned when the resource is temporarily unavailable.
*/
type UnannotatedEchoServiceEcho2ServiceUnavailable struct {
	Payload any
}

// IsSuccess returns true when this unannotated echo service echo2 service unavailable response has a 2xx status code
func (o *UnannotatedEchoServiceEcho2ServiceUnavailable) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this unannotated echo service echo2 service unavailable response has a 3xx status code
	return false
}

func (o *UnannotatedEchoServiceEcho2ServiceUnavailable) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this unannotated echo service echo2 service unavailable response has a 4xx status code
	return false
}

func (o *UnannotatedEchoServiceEcho2ServiceUnavailable) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this unannotated echo service echo2 service unavailable response has a 5xx status code
	return false
}

func (o *UnannotatedEchoServiceEcho2ServiceUnavailable) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this unannotated echo service echo2 service unavailable response a status code equal to that given
	return false
}

func (o *UnannotatedEchoServiceEcho2ServiceUnavailable) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the unannotated echo service echo2 service unavailable response
}

func (o *UnannotatedEchoServiceEcho2ServiceUnavailable) Code() int {
	_ = "STUB: not implemented"
	return 0
}

func (o *UnannotatedEchoServiceEcho2ServiceUnavailable) Error() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *UnannotatedEchoServiceEcho2ServiceUnavailable) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *UnannotatedEchoServiceEcho2ServiceUnavailable) GetPayload() any {
	_ = "STUB: not implemented"
	return *new(any)
}

func (o *UnannotatedEchoServiceEcho2ServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// response payload
	return nil
}

// NewUnannotatedEchoServiceEcho2Default creates a UnannotatedEchoServiceEcho2Default with default headers values
func NewUnannotatedEchoServiceEcho2Default(code int) *UnannotatedEchoServiceEcho2Default {
	_ = "STUB: not implemented"
	return nil
}

/*
UnannotatedEchoServiceEcho2Default describes a response with status code -1, with default header values.

An unexpected error response.
*/
type UnannotatedEchoServiceEcho2Default struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this unannotated echo service echo2 default response has a 2xx status code
func (o *UnannotatedEchoServiceEcho2Default) IsSuccess() bool {
	_ = "STUB: not implemented"
	return false
}

// IsRedirect returns true when this unannotated echo service echo2 default response has a 3xx status code
func (o *UnannotatedEchoServiceEcho2Default) IsRedirect() bool {
	_ = "STUB: not implemented"
	return false
}

// IsClientError returns true when this unannotated echo service echo2 default response has a 4xx status code
func (o *UnannotatedEchoServiceEcho2Default) IsClientError() bool {
	_ = "STUB: not implemented"
	return false
}

// IsServerError returns true when this unannotated echo service echo2 default response has a 5xx status code
func (o *UnannotatedEchoServiceEcho2Default) IsServerError() bool {
	_ = "STUB: not implemented"
	return false
}

// IsCode returns true when this unannotated echo service echo2 default response a status code equal to that given
func (o *UnannotatedEchoServiceEcho2Default) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the unannotated echo service echo2 default response
}

func (o *UnannotatedEchoServiceEcho2Default) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *UnannotatedEchoServiceEcho2Default) Error() string { _ = "STUB: not implemented"; return "" }

func (o *UnannotatedEchoServiceEcho2Default) String() string { _ = "STUB: not implemented"; return "" }

func (o *UnannotatedEchoServiceEcho2Default) GetPayload() *models.RPCStatus {
	_ = "STUB: not implemented"
	return nil
}

func (o *UnannotatedEchoServiceEcho2Default) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// response payload
