// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/strfmt"
)

// ProtobufNullValue `NullValue` is a singleton enumeration to represent the null value for the
// `Value` type union.
//
// The JSON representation for `NullValue` is JSON `null`.
//
//   - NULL_VALUE: Null value.
//
// swagger:model protobufNullValue
type ProtobufNullValue string

func NewProtobufNullValue(value ProtobufNullValue) *ProtobufNullValue {
	_ = "STUB: not implemented"

	// Pointer returns a pointer to a freshly-allocated ProtobufNullValue.
	return nil
}

func (m ProtobufNullValue) Pointer() *ProtobufNullValue { _ = "STUB: not implemented"; return nil }

const (

	// ProtobufNullValueNULLVALUE captures enum value "NULL_VALUE"
	ProtobufNullValueNULLVALUE ProtobufNullValue = "NULL_VALUE"
)

// for schema
var protobufNullValueEnum []any

func init() {
	var res []ProtobufNullValue
	if err := json.Unmarshal([]byte(`["NULL_VALUE"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		protobufNullValueEnum = append(protobufNullValueEnum, v)
	}
}

func (m ProtobufNullValue) validateProtobufNullValueEnum(path, location string, value ProtobufNullValue) error {
	_ = "STUB: not implemented"
	return nil
}

// Validate validates this protobuf null value
func (m ProtobufNullValue) Validate(formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// value enum
	return nil
}

// ContextValidate validates this protobuf null value based on context it is used
func (m ProtobufNullValue) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}
