// Code generated by go-swagger; DO NOT EDIT.

package echo_service

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/grpc-ecosystem/grpc-gateway/v2/examples/internal/clients/echo/models"
)

// NewEchoServiceEchoStatusParams creates a new EchoServiceEchoStatusParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewEchoServiceEchoStatusParams() *EchoServiceEchoStatusParams {
	_ = "STUB: not implemented"
	return nil
}

// NewEchoServiceEchoStatusParamsWithTimeout creates a new EchoServiceEchoStatusParams object
// with the ability to set a timeout on a request.
func NewEchoServiceEchoStatusParamsWithTimeout(timeout time.Duration) *EchoServiceEchoStatusParams {
	_ = "STUB: not implemented"
	return nil
}

// NewEchoServiceEchoStatusParamsWithContext creates a new EchoServiceEchoStatusParams object
// with the ability to set a context for a request.
func NewEchoServiceEchoStatusParamsWithContext(ctx context.Context) *EchoServiceEchoStatusParams {
	_ = "STUB: not implemented"
	return nil
}

// NewEchoServiceEchoStatusParamsWithHTTPClient creates a new EchoServiceEchoStatusParams object
// with the ability to set a custom HTTPClient for a request.
func NewEchoServiceEchoStatusParamsWithHTTPClient(client *http.Client) *EchoServiceEchoStatusParams {
	_ = "STUB: not implemented"
	return nil
}

/*
EchoServiceEchoStatusParams contains all the parameters to send to the API endpoint

	for the echo service echo status operation.

	Typically these are written to a http.Request.
*/
type EchoServiceEchoStatusParams struct {

	/* Body.

	     StatusCheckRequest demonstrates name collision handling.
	It uses Status message from both sub and sub2 packages.
	*/
	Body *models.ExamplepbStatusCheckRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the echo service echo status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EchoServiceEchoStatusParams) WithDefaults() *EchoServiceEchoStatusParams {
	_ = "STUB: not implemented"
	return nil

	// SetDefaults hydrates default values in the echo service echo status params (not the query body).
	//
	// All values with no default are reset to their zero value.
}

func (o *EchoServiceEchoStatusParams) SetDefaults() {
	_ = "STUB: not implemented"
	// no default values defined for this parameter
	return
}

// WithTimeout adds the timeout to the echo service echo status params
func (o *EchoServiceEchoStatusParams) WithTimeout(timeout time.Duration) *EchoServiceEchoStatusParams {
	_ = "STUB: not implemented"
	return nil
}

// SetTimeout adds the timeout to the echo service echo status params
func (o *EchoServiceEchoStatusParams) SetTimeout(timeout time.Duration) {
	_ = "STUB: not implemented"
	return

	// WithContext adds the context to the echo service echo status params
}

func (o *EchoServiceEchoStatusParams) WithContext(ctx context.Context) *EchoServiceEchoStatusParams {
	_ = "STUB: not implemented"
	return nil
}

// SetContext adds the context to the echo service echo status params
func (o *EchoServiceEchoStatusParams) SetContext(ctx context.Context) {
	_ = "STUB: not implemented"

	// WithHTTPClient adds the HTTPClient to the echo service echo status params
	return
}

func (o *EchoServiceEchoStatusParams) WithHTTPClient(client *http.Client) *EchoServiceEchoStatusParams {
	_ = "STUB: not implemented"
	return nil
}

// SetHTTPClient adds the HTTPClient to the echo service echo status params
func (o *EchoServiceEchoStatusParams) SetHTTPClient(client *http.Client) {
	_ = "STUB: not implemented"
	return

	// WithBody adds the body to the echo service echo status params
}

func (o *EchoServiceEchoStatusParams) WithBody(body *models.ExamplepbStatusCheckRequest) *EchoServiceEchoStatusParams {
	_ = "STUB: not implemented"
	return nil

	// SetBody adds the body to the echo service echo status params
}

func (o *EchoServiceEchoStatusParams) SetBody(body *models.ExamplepbStatusCheckRequest) {
	_ = "STUB: not implemented"

	// WriteToRequest writes these params to a swagger request
	return
}

func (o *EchoServiceEchoStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}
