// Code generated by go-swagger; DO NOT EDIT.

package echo_service

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/grpc-ecosystem/grpc-gateway/v2/examples/internal/clients/echo/models"
)

// EchoServiceEcho5Reader is a Reader for the EchoServiceEcho5 structure.
type EchoServiceEcho5Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EchoServiceEcho5Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

// NewEchoServiceEcho5OK creates a EchoServiceEcho5OK with default headers values
func NewEchoServiceEcho5OK() *EchoServiceEcho5OK { _ = "STUB: not implemented"; return nil }

/*
EchoServiceEcho5OK describes a response with status code 200, with default header values.

A successful response.
*/
type EchoServiceEcho5OK struct {
	Payload *models.ExamplepbSimpleMessage
}

// IsSuccess returns true when this echo service echo5 o k response has a 2xx status code
func (o *EchoServiceEcho5OK) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this echo service echo5 o k response has a 3xx status code
	return false
}

func (o *EchoServiceEcho5OK) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this echo service echo5 o k response has a 4xx status code
	return false
}

func (o *EchoServiceEcho5OK) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this echo service echo5 o k response has a 5xx status code
	return false
}

func (o *EchoServiceEcho5OK) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this echo service echo5 o k response a status code equal to that given
	return false
}

func (o *EchoServiceEcho5OK) IsCode(code int) bool {
	_ = "STUB: not implemented"

	// Code gets the status code for the echo service echo5 o k response
	return false
}

func (o *EchoServiceEcho5OK) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *EchoServiceEcho5OK) Error() string { _ = "STUB: not implemented"; return "" }

func (o *EchoServiceEcho5OK) String() string { _ = "STUB: not implemented"; return "" }

func (o *EchoServiceEcho5OK) GetPayload() *models.ExamplepbSimpleMessage {
	_ = "STUB: not implemented"
	return nil
}

func (o *EchoServiceEcho5OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// response payload

// NewEchoServiceEcho5Default creates a EchoServiceEcho5Default with default headers values
func NewEchoServiceEcho5Default(code int) *EchoServiceEcho5Default {
	_ = "STUB: not implemented"
	return nil
}

/*
EchoServiceEcho5Default describes a response with status code -1, with default header values.

An unexpected error response.
*/
type EchoServiceEcho5Default struct {
	_statusCode int

	Payload *models.GoogleRPCStatus
}

// IsSuccess returns true when this echo service echo5 default response has a 2xx status code
func (o *EchoServiceEcho5Default) IsSuccess() bool { _ = "STUB: not implemented"; return false }

// IsRedirect returns true when this echo service echo5 default response has a 3xx status code
func (o *EchoServiceEcho5Default) IsRedirect() bool { _ = "STUB: not implemented"; return false }

// IsClientError returns true when this echo service echo5 default response has a 4xx status code
func (o *EchoServiceEcho5Default) IsClientError() bool { _ = "STUB: not implemented"; return false }

// IsServerError returns true when this echo service echo5 default response has a 5xx status code
func (o *EchoServiceEcho5Default) IsServerError() bool { _ = "STUB: not implemented"; return false }

// IsCode returns true when this echo service echo5 default response a status code equal to that given
func (o *EchoServiceEcho5Default) IsCode(code int) bool { _ = "STUB: not implemented"; return false }

// Code gets the status code for the echo service echo5 default response
func (o *EchoServiceEcho5Default) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *EchoServiceEcho5Default) Error() string { _ = "STUB: not implemented"; return "" }

func (o *EchoServiceEcho5Default) String() string { _ = "STUB: not implemented"; return "" }

func (o *EchoServiceEcho5Default) GetPayload() *models.GoogleRPCStatus {
	_ = "STUB: not implemented"
	return nil
}

func (o *EchoServiceEcho5Default) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// response payload
