// Code generated by go-swagger; DO NOT EDIT.

package echo_service

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/grpc-ecosystem/grpc-gateway/v2/examples/internal/clients/echo/models"
)

// EchoServiceEchoPatchReader is a Reader for the EchoServiceEchoPatch structure.
type EchoServiceEchoPatchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EchoServiceEchoPatchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

// NewEchoServiceEchoPatchOK creates a EchoServiceEchoPatchOK with default headers values
func NewEchoServiceEchoPatchOK() *EchoServiceEchoPatchOK { _ = "STUB: not implemented"; return nil }

/*
EchoServiceEchoPatchOK describes a response with status code 200, with default header values.

A successful response.
*/
type EchoServiceEchoPatchOK struct {
	Payload *models.ExamplepbDynamicMessageUpdate
}

// IsSuccess returns true when this echo service echo patch o k response has a 2xx status code
func (o *EchoServiceEchoPatchOK) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this echo service echo patch o k response has a 3xx status code
	return false
}

func (o *EchoServiceEchoPatchOK) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this echo service echo patch o k response has a 4xx status code
	return false
}

func (o *EchoServiceEchoPatchOK) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this echo service echo patch o k response has a 5xx status code
	return false
}

func (o *EchoServiceEchoPatchOK) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this echo service echo patch o k response a status code equal to that given
	return false
}

func (o *EchoServiceEchoPatchOK) IsCode(code int) bool {
	_ = "STUB: not implemented"

	// Code gets the status code for the echo service echo patch o k response
	return false
}

func (o *EchoServiceEchoPatchOK) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *EchoServiceEchoPatchOK) Error() string { _ = "STUB: not implemented"; return "" }

func (o *EchoServiceEchoPatchOK) String() string { _ = "STUB: not implemented"; return "" }

func (o *EchoServiceEchoPatchOK) GetPayload() *models.ExamplepbDynamicMessageUpdate {
	_ = "STUB: not implemented"
	return nil
}

func (o *EchoServiceEchoPatchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// response payload

// NewEchoServiceEchoPatchDefault creates a EchoServiceEchoPatchDefault with default headers values
func NewEchoServiceEchoPatchDefault(code int) *EchoServiceEchoPatchDefault {
	_ = "STUB: not implemented"
	return nil
}

/*
EchoServiceEchoPatchDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type EchoServiceEchoPatchDefault struct {
	_statusCode int

	Payload *models.GoogleRPCStatus
}

// IsSuccess returns true when this echo service echo patch default response has a 2xx status code
func (o *EchoServiceEchoPatchDefault) IsSuccess() bool { _ = "STUB: not implemented"; return false }

// IsRedirect returns true when this echo service echo patch default response has a 3xx status code
func (o *EchoServiceEchoPatchDefault) IsRedirect() bool { _ = "STUB: not implemented"; return false }

// IsClientError returns true when this echo service echo patch default response has a 4xx status code
func (o *EchoServiceEchoPatchDefault) IsClientError() bool { _ = "STUB: not implemented"; return false }

// IsServerError returns true when this echo service echo patch default response has a 5xx status code
func (o *EchoServiceEchoPatchDefault) IsServerError() bool { _ = "STUB: not implemented"; return false }

// IsCode returns true when this echo service echo patch default response a status code equal to that given
func (o *EchoServiceEchoPatchDefault) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the echo service echo patch default response
}

func (o *EchoServiceEchoPatchDefault) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *EchoServiceEchoPatchDefault) Error() string { _ = "STUB: not implemented"; return "" }

func (o *EchoServiceEchoPatchDefault) String() string { _ = "STUB: not implemented"; return "" }

func (o *EchoServiceEchoPatchDefault) GetPayload() *models.GoogleRPCStatus {
	_ = "STUB: not implemented"
	return nil
}

func (o *EchoServiceEchoPatchDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// response payload
