// Code generated by go-swagger; DO NOT EDIT.

package echo_service

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/grpc-ecosystem/grpc-gateway/v2/examples/internal/clients/echo/models"
)

// EchoServiceEchoStatusReader is a Reader for the EchoServiceEchoStatus structure.
type EchoServiceEchoStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EchoServiceEchoStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

// NewEchoServiceEchoStatusOK creates a EchoServiceEchoStatusOK with default headers values
func NewEchoServiceEchoStatusOK() *EchoServiceEchoStatusOK { _ = "STUB: not implemented"; return nil }

/*
EchoServiceEchoStatusOK describes a response with status code 200, with default header values.

A successful response.
*/
type EchoServiceEchoStatusOK struct {
	Payload *models.ExamplepbStatusCheckResponse
}

// IsSuccess returns true when this echo service echo status o k response has a 2xx status code
func (o *EchoServiceEchoStatusOK) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this echo service echo status o k response has a 3xx status code
	return false
}

func (o *EchoServiceEchoStatusOK) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this echo service echo status o k response has a 4xx status code
	return false
}

func (o *EchoServiceEchoStatusOK) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this echo service echo status o k response has a 5xx status code
	return false
}

func (o *EchoServiceEchoStatusOK) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this echo service echo status o k response a status code equal to that given
	return false
}

func (o *EchoServiceEchoStatusOK) IsCode(code int) bool {
	_ = "STUB: not implemented"

	// Code gets the status code for the echo service echo status o k response
	return false
}

func (o *EchoServiceEchoStatusOK) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *EchoServiceEchoStatusOK) Error() string { _ = "STUB: not implemented"; return "" }

func (o *EchoServiceEchoStatusOK) String() string { _ = "STUB: not implemented"; return "" }

func (o *EchoServiceEchoStatusOK) GetPayload() *models.ExamplepbStatusCheckResponse {
	_ = "STUB: not implemented"
	return nil
}

func (o *EchoServiceEchoStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// response payload

// NewEchoServiceEchoStatusDefault creates a EchoServiceEchoStatusDefault with default headers values
func NewEchoServiceEchoStatusDefault(code int) *EchoServiceEchoStatusDefault {
	_ = "STUB: not implemented"
	return nil
}

/*
EchoServiceEchoStatusDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type EchoServiceEchoStatusDefault struct {
	_statusCode int

	Payload *models.GoogleRPCStatus
}

// IsSuccess returns true when this echo service echo status default response has a 2xx status code
func (o *EchoServiceEchoStatusDefault) IsSuccess() bool { _ = "STUB: not implemented"; return false }

// IsRedirect returns true when this echo service echo status default response has a 3xx status code
func (o *EchoServiceEchoStatusDefault) IsRedirect() bool { _ = "STUB: not implemented"; return false }

// IsClientError returns true when this echo service echo status default response has a 4xx status code
func (o *EchoServiceEchoStatusDefault) IsClientError() bool {
	_ = "STUB: not implemented"
	return false
}

// IsServerError returns true when this echo service echo status default response has a 5xx status code
func (o *EchoServiceEchoStatusDefault) IsServerError() bool {
	_ = "STUB: not implemented"
	return false
}

// IsCode returns true when this echo service echo status default response a status code equal to that given
func (o *EchoServiceEchoStatusDefault) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the echo service echo status default response
}

func (o *EchoServiceEchoStatusDefault) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *EchoServiceEchoStatusDefault) Error() string { _ = "STUB: not implemented"; return "" }

func (o *EchoServiceEchoStatusDefault) String() string { _ = "STUB: not implemented"; return "" }

func (o *EchoServiceEchoStatusDefault) GetPayload() *models.GoogleRPCStatus {
	_ = "STUB: not implemented"
	return nil
}

func (o *EchoServiceEchoStatusDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// response payload
