// Code generated by go-swagger; DO NOT EDIT.

package echo_service

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// NewEchoServiceEcho4Params creates a new EchoServiceEcho4Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewEchoServiceEcho4Params() *EchoServiceEcho4Params { _ = "STUB: not implemented"; return nil }

// NewEchoServiceEcho4ParamsWithTimeout creates a new EchoServiceEcho4Params object
// with the ability to set a timeout on a request.
func NewEchoServiceEcho4ParamsWithTimeout(timeout time.Duration) *EchoServiceEcho4Params {
	_ = "STUB: not implemented"
	return nil
}

// NewEchoServiceEcho4ParamsWithContext creates a new EchoServiceEcho4Params object
// with the ability to set a context for a request.
func NewEchoServiceEcho4ParamsWithContext(ctx context.Context) *EchoServiceEcho4Params {
	_ = "STUB: not implemented"
	return nil
}

// NewEchoServiceEcho4ParamsWithHTTPClient creates a new EchoServiceEcho4Params object
// with the ability to set a custom HTTPClient for a request.
func NewEchoServiceEcho4ParamsWithHTTPClient(client *http.Client) *EchoServiceEcho4Params {
	_ = "STUB: not implemented"
	return nil
}

/*
EchoServiceEcho4Params contains all the parameters to send to the API endpoint

	for the echo service echo4 operation.

	Typically these are written to a http.Request.
*/
type EchoServiceEcho4Params struct {

	// En.
	//
	// Format: int64
	En *string

	/* ID.

	   Id represents the message identifier.
	*/
	ID string

	// Lang.
	Lang *string

	// LineNum.
	//
	// Format: int64
	LineNum string

	// NIDnID.
	NIDnID *string

	// NIDVal.
	NIDVal *string

	// NoProgress.
	//
	// Format: int64
	NoProgress *string

	// Num.
	//
	// Format: int64
	Num *string

	// ResourceID.
	ResourceID *string

	// StatusNote.
	StatusNote string

	// StatusProgress.
	//
	// Format: int64
	StatusProgress *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the echo service echo4 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EchoServiceEcho4Params) WithDefaults() *EchoServiceEcho4Params {
	_ = "STUB: not implemented"
	return nil

	// SetDefaults hydrates default values in the echo service echo4 params (not the query body).
	//
	// All values with no default are reset to their zero value.
}

func (o *EchoServiceEcho4Params) SetDefaults() {
	_ = "STUB: not implemented"
	// no default values defined for this parameter
	return
}

// WithTimeout adds the timeout to the echo service echo4 params
func (o *EchoServiceEcho4Params) WithTimeout(timeout time.Duration) *EchoServiceEcho4Params {
	_ = "STUB: not implemented"
	return nil
}

// SetTimeout adds the timeout to the echo service echo4 params
func (o *EchoServiceEcho4Params) SetTimeout(timeout time.Duration) {
	_ = "STUB: not implemented"
	return

	// WithContext adds the context to the echo service echo4 params
}

func (o *EchoServiceEcho4Params) WithContext(ctx context.Context) *EchoServiceEcho4Params {
	_ = "STUB: not implemented"
	return nil
}

// SetContext adds the context to the echo service echo4 params
func (o *EchoServiceEcho4Params) SetContext(ctx context.Context) {
	_ = "STUB: not implemented"

	// WithHTTPClient adds the HTTPClient to the echo service echo4 params
	return
}

func (o *EchoServiceEcho4Params) WithHTTPClient(client *http.Client) *EchoServiceEcho4Params {
	_ = "STUB: not implemented"
	return nil
}

// SetHTTPClient adds the HTTPClient to the echo service echo4 params
func (o *EchoServiceEcho4Params) SetHTTPClient(client *http.Client) {
	_ = "STUB: not implemented"
	return

	// WithEn adds the en to the echo service echo4 params
}

func (o *EchoServiceEcho4Params) WithEn(en *string) *EchoServiceEcho4Params {
	_ = "STUB: not implemented"
	return nil

	// SetEn adds the en to the echo service echo4 params
}

func (o *EchoServiceEcho4Params) SetEn(en *string) {
	_ = "STUB: not implemented"

	// WithID adds the id to the echo service echo4 params
	return
}

func (o *EchoServiceEcho4Params) WithID(id string) *EchoServiceEcho4Params {
	_ = "STUB: not implemented"
	return nil

	// SetID adds the id to the echo service echo4 params
}

func (o *EchoServiceEcho4Params) SetID(id string) {
	_ = "STUB: not implemented"

	// WithLang adds the lang to the echo service echo4 params
	return
}

func (o *EchoServiceEcho4Params) WithLang(lang *string) *EchoServiceEcho4Params {
	_ = "STUB: not implemented"
	return nil

	// SetLang adds the lang to the echo service echo4 params
}

func (o *EchoServiceEcho4Params) SetLang(lang *string) {
	_ = "STUB: not implemented"

	// WithLineNum adds the lineNum to the echo service echo4 params
	return
}

func (o *EchoServiceEcho4Params) WithLineNum(lineNum string) *EchoServiceEcho4Params {
	_ = "STUB: not implemented"
	return nil
}

// SetLineNum adds the lineNum to the echo service echo4 params
func (o *EchoServiceEcho4Params) SetLineNum(lineNum string) { _ = "STUB: not implemented"; return }

// WithNIDnID adds the nIDnID to the echo service echo4 params
func (o *EchoServiceEcho4Params) WithNIDnID(nIDnID *string) *EchoServiceEcho4Params {
	_ = "STUB: not implemented"
	return nil
}

// SetNIDnID adds the nIdNId to the echo service echo4 params
func (o *EchoServiceEcho4Params) SetNIDnID(nIDnID *string) {
	_ = "STUB: not implemented"

	// WithNIDVal adds the nIDVal to the echo service echo4 params
	return
}

func (o *EchoServiceEcho4Params) WithNIDVal(nIDVal *string) *EchoServiceEcho4Params {
	_ = "STUB: not implemented"
	return nil
}

// SetNIDVal adds the nIdVal to the echo service echo4 params
func (o *EchoServiceEcho4Params) SetNIDVal(nIDVal *string) {
	_ = "STUB: not implemented"

	// WithNoProgress adds the noProgress to the echo service echo4 params
	return
}

func (o *EchoServiceEcho4Params) WithNoProgress(noProgress *string) *EchoServiceEcho4Params {
	_ = "STUB: not implemented"
	return nil
}

// SetNoProgress adds the noProgress to the echo service echo4 params
func (o *EchoServiceEcho4Params) SetNoProgress(noProgress *string) {
	_ = "STUB: not implemented"
	return
}

// WithNum adds the num to the echo service echo4 params
func (o *EchoServiceEcho4Params) WithNum(num *string) *EchoServiceEcho4Params {
	_ = "STUB: not implemented"
	return nil

	// SetNum adds the num to the echo service echo4 params
}

func (o *EchoServiceEcho4Params) SetNum(num *string) {
	_ = "STUB: not implemented"

	// WithResourceID adds the resourceID to the echo service echo4 params
	return
}

func (o *EchoServiceEcho4Params) WithResourceID(resourceID *string) *EchoServiceEcho4Params {
	_ = "STUB: not implemented"
	return nil
}

// SetResourceID adds the resourceId to the echo service echo4 params
func (o *EchoServiceEcho4Params) SetResourceID(resourceID *string) {
	_ = "STUB: not implemented"
	return
}

// WithStatusNote adds the statusNote to the echo service echo4 params
func (o *EchoServiceEcho4Params) WithStatusNote(statusNote string) *EchoServiceEcho4Params {
	_ = "STUB: not implemented"
	return nil
}

// SetStatusNote adds the statusNote to the echo service echo4 params
func (o *EchoServiceEcho4Params) SetStatusNote(statusNote string) {
	_ = "STUB: not implemented"
	return
}

// WithStatusProgress adds the statusProgress to the echo service echo4 params
func (o *EchoServiceEcho4Params) WithStatusProgress(statusProgress *string) *EchoServiceEcho4Params {
	_ = "STUB: not implemented"
	return nil
}

// SetStatusProgress adds the statusProgress to the echo service echo4 params
func (o *EchoServiceEcho4Params) SetStatusProgress(statusProgress *string) {
	_ = "STUB: not implemented"
	return
}

// WriteToRequest writes these params to a swagger request
func (o *EchoServiceEcho4Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// query param en

// path param id

// query param lang

// path param lineNum

// query param nId.nId

// query param nId.val

// query param no.progress

// query param num

// query param resourceId

// path param status.note

// query param status.progress
