// Code generated by go-swagger; DO NOT EDIT.

package echo_service

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// NewEchoServiceEchoDeleteParams creates a new EchoServiceEchoDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewEchoServiceEchoDeleteParams() *EchoServiceEchoDeleteParams {
	_ = "STUB: not implemented"
	return nil
}

// NewEchoServiceEchoDeleteParamsWithTimeout creates a new EchoServiceEchoDeleteParams object
// with the ability to set a timeout on a request.
func NewEchoServiceEchoDeleteParamsWithTimeout(timeout time.Duration) *EchoServiceEchoDeleteParams {
	_ = "STUB: not implemented"
	return nil
}

// NewEchoServiceEchoDeleteParamsWithContext creates a new EchoServiceEchoDeleteParams object
// with the ability to set a context for a request.
func NewEchoServiceEchoDeleteParamsWithContext(ctx context.Context) *EchoServiceEchoDeleteParams {
	_ = "STUB: not implemented"
	return nil
}

// NewEchoServiceEchoDeleteParamsWithHTTPClient creates a new EchoServiceEchoDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewEchoServiceEchoDeleteParamsWithHTTPClient(client *http.Client) *EchoServiceEchoDeleteParams {
	_ = "STUB: not implemented"
	return nil
}

/*
EchoServiceEchoDeleteParams contains all the parameters to send to the API endpoint

	for the echo service echo delete operation.

	Typically these are written to a http.Request.
*/
type EchoServiceEchoDeleteParams struct {

	// En.
	//
	// Format: int64
	En *string

	/* ID.

	   Id represents the message identifier.
	*/
	ID *string

	// Lang.
	Lang *string

	// LineNum.
	//
	// Format: int64
	LineNum *string

	// NIDnID.
	NIDnID *string

	// NIDVal.
	NIDVal *string

	// NoNote.
	NoNote *string

	// NoProgress.
	//
	// Format: int64
	NoProgress *string

	// Num.
	//
	// Format: int64
	Num *string

	// ResourceID.
	ResourceID *string

	// StatusNote.
	StatusNote *string

	// StatusProgress.
	//
	// Format: int64
	StatusProgress *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the echo service echo delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EchoServiceEchoDeleteParams) WithDefaults() *EchoServiceEchoDeleteParams {
	_ = "STUB: not implemented"
	return nil

	// SetDefaults hydrates default values in the echo service echo delete params (not the query body).
	//
	// All values with no default are reset to their zero value.
}

func (o *EchoServiceEchoDeleteParams) SetDefaults() {
	_ = "STUB: not implemented"
	// no default values defined for this parameter
	return
}

// WithTimeout adds the timeout to the echo service echo delete params
func (o *EchoServiceEchoDeleteParams) WithTimeout(timeout time.Duration) *EchoServiceEchoDeleteParams {
	_ = "STUB: not implemented"
	return nil
}

// SetTimeout adds the timeout to the echo service echo delete params
func (o *EchoServiceEchoDeleteParams) SetTimeout(timeout time.Duration) {
	_ = "STUB: not implemented"
	return

	// WithContext adds the context to the echo service echo delete params
}

func (o *EchoServiceEchoDeleteParams) WithContext(ctx context.Context) *EchoServiceEchoDeleteParams {
	_ = "STUB: not implemented"
	return nil
}

// SetContext adds the context to the echo service echo delete params
func (o *EchoServiceEchoDeleteParams) SetContext(ctx context.Context) {
	_ = "STUB: not implemented"

	// WithHTTPClient adds the HTTPClient to the echo service echo delete params
	return
}

func (o *EchoServiceEchoDeleteParams) WithHTTPClient(client *http.Client) *EchoServiceEchoDeleteParams {
	_ = "STUB: not implemented"
	return nil
}

// SetHTTPClient adds the HTTPClient to the echo service echo delete params
func (o *EchoServiceEchoDeleteParams) SetHTTPClient(client *http.Client) {
	_ = "STUB: not implemented"
	return

	// WithEn adds the en to the echo service echo delete params
}

func (o *EchoServiceEchoDeleteParams) WithEn(en *string) *EchoServiceEchoDeleteParams {
	_ = "STUB: not implemented"
	return nil

	// SetEn adds the en to the echo service echo delete params
}

func (o *EchoServiceEchoDeleteParams) SetEn(en *string) {
	_ = "STUB: not implemented"

	// WithID adds the id to the echo service echo delete params
	return
}

func (o *EchoServiceEchoDeleteParams) WithID(id *string) *EchoServiceEchoDeleteParams {
	_ = "STUB: not implemented"
	return nil

	// SetID adds the id to the echo service echo delete params
}

func (o *EchoServiceEchoDeleteParams) SetID(id *string) {
	_ = "STUB: not implemented"

	// WithLang adds the lang to the echo service echo delete params
	return
}

func (o *EchoServiceEchoDeleteParams) WithLang(lang *string) *EchoServiceEchoDeleteParams {
	_ = "STUB: not implemented"
	return nil

	// SetLang adds the lang to the echo service echo delete params
}

func (o *EchoServiceEchoDeleteParams) SetLang(lang *string) {
	_ = "STUB: not implemented"

	// WithLineNum adds the lineNum to the echo service echo delete params
	return
}

func (o *EchoServiceEchoDeleteParams) WithLineNum(lineNum *string) *EchoServiceEchoDeleteParams {
	_ = "STUB: not implemented"
	return nil
}

// SetLineNum adds the lineNum to the echo service echo delete params
func (o *EchoServiceEchoDeleteParams) SetLineNum(lineNum *string) {
	_ = "STUB: not implemented"
	return

	// WithNIDnID adds the nIDnID to the echo service echo delete params
}

func (o *EchoServiceEchoDeleteParams) WithNIDnID(nIDnID *string) *EchoServiceEchoDeleteParams {
	_ = "STUB: not implemented"
	return nil
}

// SetNIDnID adds the nIdNId to the echo service echo delete params
func (o *EchoServiceEchoDeleteParams) SetNIDnID(nIDnID *string) {
	_ = "STUB: not implemented"

	// WithNIDVal adds the nIDVal to the echo service echo delete params
	return
}

func (o *EchoServiceEchoDeleteParams) WithNIDVal(nIDVal *string) *EchoServiceEchoDeleteParams {
	_ = "STUB: not implemented"
	return nil
}

// SetNIDVal adds the nIdVal to the echo service echo delete params
func (o *EchoServiceEchoDeleteParams) SetNIDVal(nIDVal *string) {
	_ = "STUB: not implemented"

	// WithNoNote adds the noNote to the echo service echo delete params
	return
}

func (o *EchoServiceEchoDeleteParams) WithNoNote(noNote *string) *EchoServiceEchoDeleteParams {
	_ = "STUB: not implemented"
	return nil
}

// SetNoNote adds the noNote to the echo service echo delete params
func (o *EchoServiceEchoDeleteParams) SetNoNote(noNote *string) {
	_ = "STUB: not implemented"

	// WithNoProgress adds the noProgress to the echo service echo delete params
	return
}

func (o *EchoServiceEchoDeleteParams) WithNoProgress(noProgress *string) *EchoServiceEchoDeleteParams {
	_ = "STUB: not implemented"
	return nil
}

// SetNoProgress adds the noProgress to the echo service echo delete params
func (o *EchoServiceEchoDeleteParams) SetNoProgress(noProgress *string) {
	_ = "STUB: not implemented"
	return
}

// WithNum adds the num to the echo service echo delete params
func (o *EchoServiceEchoDeleteParams) WithNum(num *string) *EchoServiceEchoDeleteParams {
	_ = "STUB: not implemented"
	return nil

	// SetNum adds the num to the echo service echo delete params
}

func (o *EchoServiceEchoDeleteParams) SetNum(num *string) {
	_ = "STUB: not implemented"

	// WithResourceID adds the resourceID to the echo service echo delete params
	return
}

func (o *EchoServiceEchoDeleteParams) WithResourceID(resourceID *string) *EchoServiceEchoDeleteParams {
	_ = "STUB: not implemented"
	return nil
}

// SetResourceID adds the resourceId to the echo service echo delete params
func (o *EchoServiceEchoDeleteParams) SetResourceID(resourceID *string) {
	_ = "STUB: not implemented"
	return
}

// WithStatusNote adds the statusNote to the echo service echo delete params
func (o *EchoServiceEchoDeleteParams) WithStatusNote(statusNote *string) *EchoServiceEchoDeleteParams {
	_ = "STUB: not implemented"
	return nil
}

// SetStatusNote adds the statusNote to the echo service echo delete params
func (o *EchoServiceEchoDeleteParams) SetStatusNote(statusNote *string) {
	_ = "STUB: not implemented"
	return
}

// WithStatusProgress adds the statusProgress to the echo service echo delete params
func (o *EchoServiceEchoDeleteParams) WithStatusProgress(statusProgress *string) *EchoServiceEchoDeleteParams {
	_ = "STUB: not implemented"
	return nil
}

// SetStatusProgress adds the statusProgress to the echo service echo delete params
func (o *EchoServiceEchoDeleteParams) SetStatusProgress(statusProgress *string) {
	_ = "STUB: not implemented"
	return
}

// WriteToRequest writes these params to a swagger request
func (o *EchoServiceEchoDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// query param en

// query param id

// query param lang

// query param lineNum

// query param nId.nId

// query param nId.val

// query param no.note

// query param no.progress

// query param num

// query param resourceId

// query param status.note

// query param status.progress
