// Code generated by go-swagger; DO NOT EDIT.

package echo_service

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// NewEchoServiceEcho5Params creates a new EchoServiceEcho5Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewEchoServiceEcho5Params() *EchoServiceEcho5Params { _ = "STUB: not implemented"; return nil }

// NewEchoServiceEcho5ParamsWithTimeout creates a new EchoServiceEcho5Params object
// with the ability to set a timeout on a request.
func NewEchoServiceEcho5ParamsWithTimeout(timeout time.Duration) *EchoServiceEcho5Params {
	_ = "STUB: not implemented"
	return nil
}

// NewEchoServiceEcho5ParamsWithContext creates a new EchoServiceEcho5Params object
// with the ability to set a context for a request.
func NewEchoServiceEcho5ParamsWithContext(ctx context.Context) *EchoServiceEcho5Params {
	_ = "STUB: not implemented"
	return nil
}

// NewEchoServiceEcho5ParamsWithHTTPClient creates a new EchoServiceEcho5Params object
// with the ability to set a custom HTTPClient for a request.
func NewEchoServiceEcho5ParamsWithHTTPClient(client *http.Client) *EchoServiceEcho5Params {
	_ = "STUB: not implemented"
	return nil
}

/*
EchoServiceEcho5Params contains all the parameters to send to the API endpoint

	for the echo service echo5 operation.

	Typically these are written to a http.Request.
*/
type EchoServiceEcho5Params struct {

	// En.
	//
	// Format: int64
	En *string

	/* ID.

	   Id represents the message identifier.
	*/
	ID *string

	// Lang.
	Lang *string

	// LineNum.
	//
	// Format: int64
	LineNum *string

	// NIDnID.
	NIDnID *string

	// NIDVal.
	NIDVal *string

	// NoNote.
	NoNote string

	// NoProgress.
	//
	// Format: int64
	NoProgress *string

	// Num.
	//
	// Format: int64
	Num *string

	// ResourceID.
	ResourceID *string

	// StatusProgress.
	//
	// Format: int64
	StatusProgress *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the echo service echo5 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EchoServiceEcho5Params) WithDefaults() *EchoServiceEcho5Params {
	_ = "STUB: not implemented"
	return nil

	// SetDefaults hydrates default values in the echo service echo5 params (not the query body).
	//
	// All values with no default are reset to their zero value.
}

func (o *EchoServiceEcho5Params) SetDefaults() {
	_ = "STUB: not implemented"
	// no default values defined for this parameter
	return
}

// WithTimeout adds the timeout to the echo service echo5 params
func (o *EchoServiceEcho5Params) WithTimeout(timeout time.Duration) *EchoServiceEcho5Params {
	_ = "STUB: not implemented"
	return nil
}

// SetTimeout adds the timeout to the echo service echo5 params
func (o *EchoServiceEcho5Params) SetTimeout(timeout time.Duration) {
	_ = "STUB: not implemented"
	return

	// WithContext adds the context to the echo service echo5 params
}

func (o *EchoServiceEcho5Params) WithContext(ctx context.Context) *EchoServiceEcho5Params {
	_ = "STUB: not implemented"
	return nil
}

// SetContext adds the context to the echo service echo5 params
func (o *EchoServiceEcho5Params) SetContext(ctx context.Context) {
	_ = "STUB: not implemented"

	// WithHTTPClient adds the HTTPClient to the echo service echo5 params
	return
}

func (o *EchoServiceEcho5Params) WithHTTPClient(client *http.Client) *EchoServiceEcho5Params {
	_ = "STUB: not implemented"
	return nil
}

// SetHTTPClient adds the HTTPClient to the echo service echo5 params
func (o *EchoServiceEcho5Params) SetHTTPClient(client *http.Client) {
	_ = "STUB: not implemented"
	return

	// WithEn adds the en to the echo service echo5 params
}

func (o *EchoServiceEcho5Params) WithEn(en *string) *EchoServiceEcho5Params {
	_ = "STUB: not implemented"
	return nil

	// SetEn adds the en to the echo service echo5 params
}

func (o *EchoServiceEcho5Params) SetEn(en *string) {
	_ = "STUB: not implemented"

	// WithID adds the id to the echo service echo5 params
	return
}

func (o *EchoServiceEcho5Params) WithID(id *string) *EchoServiceEcho5Params {
	_ = "STUB: not implemented"
	return nil

	// SetID adds the id to the echo service echo5 params
}

func (o *EchoServiceEcho5Params) SetID(id *string) {
	_ = "STUB: not implemented"

	// WithLang adds the lang to the echo service echo5 params
	return
}

func (o *EchoServiceEcho5Params) WithLang(lang *string) *EchoServiceEcho5Params {
	_ = "STUB: not implemented"
	return nil

	// SetLang adds the lang to the echo service echo5 params
}

func (o *EchoServiceEcho5Params) SetLang(lang *string) {
	_ = "STUB: not implemented"

	// WithLineNum adds the lineNum to the echo service echo5 params
	return
}

func (o *EchoServiceEcho5Params) WithLineNum(lineNum *string) *EchoServiceEcho5Params {
	_ = "STUB: not implemented"
	return nil
}

// SetLineNum adds the lineNum to the echo service echo5 params
func (o *EchoServiceEcho5Params) SetLineNum(lineNum *string) { _ = "STUB: not implemented"; return }

// WithNIDnID adds the nIDnID to the echo service echo5 params
func (o *EchoServiceEcho5Params) WithNIDnID(nIDnID *string) *EchoServiceEcho5Params {
	_ = "STUB: not implemented"
	return nil
}

// SetNIDnID adds the nIdNId to the echo service echo5 params
func (o *EchoServiceEcho5Params) SetNIDnID(nIDnID *string) {
	_ = "STUB: not implemented"

	// WithNIDVal adds the nIDVal to the echo service echo5 params
	return
}

func (o *EchoServiceEcho5Params) WithNIDVal(nIDVal *string) *EchoServiceEcho5Params {
	_ = "STUB: not implemented"
	return nil
}

// SetNIDVal adds the nIdVal to the echo service echo5 params
func (o *EchoServiceEcho5Params) SetNIDVal(nIDVal *string) {
	_ = "STUB: not implemented"

	// WithNoNote adds the noNote to the echo service echo5 params
	return
}

func (o *EchoServiceEcho5Params) WithNoNote(noNote string) *EchoServiceEcho5Params {
	_ = "STUB: not implemented"
	return nil
}

// SetNoNote adds the noNote to the echo service echo5 params
func (o *EchoServiceEcho5Params) SetNoNote(noNote string) {
	_ = "STUB: not implemented"

	// WithNoProgress adds the noProgress to the echo service echo5 params
	return
}

func (o *EchoServiceEcho5Params) WithNoProgress(noProgress *string) *EchoServiceEcho5Params {
	_ = "STUB: not implemented"
	return nil
}

// SetNoProgress adds the noProgress to the echo service echo5 params
func (o *EchoServiceEcho5Params) SetNoProgress(noProgress *string) {
	_ = "STUB: not implemented"
	return
}

// WithNum adds the num to the echo service echo5 params
func (o *EchoServiceEcho5Params) WithNum(num *string) *EchoServiceEcho5Params {
	_ = "STUB: not implemented"
	return nil

	// SetNum adds the num to the echo service echo5 params
}

func (o *EchoServiceEcho5Params) SetNum(num *string) {
	_ = "STUB: not implemented"

	// WithResourceID adds the resourceID to the echo service echo5 params
	return
}

func (o *EchoServiceEcho5Params) WithResourceID(resourceID *string) *EchoServiceEcho5Params {
	_ = "STUB: not implemented"
	return nil
}

// SetResourceID adds the resourceId to the echo service echo5 params
func (o *EchoServiceEcho5Params) SetResourceID(resourceID *string) {
	_ = "STUB: not implemented"
	return
}

// WithStatusProgress adds the statusProgress to the echo service echo5 params
func (o *EchoServiceEcho5Params) WithStatusProgress(statusProgress *string) *EchoServiceEcho5Params {
	_ = "STUB: not implemented"
	return nil
}

// SetStatusProgress adds the statusProgress to the echo service echo5 params
func (o *EchoServiceEcho5Params) SetStatusProgress(statusProgress *string) {
	_ = "STUB: not implemented"
	return
}

// WriteToRequest writes these params to a swagger request
func (o *EchoServiceEcho5Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// query param en

// query param id

// query param lang

// query param lineNum

// query param nId.nId

// query param nId.val

// path param no.note

// query param no.progress

// query param num

// query param resourceId

// query param status.progress
