// Code generated by go-swagger; DO NOT EDIT.

package echo_service

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/grpc-ecosystem/grpc-gateway/v2/examples/internal/clients/echo/models"
)

// NewEchoServiceEchoBody2Params creates a new EchoServiceEchoBody2Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewEchoServiceEchoBody2Params() *EchoServiceEchoBody2Params {
	_ = "STUB: not implemented"
	return nil
}

// NewEchoServiceEchoBody2ParamsWithTimeout creates a new EchoServiceEchoBody2Params object
// with the ability to set a timeout on a request.
func NewEchoServiceEchoBody2ParamsWithTimeout(timeout time.Duration) *EchoServiceEchoBody2Params {
	_ = "STUB: not implemented"
	return nil
}

// NewEchoServiceEchoBody2ParamsWithContext creates a new EchoServiceEchoBody2Params object
// with the ability to set a context for a request.
func NewEchoServiceEchoBody2ParamsWithContext(ctx context.Context) *EchoServiceEchoBody2Params {
	_ = "STUB: not implemented"
	return nil
}

// NewEchoServiceEchoBody2ParamsWithHTTPClient creates a new EchoServiceEchoBody2Params object
// with the ability to set a custom HTTPClient for a request.
func NewEchoServiceEchoBody2ParamsWithHTTPClient(client *http.Client) *EchoServiceEchoBody2Params {
	_ = "STUB: not implemented"
	return nil
}

/*
EchoServiceEchoBody2Params contains all the parameters to send to the API endpoint

	for the echo service echo body2 operation.

	Typically these are written to a http.Request.
*/
type EchoServiceEchoBody2Params struct {

	/* ID.

	   Id represents the message identifier.
	*/
	ID string

	// Lang.
	Lang *string

	// LineNum.
	//
	// Format: int64
	LineNum *string

	// NIDnID.
	NIDnID *string

	// NIDVal.
	NIDVal *string

	// No.
	No *models.ExamplepbEmbedded

	// Num.
	//
	// Format: int64
	Num *string

	// ResourceID.
	ResourceID *string

	// StatusNote.
	StatusNote *string

	// StatusProgress.
	//
	// Format: int64
	StatusProgress *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the echo service echo body2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EchoServiceEchoBody2Params) WithDefaults() *EchoServiceEchoBody2Params {
	_ = "STUB: not implemented"
	return nil

	// SetDefaults hydrates default values in the echo service echo body2 params (not the query body).
	//
	// All values with no default are reset to their zero value.
}

func (o *EchoServiceEchoBody2Params) SetDefaults() {
	_ = "STUB: not implemented"
	// no default values defined for this parameter
	return
}

// WithTimeout adds the timeout to the echo service echo body2 params
func (o *EchoServiceEchoBody2Params) WithTimeout(timeout time.Duration) *EchoServiceEchoBody2Params {
	_ = "STUB: not implemented"
	return nil
}

// SetTimeout adds the timeout to the echo service echo body2 params
func (o *EchoServiceEchoBody2Params) SetTimeout(timeout time.Duration) {
	_ = "STUB: not implemented"
	return

	// WithContext adds the context to the echo service echo body2 params
}

func (o *EchoServiceEchoBody2Params) WithContext(ctx context.Context) *EchoServiceEchoBody2Params {
	_ = "STUB: not implemented"
	return nil
}

// SetContext adds the context to the echo service echo body2 params
func (o *EchoServiceEchoBody2Params) SetContext(ctx context.Context) {
	_ = "STUB: not implemented"

	// WithHTTPClient adds the HTTPClient to the echo service echo body2 params
	return
}

func (o *EchoServiceEchoBody2Params) WithHTTPClient(client *http.Client) *EchoServiceEchoBody2Params {
	_ = "STUB: not implemented"
	return nil
}

// SetHTTPClient adds the HTTPClient to the echo service echo body2 params
func (o *EchoServiceEchoBody2Params) SetHTTPClient(client *http.Client) {
	_ = "STUB: not implemented"
	return

	// WithID adds the id to the echo service echo body2 params
}

func (o *EchoServiceEchoBody2Params) WithID(id string) *EchoServiceEchoBody2Params {
	_ = "STUB: not implemented"
	return nil

	// SetID adds the id to the echo service echo body2 params
}

func (o *EchoServiceEchoBody2Params) SetID(id string) {
	_ = "STUB: not implemented"

	// WithLang adds the lang to the echo service echo body2 params
	return
}

func (o *EchoServiceEchoBody2Params) WithLang(lang *string) *EchoServiceEchoBody2Params {
	_ = "STUB: not implemented"
	return nil

	// SetLang adds the lang to the echo service echo body2 params
}

func (o *EchoServiceEchoBody2Params) SetLang(lang *string) {
	_ = "STUB: not implemented"

	// WithLineNum adds the lineNum to the echo service echo body2 params
	return
}

func (o *EchoServiceEchoBody2Params) WithLineNum(lineNum *string) *EchoServiceEchoBody2Params {
	_ = "STUB: not implemented"
	return nil
}

// SetLineNum adds the lineNum to the echo service echo body2 params
func (o *EchoServiceEchoBody2Params) SetLineNum(lineNum *string) { _ = "STUB: not implemented"; return }

// WithNIDnID adds the nIDnID to the echo service echo body2 params
func (o *EchoServiceEchoBody2Params) WithNIDnID(nIDnID *string) *EchoServiceEchoBody2Params {
	_ = "STUB: not implemented"
	return nil
}

// SetNIDnID adds the nIdNId to the echo service echo body2 params
func (o *EchoServiceEchoBody2Params) SetNIDnID(nIDnID *string) {
	_ = "STUB: not implemented"

	// WithNIDVal adds the nIDVal to the echo service echo body2 params
	return
}

func (o *EchoServiceEchoBody2Params) WithNIDVal(nIDVal *string) *EchoServiceEchoBody2Params {
	_ = "STUB: not implemented"
	return nil
}

// SetNIDVal adds the nIdVal to the echo service echo body2 params
func (o *EchoServiceEchoBody2Params) SetNIDVal(nIDVal *string) {
	_ = "STUB: not implemented"

	// WithNo adds the no to the echo service echo body2 params
	return
}

func (o *EchoServiceEchoBody2Params) WithNo(no *models.ExamplepbEmbedded) *EchoServiceEchoBody2Params {
	_ = "STUB: not implemented"
	return nil

	// SetNo adds the no to the echo service echo body2 params
}

func (o *EchoServiceEchoBody2Params) SetNo(no *models.ExamplepbEmbedded) {
	_ = "STUB: not implemented"

	// WithNum adds the num to the echo service echo body2 params
	return
}

func (o *EchoServiceEchoBody2Params) WithNum(num *string) *EchoServiceEchoBody2Params {
	_ = "STUB: not implemented"
	return nil

	// SetNum adds the num to the echo service echo body2 params
}

func (o *EchoServiceEchoBody2Params) SetNum(num *string) {
	_ = "STUB: not implemented"

	// WithResourceID adds the resourceID to the echo service echo body2 params
	return
}

func (o *EchoServiceEchoBody2Params) WithResourceID(resourceID *string) *EchoServiceEchoBody2Params {
	_ = "STUB: not implemented"
	return nil
}

// SetResourceID adds the resourceId to the echo service echo body2 params
func (o *EchoServiceEchoBody2Params) SetResourceID(resourceID *string) {
	_ = "STUB: not implemented"
	return
}

// WithStatusNote adds the statusNote to the echo service echo body2 params
func (o *EchoServiceEchoBody2Params) WithStatusNote(statusNote *string) *EchoServiceEchoBody2Params {
	_ = "STUB: not implemented"
	return nil
}

// SetStatusNote adds the statusNote to the echo service echo body2 params
func (o *EchoServiceEchoBody2Params) SetStatusNote(statusNote *string) {
	_ = "STUB: not implemented"
	return
}

// WithStatusProgress adds the statusProgress to the echo service echo body2 params
func (o *EchoServiceEchoBody2Params) WithStatusProgress(statusProgress *string) *EchoServiceEchoBody2Params {
	_ = "STUB: not implemented"
	return nil
}

// SetStatusProgress adds the statusProgress to the echo service echo body2 params
func (o *EchoServiceEchoBody2Params) SetStatusProgress(statusProgress *string) {
	_ = "STUB: not implemented"
	return
}

// WriteToRequest writes these params to a swagger request
func (o *EchoServiceEchoBody2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// path param id

// query param lang

// query param lineNum

// query param nId.nId

// query param nId.val

// query param num

// query param resourceId

// query param status.note

// query param status.progress
