// Code generated by go-swagger; DO NOT EDIT.

package echo_service

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/grpc-ecosystem/grpc-gateway/v2/examples/internal/clients/echo/models"
)

// EchoServiceEcho3Reader is a Reader for the EchoServiceEcho3 structure.
type EchoServiceEcho3Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EchoServiceEcho3Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

// NewEchoServiceEcho3OK creates a EchoServiceEcho3OK with default headers values
func NewEchoServiceEcho3OK() *EchoServiceEcho3OK { _ = "STUB: not implemented"; return nil }

/*
EchoServiceEcho3OK describes a response with status code 200, with default header values.

A successful response.
*/
type EchoServiceEcho3OK struct {
	Payload *models.ExamplepbSimpleMessage
}

// IsSuccess returns true when this echo service echo3 o k response has a 2xx status code
func (o *EchoServiceEcho3OK) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this echo service echo3 o k response has a 3xx status code
	return false
}

func (o *EchoServiceEcho3OK) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this echo service echo3 o k response has a 4xx status code
	return false
}

func (o *EchoServiceEcho3OK) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this echo service echo3 o k response has a 5xx status code
	return false
}

func (o *EchoServiceEcho3OK) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this echo service echo3 o k response a status code equal to that given
	return false
}

func (o *EchoServiceEcho3OK) IsCode(code int) bool {
	_ = "STUB: not implemented"

	// Code gets the status code for the echo service echo3 o k response
	return false
}

func (o *EchoServiceEcho3OK) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *EchoServiceEcho3OK) Error() string { _ = "STUB: not implemented"; return "" }

func (o *EchoServiceEcho3OK) String() string { _ = "STUB: not implemented"; return "" }

func (o *EchoServiceEcho3OK) GetPayload() *models.ExamplepbSimpleMessage {
	_ = "STUB: not implemented"
	return nil
}

func (o *EchoServiceEcho3OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// response payload

// NewEchoServiceEcho3Default creates a EchoServiceEcho3Default with default headers values
func NewEchoServiceEcho3Default(code int) *EchoServiceEcho3Default {
	_ = "STUB: not implemented"
	return nil
}

/*
EchoServiceEcho3Default describes a response with status code -1, with default header values.

An unexpected error response.
*/
type EchoServiceEcho3Default struct {
	_statusCode int

	Payload *models.GoogleRPCStatus
}

// IsSuccess returns true when this echo service echo3 default response has a 2xx status code
func (o *EchoServiceEcho3Default) IsSuccess() bool { _ = "STUB: not implemented"; return false }

// IsRedirect returns true when this echo service echo3 default response has a 3xx status code
func (o *EchoServiceEcho3Default) IsRedirect() bool { _ = "STUB: not implemented"; return false }

// IsClientError returns true when this echo service echo3 default response has a 4xx status code
func (o *EchoServiceEcho3Default) IsClientError() bool { _ = "STUB: not implemented"; return false }

// IsServerError returns true when this echo service echo3 default response has a 5xx status code
func (o *EchoServiceEcho3Default) IsServerError() bool { _ = "STUB: not implemented"; return false }

// IsCode returns true when this echo service echo3 default response a status code equal to that given
func (o *EchoServiceEcho3Default) IsCode(code int) bool { _ = "STUB: not implemented"; return false }

// Code gets the status code for the echo service echo3 default response
func (o *EchoServiceEcho3Default) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *EchoServiceEcho3Default) Error() string { _ = "STUB: not implemented"; return "" }

func (o *EchoServiceEcho3Default) String() string { _ = "STUB: not implemented"; return "" }

func (o *EchoServiceEcho3Default) GetPayload() *models.GoogleRPCStatus {
	_ = "STUB: not implemented"
	return nil
}

func (o *EchoServiceEcho3Default) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// response payload
