// Package helloworldv3 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package helloworldv3

import (
	"context"
	"net/http"
)

// GoogleRpcStatus The Status type defines a logical error model suitable for different programming environments.
type GoogleRpcStatus struct {
	// Code The status code, which should be an enum value of google.rpc.Code.
	Code *int32 `json:"code,omitempty"`

	// Details A list of messages that carry the error details.
	Details *[]GoogleRpcStatus_Details_Item `json:"details,omitempty"`

	// Message A developer-facing error message.
	Message *string `json:"message,omitempty"`
}

// GoogleRpcStatus_Details_Item defines model for google.rpc.Status.details.Item.
type GoogleRpcStatus_Details_Item struct {
	Type                 *string                `json:"@type,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// GrpcGatewayExamplesInternalHelloworldHelloReply defines model for grpc.gateway.examples.internal.helloworld.HelloReply.
type GrpcGatewayExamplesInternalHelloworldHelloReply struct {
	Message *string `json:"message,omitempty"`
}

// GreeterSayHello4Params defines parameters for GreeterSayHello4.
type GreeterSayHello4Params struct {
	Name      *string  `form:"name,omitempty" json:"name,omitempty"`
	StrVal    *string  `form:"strVal,omitempty" json:"strVal,omitempty"`
	FloatVal  *float32 `form:"floatVal,omitempty" json:"floatVal,omitempty"`
	DoubleVal *float64 `form:"doubleVal,omitempty" json:"doubleVal,omitempty"`
	BytesVal  *[]byte  `form:"bytesVal,omitempty" json:"bytesVal,omitempty"`
	Int32Val  *int32   `form:"int32Val,omitempty" json:"int32Val,omitempty"`
	Uint32Val *int64   `form:"uint32Val,omitempty" json:"uint32Val,omitempty"`
	Int64Val  *string  `form:"int64Val,omitempty" json:"int64Val,omitempty"`
	Uint64Val *string  `form:"uint64Val,omitempty" json:"uint64Val,omitempty"`
}

// GreeterSayHello5Params defines parameters for GreeterSayHello5.
type GreeterSayHello5Params struct {
	Name      *string  `form:"name,omitempty" json:"name,omitempty"`
	StrVal    *string  `form:"strVal,omitempty" json:"strVal,omitempty"`
	FloatVal  *float32 `form:"floatVal,omitempty" json:"floatVal,omitempty"`
	DoubleVal *float64 `form:"doubleVal,omitempty" json:"doubleVal,omitempty"`
	BoolVal   *bool    `form:"boolVal,omitempty" json:"boolVal,omitempty"`
	Int32Val  *int32   `form:"int32Val,omitempty" json:"int32Val,omitempty"`
	Uint32Val *int64   `form:"uint32Val,omitempty" json:"uint32Val,omitempty"`
	Int64Val  *string  `form:"int64Val,omitempty" json:"int64Val,omitempty"`
	Uint64Val *string  `form:"uint64Val,omitempty" json:"uint64Val,omitempty"`
}

// GreeterSayHello3Params defines parameters for GreeterSayHello3.
type GreeterSayHello3Params struct {
	Name      *string  `form:"name,omitempty" json:"name,omitempty"`
	StrVal    *string  `form:"strVal,omitempty" json:"strVal,omitempty"`
	FloatVal  *float32 `form:"floatVal,omitempty" json:"floatVal,omitempty"`
	BoolVal   *bool    `form:"boolVal,omitempty" json:"boolVal,omitempty"`
	BytesVal  *[]byte  `form:"bytesVal,omitempty" json:"bytesVal,omitempty"`
	Int32Val  *int32   `form:"int32Val,omitempty" json:"int32Val,omitempty"`
	Uint32Val *int64   `form:"uint32Val,omitempty" json:"uint32Val,omitempty"`
	Int64Val  *string  `form:"int64Val,omitempty" json:"int64Val,omitempty"`
	Uint64Val *string  `form:"uint64Val,omitempty" json:"uint64Val,omitempty"`
}

// GreeterSayHello2Params defines parameters for GreeterSayHello2.
type GreeterSayHello2Params struct {
	Name      *string  `form:"name,omitempty" json:"name,omitempty"`
	StrVal    *string  `form:"strVal,omitempty" json:"strVal,omitempty"`
	DoubleVal *float64 `form:"doubleVal,omitempty" json:"doubleVal,omitempty"`
	BoolVal   *bool    `form:"boolVal,omitempty" json:"boolVal,omitempty"`
	BytesVal  *[]byte  `form:"bytesVal,omitempty" json:"bytesVal,omitempty"`
	Int32Val  *int32   `form:"int32Val,omitempty" json:"int32Val,omitempty"`
	Uint32Val *int64   `form:"uint32Val,omitempty" json:"uint32Val,omitempty"`
	Int64Val  *string  `form:"int64Val,omitempty" json:"int64Val,omitempty"`
	Uint64Val *string  `form:"uint64Val,omitempty" json:"uint64Val,omitempty"`
}

// GreeterSayHello6Params defines parameters for GreeterSayHello6.
type GreeterSayHello6Params struct {
	Name      *string  `form:"name,omitempty" json:"name,omitempty"`
	StrVal    *string  `form:"strVal,omitempty" json:"strVal,omitempty"`
	FloatVal  *float32 `form:"floatVal,omitempty" json:"floatVal,omitempty"`
	DoubleVal *float64 `form:"doubleVal,omitempty" json:"doubleVal,omitempty"`
	BoolVal   *bool    `form:"boolVal,omitempty" json:"boolVal,omitempty"`
	BytesVal  *[]byte  `form:"bytesVal,omitempty" json:"bytesVal,omitempty"`
	Uint32Val *int64   `form:"uint32Val,omitempty" json:"uint32Val,omitempty"`
	Int64Val  *string  `form:"int64Val,omitempty" json:"int64Val,omitempty"`
	Uint64Val *string  `form:"uint64Val,omitempty" json:"uint64Val,omitempty"`
}

// GreeterSayHello8Params defines parameters for GreeterSayHello8.
type GreeterSayHello8Params struct {
	Name      *string  `form:"name,omitempty" json:"name,omitempty"`
	StrVal    *string  `form:"strVal,omitempty" json:"strVal,omitempty"`
	FloatVal  *float32 `form:"floatVal,omitempty" json:"floatVal,omitempty"`
	DoubleVal *float64 `form:"doubleVal,omitempty" json:"doubleVal,omitempty"`
	BoolVal   *bool    `form:"boolVal,omitempty" json:"boolVal,omitempty"`
	BytesVal  *[]byte  `form:"bytesVal,omitempty" json:"bytesVal,omitempty"`
	Int32Val  *int32   `form:"int32Val,omitempty" json:"int32Val,omitempty"`
	Uint32Val *int64   `form:"uint32Val,omitempty" json:"uint32Val,omitempty"`
	Uint64Val *string  `form:"uint64Val,omitempty" json:"uint64Val,omitempty"`
}

// GreeterSayHello1Params defines parameters for GreeterSayHello1.
type GreeterSayHello1Params struct {
	Name      *string  `form:"name,omitempty" json:"name,omitempty"`
	FloatVal  *float32 `form:"floatVal,omitempty" json:"floatVal,omitempty"`
	DoubleVal *float64 `form:"doubleVal,omitempty" json:"doubleVal,omitempty"`
	BoolVal   *bool    `form:"boolVal,omitempty" json:"boolVal,omitempty"`
	BytesVal  *[]byte  `form:"bytesVal,omitempty" json:"bytesVal,omitempty"`
	Int32Val  *int32   `form:"int32Val,omitempty" json:"int32Val,omitempty"`
	Uint32Val *int64   `form:"uint32Val,omitempty" json:"uint32Val,omitempty"`
	Int64Val  *string  `form:"int64Val,omitempty" json:"int64Val,omitempty"`
	Uint64Val *string  `form:"uint64Val,omitempty" json:"uint64Val,omitempty"`
}

// GreeterSayHello7Params defines parameters for GreeterSayHello7.
type GreeterSayHello7Params struct {
	Name      *string  `form:"name,omitempty" json:"name,omitempty"`
	StrVal    *string  `form:"strVal,omitempty" json:"strVal,omitempty"`
	FloatVal  *float32 `form:"floatVal,omitempty" json:"floatVal,omitempty"`
	DoubleVal *float64 `form:"doubleVal,omitempty" json:"doubleVal,omitempty"`
	BoolVal   *bool    `form:"boolVal,omitempty" json:"boolVal,omitempty"`
	BytesVal  *[]byte  `form:"bytesVal,omitempty" json:"bytesVal,omitempty"`
	Int32Val  *int32   `form:"int32Val,omitempty" json:"int32Val,omitempty"`
	Int64Val  *string  `form:"int64Val,omitempty" json:"int64Val,omitempty"`
	Uint64Val *string  `form:"uint64Val,omitempty" json:"uint64Val,omitempty"`
}

// GreeterSayHello9Params defines parameters for GreeterSayHello9.
type GreeterSayHello9Params struct {
	Name      *string  `form:"name,omitempty" json:"name,omitempty"`
	StrVal    *string  `form:"strVal,omitempty" json:"strVal,omitempty"`
	FloatVal  *float32 `form:"floatVal,omitempty" json:"floatVal,omitempty"`
	DoubleVal *float64 `form:"doubleVal,omitempty" json:"doubleVal,omitempty"`
	BoolVal   *bool    `form:"boolVal,omitempty" json:"boolVal,omitempty"`
	BytesVal  *[]byte  `form:"bytesVal,omitempty" json:"bytesVal,omitempty"`
	Int32Val  *int32   `form:"int32Val,omitempty" json:"int32Val,omitempty"`
	Uint32Val *int64   `form:"uint32Val,omitempty" json:"uint32Val,omitempty"`
	Int64Val  *string  `form:"int64Val,omitempty" json:"int64Val,omitempty"`
}

// GreeterSayHelloParams defines parameters for GreeterSayHello.
type GreeterSayHelloParams struct {
	StrVal    *string  `form:"strVal,omitempty" json:"strVal,omitempty"`
	FloatVal  *float32 `form:"floatVal,omitempty" json:"floatVal,omitempty"`
	DoubleVal *float64 `form:"doubleVal,omitempty" json:"doubleVal,omitempty"`
	BoolVal   *bool    `form:"boolVal,omitempty" json:"boolVal,omitempty"`
	BytesVal  *[]byte  `form:"bytesVal,omitempty" json:"bytesVal,omitempty"`
	Int32Val  *int32   `form:"int32Val,omitempty" json:"int32Val,omitempty"`
	Uint32Val *int64   `form:"uint32Val,omitempty" json:"uint32Val,omitempty"`
	Int64Val  *string  `form:"int64Val,omitempty" json:"int64Val,omitempty"`
	Uint64Val *string  `form:"uint64Val,omitempty" json:"uint64Val,omitempty"`
}

// Getter for additional properties for GoogleRpcStatus_Details_Item. Returns the specified
// element and whether it was found
func (a GoogleRpcStatus_Details_Item) Get(fieldName string) (value interface{}, found bool) {
	_ = "STUB: not implemented"
	return nil, false
}

// Setter for additional properties for GoogleRpcStatus_Details_Item
func (a *GoogleRpcStatus_Details_Item) Set(fieldName string, value interface{}) {
	_ = "STUB: not implemented"
	return
}

// Override default JSON handling for GoogleRpcStatus_Details_Item to handle AdditionalProperties
func (a *GoogleRpcStatus_Details_Item) UnmarshalJSON(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Override default JSON handling for GoogleRpcStatus_Details_Item to handle AdditionalProperties
func (a GoogleRpcStatus_Details_Item) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	_ = "STUB: not implemented"
	// create a client with sane default values
	return nil, nil
}

// mutate client and add all optional params

// ensure the server URL always has a trailing slash

// create httpClient, if not already present

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	_ = "STUB: not implemented"
	return *new(ClientOption)
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	_ = "STUB: not implemented"
	return *new(ClientOption)
}

// The interface specification for the client above.
type ClientInterface interface {
	// GreeterSayHello4 request
	GreeterSayHello4(ctx context.Context, boolVal bool, params *GreeterSayHello4Params, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GreeterSayHello5 request
	GreeterSayHello5(ctx context.Context, bytesVal []byte, params *GreeterSayHello5Params, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GreeterSayHello3 request
	GreeterSayHello3(ctx context.Context, doubleVal float64, params *GreeterSayHello3Params, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GreeterSayHello2 request
	GreeterSayHello2(ctx context.Context, floatVal float32, params *GreeterSayHello2Params, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GreeterSayHello6 request
	GreeterSayHello6(ctx context.Context, int32Val int32, params *GreeterSayHello6Params, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GreeterSayHello8 request
	GreeterSayHello8(ctx context.Context, int64Val string, params *GreeterSayHello8Params, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GreeterSayHello1 request
	GreeterSayHello1(ctx context.Context, strVal string, params *GreeterSayHello1Params, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GreeterSayHello7 request
	GreeterSayHello7(ctx context.Context, uint32Val int64, params *GreeterSayHello7Params, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GreeterSayHello9 request
	GreeterSayHello9(ctx context.Context, uint64Val string, params *GreeterSayHello9Params, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GreeterSayHello request
	GreeterSayHello(ctx context.Context, name string, params *GreeterSayHelloParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GreeterSayHello4(ctx context.Context, boolVal bool, params *GreeterSayHello4Params, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) GreeterSayHello5(ctx context.Context, bytesVal []byte, params *GreeterSayHello5Params, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) GreeterSayHello3(ctx context.Context, doubleVal float64, params *GreeterSayHello3Params, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) GreeterSayHello2(ctx context.Context, floatVal float32, params *GreeterSayHello2Params, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) GreeterSayHello6(ctx context.Context, int32Val int32, params *GreeterSayHello6Params, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) GreeterSayHello8(ctx context.Context, int64Val string, params *GreeterSayHello8Params, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) GreeterSayHello1(ctx context.Context, strVal string, params *GreeterSayHello1Params, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) GreeterSayHello7(ctx context.Context, uint32Val int64, params *GreeterSayHello7Params, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) GreeterSayHello9(ctx context.Context, uint64Val string, params *GreeterSayHello9Params, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) GreeterSayHello(ctx context.Context, name string, params *GreeterSayHelloParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewGreeterSayHello4Request generates requests for GreeterSayHello4
func NewGreeterSayHello4Request(server string, boolVal bool, params *GreeterSayHello4Params) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewGreeterSayHello5Request generates requests for GreeterSayHello5
func NewGreeterSayHello5Request(server string, bytesVal []byte, params *GreeterSayHello5Params) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewGreeterSayHello3Request generates requests for GreeterSayHello3
func NewGreeterSayHello3Request(server string, doubleVal float64, params *GreeterSayHello3Params) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewGreeterSayHello2Request generates requests for GreeterSayHello2
func NewGreeterSayHello2Request(server string, floatVal float32, params *GreeterSayHello2Params) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewGreeterSayHello6Request generates requests for GreeterSayHello6
func NewGreeterSayHello6Request(server string, int32Val int32, params *GreeterSayHello6Params) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewGreeterSayHello8Request generates requests for GreeterSayHello8
func NewGreeterSayHello8Request(server string, int64Val string, params *GreeterSayHello8Params) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewGreeterSayHello1Request generates requests for GreeterSayHello1
func NewGreeterSayHello1Request(server string, strVal string, params *GreeterSayHello1Params) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewGreeterSayHello7Request generates requests for GreeterSayHello7
func NewGreeterSayHello7Request(server string, uint32Val int64, params *GreeterSayHello7Params) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewGreeterSayHello9Request generates requests for GreeterSayHello9
func NewGreeterSayHello9Request(server string, uint64Val string, params *GreeterSayHello9Params) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewGreeterSayHelloRequest generates requests for GreeterSayHello
func NewGreeterSayHelloRequest(server string, name string, params *GreeterSayHelloParams) (*http.Request, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	_ = "STUB: not implemented"
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption { _ = "STUB: not implemented"; return *new(ClientOption) }

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GreeterSayHello4WithResponse request
	GreeterSayHello4WithResponse(ctx context.Context, boolVal bool, params *GreeterSayHello4Params, reqEditors ...RequestEditorFn) (*GreeterSayHello4Response, error)

	// GreeterSayHello5WithResponse request
	GreeterSayHello5WithResponse(ctx context.Context, bytesVal []byte, params *GreeterSayHello5Params, reqEditors ...RequestEditorFn) (*GreeterSayHello5Response, error)

	// GreeterSayHello3WithResponse request
	GreeterSayHello3WithResponse(ctx context.Context, doubleVal float64, params *GreeterSayHello3Params, reqEditors ...RequestEditorFn) (*GreeterSayHello3Response, error)

	// GreeterSayHello2WithResponse request
	GreeterSayHello2WithResponse(ctx context.Context, floatVal float32, params *GreeterSayHello2Params, reqEditors ...RequestEditorFn) (*GreeterSayHello2Response, error)

	// GreeterSayHello6WithResponse request
	GreeterSayHello6WithResponse(ctx context.Context, int32Val int32, params *GreeterSayHello6Params, reqEditors ...RequestEditorFn) (*GreeterSayHello6Response, error)

	// GreeterSayHello8WithResponse request
	GreeterSayHello8WithResponse(ctx context.Context, int64Val string, params *GreeterSayHello8Params, reqEditors ...RequestEditorFn) (*GreeterSayHello8Response, error)

	// GreeterSayHello1WithResponse request
	GreeterSayHello1WithResponse(ctx context.Context, strVal string, params *GreeterSayHello1Params, reqEditors ...RequestEditorFn) (*GreeterSayHello1Response, error)

	// GreeterSayHello7WithResponse request
	GreeterSayHello7WithResponse(ctx context.Context, uint32Val int64, params *GreeterSayHello7Params, reqEditors ...RequestEditorFn) (*GreeterSayHello7Response, error)

	// GreeterSayHello9WithResponse request
	GreeterSayHello9WithResponse(ctx context.Context, uint64Val string, params *GreeterSayHello9Params, reqEditors ...RequestEditorFn) (*GreeterSayHello9Response, error)

	// GreeterSayHelloWithResponse request
	GreeterSayHelloWithResponse(ctx context.Context, name string, params *GreeterSayHelloParams, reqEditors ...RequestEditorFn) (*GreeterSayHelloResponse, error)
}

type GreeterSayHello4Response struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GrpcGatewayExamplesInternalHelloworldHelloReply
	JSONDefault  *GoogleRpcStatus
}

// Status returns HTTPResponse.Status
func (r GreeterSayHello4Response) Status() string { _ = "STUB: not implemented"; return "" }

// StatusCode returns HTTPResponse.StatusCode
func (r GreeterSayHello4Response) StatusCode() int { _ = "STUB: not implemented"; return 0 }

type GreeterSayHello5Response struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GrpcGatewayExamplesInternalHelloworldHelloReply
	JSONDefault  *GoogleRpcStatus
}

// Status returns HTTPResponse.Status
func (r GreeterSayHello5Response) Status() string { _ = "STUB: not implemented"; return "" }

// StatusCode returns HTTPResponse.StatusCode
func (r GreeterSayHello5Response) StatusCode() int { _ = "STUB: not implemented"; return 0 }

type GreeterSayHello3Response struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GrpcGatewayExamplesInternalHelloworldHelloReply
	JSONDefault  *GoogleRpcStatus
}

// Status returns HTTPResponse.Status
func (r GreeterSayHello3Response) Status() string { _ = "STUB: not implemented"; return "" }

// StatusCode returns HTTPResponse.StatusCode
func (r GreeterSayHello3Response) StatusCode() int { _ = "STUB: not implemented"; return 0 }

type GreeterSayHello2Response struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GrpcGatewayExamplesInternalHelloworldHelloReply
	JSONDefault  *GoogleRpcStatus
}

// Status returns HTTPResponse.Status
func (r GreeterSayHello2Response) Status() string { _ = "STUB: not implemented"; return "" }

// StatusCode returns HTTPResponse.StatusCode
func (r GreeterSayHello2Response) StatusCode() int { _ = "STUB: not implemented"; return 0 }

type GreeterSayHello6Response struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GrpcGatewayExamplesInternalHelloworldHelloReply
	JSONDefault  *GoogleRpcStatus
}

// Status returns HTTPResponse.Status
func (r GreeterSayHello6Response) Status() string { _ = "STUB: not implemented"; return "" }

// StatusCode returns HTTPResponse.StatusCode
func (r GreeterSayHello6Response) StatusCode() int { _ = "STUB: not implemented"; return 0 }

type GreeterSayHello8Response struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GrpcGatewayExamplesInternalHelloworldHelloReply
	JSONDefault  *GoogleRpcStatus
}

// Status returns HTTPResponse.Status
func (r GreeterSayHello8Response) Status() string { _ = "STUB: not implemented"; return "" }

// StatusCode returns HTTPResponse.StatusCode
func (r GreeterSayHello8Response) StatusCode() int { _ = "STUB: not implemented"; return 0 }

type GreeterSayHello1Response struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GrpcGatewayExamplesInternalHelloworldHelloReply
	JSONDefault  *GoogleRpcStatus
}

// Status returns HTTPResponse.Status
func (r GreeterSayHello1Response) Status() string { _ = "STUB: not implemented"; return "" }

// StatusCode returns HTTPResponse.StatusCode
func (r GreeterSayHello1Response) StatusCode() int { _ = "STUB: not implemented"; return 0 }

type GreeterSayHello7Response struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GrpcGatewayExamplesInternalHelloworldHelloReply
	JSONDefault  *GoogleRpcStatus
}

// Status returns HTTPResponse.Status
func (r GreeterSayHello7Response) Status() string { _ = "STUB: not implemented"; return "" }

// StatusCode returns HTTPResponse.StatusCode
func (r GreeterSayHello7Response) StatusCode() int { _ = "STUB: not implemented"; return 0 }

type GreeterSayHello9Response struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GrpcGatewayExamplesInternalHelloworldHelloReply
	JSONDefault  *GoogleRpcStatus
}

// Status returns HTTPResponse.Status
func (r GreeterSayHello9Response) Status() string { _ = "STUB: not implemented"; return "" }

// StatusCode returns HTTPResponse.StatusCode
func (r GreeterSayHello9Response) StatusCode() int { _ = "STUB: not implemented"; return 0 }

type GreeterSayHelloResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GrpcGatewayExamplesInternalHelloworldHelloReply
	JSONDefault  *GoogleRpcStatus
}

// Status returns HTTPResponse.Status
func (r GreeterSayHelloResponse) Status() string { _ = "STUB: not implemented"; return "" }

// StatusCode returns HTTPResponse.StatusCode
func (r GreeterSayHelloResponse) StatusCode() int { _ = "STUB: not implemented"; return 0 }

// GreeterSayHello4WithResponse request returning *GreeterSayHello4Response
func (c *ClientWithResponses) GreeterSayHello4WithResponse(ctx context.Context, boolVal bool, params *GreeterSayHello4Params, reqEditors ...RequestEditorFn) (*GreeterSayHello4Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GreeterSayHello5WithResponse request returning *GreeterSayHello5Response
func (c *ClientWithResponses) GreeterSayHello5WithResponse(ctx context.Context, bytesVal []byte, params *GreeterSayHello5Params, reqEditors ...RequestEditorFn) (*GreeterSayHello5Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GreeterSayHello3WithResponse request returning *GreeterSayHello3Response
func (c *ClientWithResponses) GreeterSayHello3WithResponse(ctx context.Context, doubleVal float64, params *GreeterSayHello3Params, reqEditors ...RequestEditorFn) (*GreeterSayHello3Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GreeterSayHello2WithResponse request returning *GreeterSayHello2Response
func (c *ClientWithResponses) GreeterSayHello2WithResponse(ctx context.Context, floatVal float32, params *GreeterSayHello2Params, reqEditors ...RequestEditorFn) (*GreeterSayHello2Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GreeterSayHello6WithResponse request returning *GreeterSayHello6Response
func (c *ClientWithResponses) GreeterSayHello6WithResponse(ctx context.Context, int32Val int32, params *GreeterSayHello6Params, reqEditors ...RequestEditorFn) (*GreeterSayHello6Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GreeterSayHello8WithResponse request returning *GreeterSayHello8Response
func (c *ClientWithResponses) GreeterSayHello8WithResponse(ctx context.Context, int64Val string, params *GreeterSayHello8Params, reqEditors ...RequestEditorFn) (*GreeterSayHello8Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GreeterSayHello1WithResponse request returning *GreeterSayHello1Response
func (c *ClientWithResponses) GreeterSayHello1WithResponse(ctx context.Context, strVal string, params *GreeterSayHello1Params, reqEditors ...RequestEditorFn) (*GreeterSayHello1Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GreeterSayHello7WithResponse request returning *GreeterSayHello7Response
func (c *ClientWithResponses) GreeterSayHello7WithResponse(ctx context.Context, uint32Val int64, params *GreeterSayHello7Params, reqEditors ...RequestEditorFn) (*GreeterSayHello7Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GreeterSayHello9WithResponse request returning *GreeterSayHello9Response
func (c *ClientWithResponses) GreeterSayHello9WithResponse(ctx context.Context, uint64Val string, params *GreeterSayHello9Params, reqEditors ...RequestEditorFn) (*GreeterSayHello9Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GreeterSayHelloWithResponse request returning *GreeterSayHelloResponse
func (c *ClientWithResponses) GreeterSayHelloWithResponse(ctx context.Context, name string, params *GreeterSayHelloParams, reqEditors ...RequestEditorFn) (*GreeterSayHelloResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ParseGreeterSayHello4Response parses an HTTP response from a GreeterSayHello4WithResponse call
func ParseGreeterSayHello4Response(rsp *http.Response) (*GreeterSayHello4Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ParseGreeterSayHello5Response parses an HTTP response from a GreeterSayHello5WithResponse call
func ParseGreeterSayHello5Response(rsp *http.Response) (*GreeterSayHello5Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ParseGreeterSayHello3Response parses an HTTP response from a GreeterSayHello3WithResponse call
func ParseGreeterSayHello3Response(rsp *http.Response) (*GreeterSayHello3Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ParseGreeterSayHello2Response parses an HTTP response from a GreeterSayHello2WithResponse call
func ParseGreeterSayHello2Response(rsp *http.Response) (*GreeterSayHello2Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ParseGreeterSayHello6Response parses an HTTP response from a GreeterSayHello6WithResponse call
func ParseGreeterSayHello6Response(rsp *http.Response) (*GreeterSayHello6Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ParseGreeterSayHello8Response parses an HTTP response from a GreeterSayHello8WithResponse call
func ParseGreeterSayHello8Response(rsp *http.Response) (*GreeterSayHello8Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ParseGreeterSayHello1Response parses an HTTP response from a GreeterSayHello1WithResponse call
func ParseGreeterSayHello1Response(rsp *http.Response) (*GreeterSayHello1Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ParseGreeterSayHello7Response parses an HTTP response from a GreeterSayHello7WithResponse call
func ParseGreeterSayHello7Response(rsp *http.Response) (*GreeterSayHello7Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ParseGreeterSayHello9Response parses an HTTP response from a GreeterSayHello9WithResponse call
func ParseGreeterSayHello9Response(rsp *http.Response) (*GreeterSayHello9Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ParseGreeterSayHelloResponse parses an HTTP response from a GreeterSayHelloWithResponse call
func ParseGreeterSayHelloResponse(rsp *http.Response) (*GreeterSayHelloResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}
