// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// ExamplepbUnannotatedNestedMessage examplepb unannotated nested message
//
// swagger:model examplepbUnannotatedNestedMessage
type ExamplepbUnannotatedNestedMessage struct {

	// n Id
	NID string `json:"nId,omitempty"`

	// val
	Val string `json:"val,omitempty"`
}

// Validate validates this examplepb unannotated nested message
func (m *ExamplepbUnannotatedNestedMessage) Validate(formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// ContextValidate validates this examplepb unannotated nested message based on context it is used
	return nil
}

func (m *ExamplepbUnannotatedNestedMessage) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// MarshalBinary interface implementation
	return nil
}

func (m *ExamplepbUnannotatedNestedMessage) MarshalBinary() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalBinary interface implementation
func (m *ExamplepbUnannotatedNestedMessage) UnmarshalBinary(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}
