// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: examples/internal/proto/examplepb/enum_with_single_value.proto

package examplepb

import (
	context "context"

	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EnumWithSingleValueService_Echo_FullMethodName = "/grpc.gateway.examples.internal.proto.examplepb.EnumWithSingleValueService/Echo"
)

// EnumWithSingleValueServiceClient is the client API for EnumWithSingleValueService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EnumWithSingleValueServiceClient interface {
	Echo(ctx context.Context, in *EnumWithSingleValueServiceEchoRequest, opts ...grpc.CallOption) (*EnumWithSingleValueServiceEchoResponse, error)
}

type enumWithSingleValueServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEnumWithSingleValueServiceClient(cc grpc.ClientConnInterface) EnumWithSingleValueServiceClient {
	_ = "STUB: not implemented"
	return *new(EnumWithSingleValueServiceClient)
}

func (c *enumWithSingleValueServiceClient) Echo(ctx context.Context, in *EnumWithSingleValueServiceEchoRequest, opts ...grpc.CallOption) (*EnumWithSingleValueServiceEchoResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// EnumWithSingleValueServiceServer is the server API for EnumWithSingleValueService service.
// All implementations should embed UnimplementedEnumWithSingleValueServiceServer
// for forward compatibility.
type EnumWithSingleValueServiceServer interface {
	Echo(context.Context, *EnumWithSingleValueServiceEchoRequest) (*EnumWithSingleValueServiceEchoResponse, error)
}

// UnimplementedEnumWithSingleValueServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEnumWithSingleValueServiceServer struct{}

func (UnimplementedEnumWithSingleValueServiceServer) Echo(context.Context, *EnumWithSingleValueServiceEchoRequest) (*EnumWithSingleValueServiceEchoResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedEnumWithSingleValueServiceServer) testEmbeddedByValue() {
	_ = "STUB: not implemented"

	// UnsafeEnumWithSingleValueServiceServer may be embedded to opt out of forward compatibility for this service.
	// Use of this interface is not recommended, as added methods to EnumWithSingleValueServiceServer will
	// result in compilation errors.
	return
}

type UnsafeEnumWithSingleValueServiceServer interface {
	mustEmbedUnimplementedEnumWithSingleValueServiceServer()
}

func RegisterEnumWithSingleValueServiceServer(s grpc.ServiceRegistrar, srv EnumWithSingleValueServiceServer) {
	_ = "STUB: not implemented"
	// If the following call pancis, it indicates UnimplementedEnumWithSingleValueServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	return
}

func _EnumWithSingleValueService_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// EnumWithSingleValueService_ServiceDesc is the grpc.ServiceDesc for EnumWithSingleValueService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EnumWithSingleValueService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.gateway.examples.internal.proto.examplepb.EnumWithSingleValueService",
	HandlerType: (*EnumWithSingleValueServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _EnumWithSingleValueService_Echo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "examples/internal/proto/examplepb/enum_with_single_value.proto",
}
