// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: examples/internal/proto/examplepb/proto3_field_semantics.proto

package examplepb

import (
	context "context"

	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Proto3FieldSemanticsService_GetFilter_FullMethodName = "/grpc.gateway.examples.internal.proto.examplepb.Proto3FieldSemanticsService/GetFilter"
)

// Proto3FieldSemanticsServiceClient is the client API for Proto3FieldSemanticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Proto3FieldSemanticsServiceClient interface {
	GetFilter(ctx context.Context, in *GetFilterRequest, opts ...grpc.CallOption) (*GetFilterResponse, error)
}

type proto3FieldSemanticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProto3FieldSemanticsServiceClient(cc grpc.ClientConnInterface) Proto3FieldSemanticsServiceClient {
	_ = "STUB: not implemented"
	return *new(Proto3FieldSemanticsServiceClient)
}

func (c *proto3FieldSemanticsServiceClient) GetFilter(ctx context.Context, in *GetFilterRequest, opts ...grpc.CallOption) (*GetFilterResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Proto3FieldSemanticsServiceServer is the server API for Proto3FieldSemanticsService service.
// All implementations should embed UnimplementedProto3FieldSemanticsServiceServer
// for forward compatibility.
type Proto3FieldSemanticsServiceServer interface {
	GetFilter(context.Context, *GetFilterRequest) (*GetFilterResponse, error)
}

// UnimplementedProto3FieldSemanticsServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProto3FieldSemanticsServiceServer struct{}

func (UnimplementedProto3FieldSemanticsServiceServer) GetFilter(context.Context, *GetFilterRequest) (*GetFilterResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedProto3FieldSemanticsServiceServer) testEmbeddedByValue() {
	_ = "STUB: not implemented"

	// UnsafeProto3FieldSemanticsServiceServer may be embedded to opt out of forward compatibility for this service.
	// Use of this interface is not recommended, as added methods to Proto3FieldSemanticsServiceServer will
	// result in compilation errors.
	return
}

type UnsafeProto3FieldSemanticsServiceServer interface {
	mustEmbedUnimplementedProto3FieldSemanticsServiceServer()
}

func RegisterProto3FieldSemanticsServiceServer(s grpc.ServiceRegistrar, srv Proto3FieldSemanticsServiceServer) {
	_ = "STUB: not implemented"
	// If the following call pancis, it indicates UnimplementedProto3FieldSemanticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	return
}

func _Proto3FieldSemanticsService_GetFilter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Proto3FieldSemanticsService_ServiceDesc is the grpc.ServiceDesc for Proto3FieldSemanticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Proto3FieldSemanticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.gateway.examples.internal.proto.examplepb.Proto3FieldSemanticsService",
	HandlerType: (*Proto3FieldSemanticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFilter",
			Handler:    _Proto3FieldSemanticsService_GetFilter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "examples/internal/proto/examplepb/proto3_field_semantics.proto",
}
