// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// ExamplepbResponseBodyOut examplepb response body out
//
// swagger:model examplepbResponseBodyOut
type ExamplepbResponseBodyOut struct {

	// response
	Response *ExamplepbResponseBodyOutResponse `json:"response,omitempty"`
}

// Validate validates this examplepb response body out
func (m *ExamplepbResponseBodyOut) Validate(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ExamplepbResponseBodyOut) validateResponse(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
	// not required
}

// ContextValidate validate this examplepb response body out based on the context it is used
func (m *ExamplepbResponseBodyOut) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ExamplepbResponseBodyOut) contextValidateResponse(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// not required

// MarshalBinary interface implementation
func (m *ExamplepbResponseBodyOut) MarshalBinary() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalBinary interface implementation
func (m *ExamplepbResponseBodyOut) UnmarshalBinary(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}
