// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/strfmt"
)

// ResponseResponseType - UNKNOWN: UNKNOWN
//   - A: A is 1
//   - B: B is 2
//
// swagger:model ResponseResponseType
type ResponseResponseType string

func NewResponseResponseType(value ResponseResponseType) *ResponseResponseType {
	_ = "STUB: not implemented"

	// Pointer returns a pointer to a freshly-allocated ResponseResponseType.
	return nil
}

func (m ResponseResponseType) Pointer() *ResponseResponseType {
	_ = "STUB: not implemented"
	return nil

	// ResponseResponseTypeUNKNOWN captures enum value "UNKNOWN"
}

const (
	ResponseResponseTypeUNKNOWN ResponseResponseType = "UNKNOWN"

	// ResponseResponseTypeA captures enum value "A"
	ResponseResponseTypeA ResponseResponseType = "A"

	// ResponseResponseTypeB captures enum value "B"
	ResponseResponseTypeB ResponseResponseType = "B"
)

// for schema
var responseResponseTypeEnum []any

func init() {
	var res []ResponseResponseType
	if err := json.Unmarshal([]byte(`["UNKNOWN","A","B"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		responseResponseTypeEnum = append(responseResponseTypeEnum, v)
	}
}

func (m ResponseResponseType) validateResponseResponseTypeEnum(path, location string, value ResponseResponseType) error {
	_ = "STUB: not implemented"
	return nil
}

// Validate validates this response response type
func (m ResponseResponseType) Validate(formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// value enum
	return nil
}

// ContextValidate validates this response response type based on context it is used
func (m ResponseResponseType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}
