// Code generated by go-swagger; DO NOT EDIT.

package response_body_service

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// NewResponseBodyServiceGetResponseBodyParams creates a new ResponseBodyServiceGetResponseBodyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewResponseBodyServiceGetResponseBodyParams() *ResponseBodyServiceGetResponseBodyParams {
	_ = "STUB: not implemented"
	return nil
}

// NewResponseBodyServiceGetResponseBodyParamsWithTimeout creates a new ResponseBodyServiceGetResponseBodyParams object
// with the ability to set a timeout on a request.
func NewResponseBodyServiceGetResponseBodyParamsWithTimeout(timeout time.Duration) *ResponseBodyServiceGetResponseBodyParams {
	_ = "STUB: not implemented"
	return nil
}

// NewResponseBodyServiceGetResponseBodyParamsWithContext creates a new ResponseBodyServiceGetResponseBodyParams object
// with the ability to set a context for a request.
func NewResponseBodyServiceGetResponseBodyParamsWithContext(ctx context.Context) *ResponseBodyServiceGetResponseBodyParams {
	_ = "STUB: not implemented"
	return nil
}

// NewResponseBodyServiceGetResponseBodyParamsWithHTTPClient creates a new ResponseBodyServiceGetResponseBodyParams object
// with the ability to set a custom HTTPClient for a request.
func NewResponseBodyServiceGetResponseBodyParamsWithHTTPClient(client *http.Client) *ResponseBodyServiceGetResponseBodyParams {
	_ = "STUB: not implemented"
	return nil
}

/*
ResponseBodyServiceGetResponseBodyParams contains all the parameters to send to the API endpoint

	for the response body service get response body operation.

	Typically these are written to a http.Request.
*/
type ResponseBodyServiceGetResponseBodyParams struct {

	// Data.
	Data string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the response body service get response body params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ResponseBodyServiceGetResponseBodyParams) WithDefaults() *ResponseBodyServiceGetResponseBodyParams {
	_ = "STUB: not implemented"
	return nil

	// SetDefaults hydrates default values in the response body service get response body params (not the query body).
	//
	// All values with no default are reset to their zero value.
}

func (o *ResponseBodyServiceGetResponseBodyParams) SetDefaults() {
	_ = "STUB: not implemented"
	// no default values defined for this parameter
	return
}

// WithTimeout adds the timeout to the response body service get response body params
func (o *ResponseBodyServiceGetResponseBodyParams) WithTimeout(timeout time.Duration) *ResponseBodyServiceGetResponseBodyParams {
	_ = "STUB: not implemented"
	return nil
}

// SetTimeout adds the timeout to the response body service get response body params
func (o *ResponseBodyServiceGetResponseBodyParams) SetTimeout(timeout time.Duration) {
	_ = "STUB: not implemented"
	return

	// WithContext adds the context to the response body service get response body params
}

func (o *ResponseBodyServiceGetResponseBodyParams) WithContext(ctx context.Context) *ResponseBodyServiceGetResponseBodyParams {
	_ = "STUB: not implemented"
	return nil
}

// SetContext adds the context to the response body service get response body params
func (o *ResponseBodyServiceGetResponseBodyParams) SetContext(ctx context.Context) {
	_ = "STUB: not implemented"

	// WithHTTPClient adds the HTTPClient to the response body service get response body params
	return
}

func (o *ResponseBodyServiceGetResponseBodyParams) WithHTTPClient(client *http.Client) *ResponseBodyServiceGetResponseBodyParams {
	_ = "STUB: not implemented"
	return nil
}

// SetHTTPClient adds the HTTPClient to the response body service get response body params
func (o *ResponseBodyServiceGetResponseBodyParams) SetHTTPClient(client *http.Client) {
	_ = "STUB: not implemented"
	return

	// WithData adds the data to the response body service get response body params
}

func (o *ResponseBodyServiceGetResponseBodyParams) WithData(data string) *ResponseBodyServiceGetResponseBodyParams {
	_ = "STUB: not implemented"
	return nil

	// SetData adds the data to the response body service get response body params
}

func (o *ResponseBodyServiceGetResponseBodyParams) SetData(data string) {
	_ = "STUB: not implemented"

	// WriteToRequest writes these params to a swagger request
	return
}

func (o *ResponseBodyServiceGetResponseBodyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// path param data
