// Code generated by go-swagger; DO NOT EDIT.

package a_bit_of_everything

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/grpc-ecosystem/grpc-gateway/v2/examples/internal/clients/abe/models"
)

// ABitOfEverythingServiceOverwriteRequestContentTypeReader is a Reader for the ABitOfEverythingServiceOverwriteRequestContentType structure.
type ABitOfEverythingServiceOverwriteRequestContentTypeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ABitOfEverythingServiceOverwriteRequestContentTypeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

// NewABitOfEverythingServiceOverwriteRequestContentTypeOK creates a ABitOfEverythingServiceOverwriteRequestContentTypeOK with default headers values
func NewABitOfEverythingServiceOverwriteRequestContentTypeOK() *ABitOfEverythingServiceOverwriteRequestContentTypeOK {
	_ = "STUB: not implemented"
	return nil
}

/*
ABitOfEverythingServiceOverwriteRequestContentTypeOK describes a response with status code 200, with default header values.

A successful response.
*/
type ABitOfEverythingServiceOverwriteRequestContentTypeOK struct {
	Payload any
}

// IsSuccess returns true when this a bit of everything service overwrite request content type o k response has a 2xx status code
func (o *ABitOfEverythingServiceOverwriteRequestContentTypeOK) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this a bit of everything service overwrite request content type o k response has a 3xx status code
	return false
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeOK) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this a bit of everything service overwrite request content type o k response has a 4xx status code
	return false
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeOK) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this a bit of everything service overwrite request content type o k response has a 5xx status code
	return false
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeOK) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this a bit of everything service overwrite request content type o k response a status code equal to that given
	return false
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeOK) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the a bit of everything service overwrite request content type o k response
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeOK) Code() int {
	_ = "STUB: not implemented"
	return 0
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeOK) Error() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeOK) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeOK) GetPayload() any {
	_ = "STUB: not implemented"
	return *new(any)
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// response payload
	return nil
}

// NewABitOfEverythingServiceOverwriteRequestContentTypeForbidden creates a ABitOfEverythingServiceOverwriteRequestContentTypeForbidden with default headers values
func NewABitOfEverythingServiceOverwriteRequestContentTypeForbidden() *ABitOfEverythingServiceOverwriteRequestContentTypeForbidden {
	_ = "STUB: not implemented"
	return nil
}

/*
ABitOfEverythingServiceOverwriteRequestContentTypeForbidden describes a response with status code 403, with default header values.

Returned when the user does not have permission to access the resource.
*/
type ABitOfEverythingServiceOverwriteRequestContentTypeForbidden struct {
	Payload any
}

// IsSuccess returns true when this a bit of everything service overwrite request content type forbidden response has a 2xx status code
func (o *ABitOfEverythingServiceOverwriteRequestContentTypeForbidden) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this a bit of everything service overwrite request content type forbidden response has a 3xx status code
	return false
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeForbidden) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this a bit of everything service overwrite request content type forbidden response has a 4xx status code
	return false
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeForbidden) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this a bit of everything service overwrite request content type forbidden response has a 5xx status code
	return false
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeForbidden) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this a bit of everything service overwrite request content type forbidden response a status code equal to that given
	return false
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeForbidden) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the a bit of everything service overwrite request content type forbidden response
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeForbidden) Code() int {
	_ = "STUB: not implemented"
	return 0
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeForbidden) Error() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeForbidden) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeForbidden) GetPayload() any {
	_ = "STUB: not implemented"
	return *new(any)
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// response payload
	return nil
}

// NewABitOfEverythingServiceOverwriteRequestContentTypeNotFound creates a ABitOfEverythingServiceOverwriteRequestContentTypeNotFound with default headers values
func NewABitOfEverythingServiceOverwriteRequestContentTypeNotFound() *ABitOfEverythingServiceOverwriteRequestContentTypeNotFound {
	_ = "STUB: not implemented"
	return nil
}

/*
ABitOfEverythingServiceOverwriteRequestContentTypeNotFound describes a response with status code 404, with default header values.

Returned when the resource does not exist.
*/
type ABitOfEverythingServiceOverwriteRequestContentTypeNotFound struct {
	Payload string
}

// IsSuccess returns true when this a bit of everything service overwrite request content type not found response has a 2xx status code
func (o *ABitOfEverythingServiceOverwriteRequestContentTypeNotFound) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this a bit of everything service overwrite request content type not found response has a 3xx status code
	return false
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeNotFound) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this a bit of everything service overwrite request content type not found response has a 4xx status code
	return false
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeNotFound) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this a bit of everything service overwrite request content type not found response has a 5xx status code
	return false
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeNotFound) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this a bit of everything service overwrite request content type not found response a status code equal to that given
	return false
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeNotFound) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the a bit of everything service overwrite request content type not found response
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeNotFound) Code() int {
	_ = "STUB: not implemented"
	return 0
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeNotFound) Error() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeNotFound) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeNotFound) GetPayload() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// response payload
	return nil
}

// NewABitOfEverythingServiceOverwriteRequestContentTypeIMATeapot creates a ABitOfEverythingServiceOverwriteRequestContentTypeIMATeapot with default headers values
func NewABitOfEverythingServiceOverwriteRequestContentTypeIMATeapot() *ABitOfEverythingServiceOverwriteRequestContentTypeIMATeapot {
	_ = "STUB: not implemented"
	return nil
}

/*
ABitOfEverythingServiceOverwriteRequestContentTypeIMATeapot describes a response with status code 418, with default header values.

I'm a teapot.
*/
type ABitOfEverythingServiceOverwriteRequestContentTypeIMATeapot struct {
	Payload models.ExamplepbNumericEnum
}

// IsSuccess returns true when this a bit of everything service overwrite request content type i m a teapot response has a 2xx status code
func (o *ABitOfEverythingServiceOverwriteRequestContentTypeIMATeapot) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this a bit of everything service overwrite request content type i m a teapot response has a 3xx status code
	return false
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeIMATeapot) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this a bit of everything service overwrite request content type i m a teapot response has a 4xx status code
	return false
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeIMATeapot) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this a bit of everything service overwrite request content type i m a teapot response has a 5xx status code
	return false
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeIMATeapot) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this a bit of everything service overwrite request content type i m a teapot response a status code equal to that given
	return false
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeIMATeapot) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the a bit of everything service overwrite request content type i m a teapot response
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeIMATeapot) Code() int {
	_ = "STUB: not implemented"
	return 0
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeIMATeapot) Error() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeIMATeapot) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeIMATeapot) GetPayload() models.ExamplepbNumericEnum {
	_ = "STUB: not implemented"
	return *new(models.ExamplepbNumericEnum)
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeIMATeapot) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// response payload
	return nil
}

// NewABitOfEverythingServiceOverwriteRequestContentTypeInternalServerError creates a ABitOfEverythingServiceOverwriteRequestContentTypeInternalServerError with default headers values
func NewABitOfEverythingServiceOverwriteRequestContentTypeInternalServerError() *ABitOfEverythingServiceOverwriteRequestContentTypeInternalServerError {
	_ = "STUB: not implemented"
	return nil
}

/*
ABitOfEverythingServiceOverwriteRequestContentTypeInternalServerError describes a response with status code 500, with default header values.

Server error
*/
type ABitOfEverythingServiceOverwriteRequestContentTypeInternalServerError struct {
	Payload *models.ExamplepbErrorResponse
}

// IsSuccess returns true when this a bit of everything service overwrite request content type internal server error response has a 2xx status code
func (o *ABitOfEverythingServiceOverwriteRequestContentTypeInternalServerError) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this a bit of everything service overwrite request content type internal server error response has a 3xx status code
	return false
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeInternalServerError) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this a bit of everything service overwrite request content type internal server error response has a 4xx status code
	return false
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeInternalServerError) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this a bit of everything service overwrite request content type internal server error response has a 5xx status code
	return false
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeInternalServerError) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this a bit of everything service overwrite request content type internal server error response a status code equal to that given
	return false
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeInternalServerError) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the a bit of everything service overwrite request content type internal server error response
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeInternalServerError) Code() int {
	_ = "STUB: not implemented"
	return 0
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeInternalServerError) Error() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeInternalServerError) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeInternalServerError) GetPayload() *models.ExamplepbErrorResponse {
	_ = "STUB: not implemented"
	return nil
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// response payload

// NewABitOfEverythingServiceOverwriteRequestContentTypeDefault creates a ABitOfEverythingServiceOverwriteRequestContentTypeDefault with default headers values
func NewABitOfEverythingServiceOverwriteRequestContentTypeDefault(code int) *ABitOfEverythingServiceOverwriteRequestContentTypeDefault {
	_ = "STUB: not implemented"
	return nil
}

/*
ABitOfEverythingServiceOverwriteRequestContentTypeDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ABitOfEverythingServiceOverwriteRequestContentTypeDefault struct {
	_statusCode int

	Payload *models.GoogleRPCStatus
}

// IsSuccess returns true when this a bit of everything service overwrite request content type default response has a 2xx status code
func (o *ABitOfEverythingServiceOverwriteRequestContentTypeDefault) IsSuccess() bool {
	_ = "STUB: not implemented"
	return false
}

// IsRedirect returns true when this a bit of everything service overwrite request content type default response has a 3xx status code
func (o *ABitOfEverythingServiceOverwriteRequestContentTypeDefault) IsRedirect() bool {
	_ = "STUB: not implemented"
	return false
}

// IsClientError returns true when this a bit of everything service overwrite request content type default response has a 4xx status code
func (o *ABitOfEverythingServiceOverwriteRequestContentTypeDefault) IsClientError() bool {
	_ = "STUB: not implemented"
	return false
}

// IsServerError returns true when this a bit of everything service overwrite request content type default response has a 5xx status code
func (o *ABitOfEverythingServiceOverwriteRequestContentTypeDefault) IsServerError() bool {
	_ = "STUB: not implemented"
	return false
}

// IsCode returns true when this a bit of everything service overwrite request content type default response a status code equal to that given
func (o *ABitOfEverythingServiceOverwriteRequestContentTypeDefault) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the a bit of everything service overwrite request content type default response
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeDefault) Code() int {
	_ = "STUB: not implemented"
	return 0
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeDefault) Error() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeDefault) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeDefault) GetPayload() *models.GoogleRPCStatus {
	_ = "STUB: not implemented"
	return nil
}

func (o *ABitOfEverythingServiceOverwriteRequestContentTypeDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// response payload
