// Code generated by go-swagger; DO NOT EDIT.

package a_bit_of_everything

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/grpc-ecosystem/grpc-gateway/v2/examples/internal/clients/abe/models"
)

// ABitOfEverythingServiceCreateBookReader is a Reader for the ABitOfEverythingServiceCreateBook structure.
type ABitOfEverythingServiceCreateBookReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ABitOfEverythingServiceCreateBookReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

// NewABitOfEverythingServiceCreateBookOK creates a ABitOfEverythingServiceCreateBookOK with default headers values
func NewABitOfEverythingServiceCreateBookOK() *ABitOfEverythingServiceCreateBookOK {
	_ = "STUB: not implemented"
	return nil
}

/*
ABitOfEverythingServiceCreateBookOK describes a response with status code 200, with default header values.

A successful response.
*/
type ABitOfEverythingServiceCreateBookOK struct {
	Payload *models.ExamplepbBook
}

// IsSuccess returns true when this a bit of everything service create book o k response has a 2xx status code
func (o *ABitOfEverythingServiceCreateBookOK) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this a bit of everything service create book o k response has a 3xx status code
	return false
}

func (o *ABitOfEverythingServiceCreateBookOK) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this a bit of everything service create book o k response has a 4xx status code
	return false
}

func (o *ABitOfEverythingServiceCreateBookOK) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this a bit of everything service create book o k response has a 5xx status code
	return false
}

func (o *ABitOfEverythingServiceCreateBookOK) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this a bit of everything service create book o k response a status code equal to that given
	return false
}

func (o *ABitOfEverythingServiceCreateBookOK) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the a bit of everything service create book o k response
}

func (o *ABitOfEverythingServiceCreateBookOK) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *ABitOfEverythingServiceCreateBookOK) Error() string { _ = "STUB: not implemented"; return "" }

func (o *ABitOfEverythingServiceCreateBookOK) String() string { _ = "STUB: not implemented"; return "" }

func (o *ABitOfEverythingServiceCreateBookOK) GetPayload() *models.ExamplepbBook {
	_ = "STUB: not implemented"
	return nil
}

func (o *ABitOfEverythingServiceCreateBookOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// response payload

// NewABitOfEverythingServiceCreateBookForbidden creates a ABitOfEverythingServiceCreateBookForbidden with default headers values
func NewABitOfEverythingServiceCreateBookForbidden() *ABitOfEverythingServiceCreateBookForbidden {
	_ = "STUB: not implemented"
	return nil
}

/*
ABitOfEverythingServiceCreateBookForbidden describes a response with status code 403, with default header values.

Returned when the user does not have permission to access the resource.
*/
type ABitOfEverythingServiceCreateBookForbidden struct {
	Payload any
}

// IsSuccess returns true when this a bit of everything service create book forbidden response has a 2xx status code
func (o *ABitOfEverythingServiceCreateBookForbidden) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this a bit of everything service create book forbidden response has a 3xx status code
	return false
}

func (o *ABitOfEverythingServiceCreateBookForbidden) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this a bit of everything service create book forbidden response has a 4xx status code
	return false
}

func (o *ABitOfEverythingServiceCreateBookForbidden) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this a bit of everything service create book forbidden response has a 5xx status code
	return false
}

func (o *ABitOfEverythingServiceCreateBookForbidden) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this a bit of everything service create book forbidden response a status code equal to that given
	return false
}

func (o *ABitOfEverythingServiceCreateBookForbidden) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the a bit of everything service create book forbidden response
}

func (o *ABitOfEverythingServiceCreateBookForbidden) Code() int {
	_ = "STUB: not implemented"
	return 0
}

func (o *ABitOfEverythingServiceCreateBookForbidden) Error() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceCreateBookForbidden) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceCreateBookForbidden) GetPayload() any {
	_ = "STUB: not implemented"
	return *new(any)
}

func (o *ABitOfEverythingServiceCreateBookForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// response payload
	return nil
}

// NewABitOfEverythingServiceCreateBookNotFound creates a ABitOfEverythingServiceCreateBookNotFound with default headers values
func NewABitOfEverythingServiceCreateBookNotFound() *ABitOfEverythingServiceCreateBookNotFound {
	_ = "STUB: not implemented"
	return nil
}

/*
ABitOfEverythingServiceCreateBookNotFound describes a response with status code 404, with default header values.

Returned when the resource does not exist.
*/
type ABitOfEverythingServiceCreateBookNotFound struct {
	Payload string
}

// IsSuccess returns true when this a bit of everything service create book not found response has a 2xx status code
func (o *ABitOfEverythingServiceCreateBookNotFound) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this a bit of everything service create book not found response has a 3xx status code
	return false
}

func (o *ABitOfEverythingServiceCreateBookNotFound) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this a bit of everything service create book not found response has a 4xx status code
	return false
}

func (o *ABitOfEverythingServiceCreateBookNotFound) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this a bit of everything service create book not found response has a 5xx status code
	return false
}

func (o *ABitOfEverythingServiceCreateBookNotFound) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this a bit of everything service create book not found response a status code equal to that given
	return false
}

func (o *ABitOfEverythingServiceCreateBookNotFound) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the a bit of everything service create book not found response
}

func (o *ABitOfEverythingServiceCreateBookNotFound) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *ABitOfEverythingServiceCreateBookNotFound) Error() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceCreateBookNotFound) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceCreateBookNotFound) GetPayload() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceCreateBookNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// response payload
	return nil
}

// NewABitOfEverythingServiceCreateBookIMATeapot creates a ABitOfEverythingServiceCreateBookIMATeapot with default headers values
func NewABitOfEverythingServiceCreateBookIMATeapot() *ABitOfEverythingServiceCreateBookIMATeapot {
	_ = "STUB: not implemented"
	return nil
}

/*
ABitOfEverythingServiceCreateBookIMATeapot describes a response with status code 418, with default header values.

I'm a teapot.
*/
type ABitOfEverythingServiceCreateBookIMATeapot struct {
	Payload models.ExamplepbNumericEnum
}

// IsSuccess returns true when this a bit of everything service create book i m a teapot response has a 2xx status code
func (o *ABitOfEverythingServiceCreateBookIMATeapot) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this a bit of everything service create book i m a teapot response has a 3xx status code
	return false
}

func (o *ABitOfEverythingServiceCreateBookIMATeapot) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this a bit of everything service create book i m a teapot response has a 4xx status code
	return false
}

func (o *ABitOfEverythingServiceCreateBookIMATeapot) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this a bit of everything service create book i m a teapot response has a 5xx status code
	return false
}

func (o *ABitOfEverythingServiceCreateBookIMATeapot) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this a bit of everything service create book i m a teapot response a status code equal to that given
	return false
}

func (o *ABitOfEverythingServiceCreateBookIMATeapot) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the a bit of everything service create book i m a teapot response
}

func (o *ABitOfEverythingServiceCreateBookIMATeapot) Code() int {
	_ = "STUB: not implemented"
	return 0
}

func (o *ABitOfEverythingServiceCreateBookIMATeapot) Error() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceCreateBookIMATeapot) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceCreateBookIMATeapot) GetPayload() models.ExamplepbNumericEnum {
	_ = "STUB: not implemented"
	return *new(models.ExamplepbNumericEnum)
}

func (o *ABitOfEverythingServiceCreateBookIMATeapot) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// response payload
	return nil
}

// NewABitOfEverythingServiceCreateBookInternalServerError creates a ABitOfEverythingServiceCreateBookInternalServerError with default headers values
func NewABitOfEverythingServiceCreateBookInternalServerError() *ABitOfEverythingServiceCreateBookInternalServerError {
	_ = "STUB: not implemented"
	return nil
}

/*
ABitOfEverythingServiceCreateBookInternalServerError describes a response with status code 500, with default header values.

Server error
*/
type ABitOfEverythingServiceCreateBookInternalServerError struct {
	Payload *models.ExamplepbErrorResponse
}

// IsSuccess returns true when this a bit of everything service create book internal server error response has a 2xx status code
func (o *ABitOfEverythingServiceCreateBookInternalServerError) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this a bit of everything service create book internal server error response has a 3xx status code
	return false
}

func (o *ABitOfEverythingServiceCreateBookInternalServerError) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this a bit of everything service create book internal server error response has a 4xx status code
	return false
}

func (o *ABitOfEverythingServiceCreateBookInternalServerError) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this a bit of everything service create book internal server error response has a 5xx status code
	return false
}

func (o *ABitOfEverythingServiceCreateBookInternalServerError) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this a bit of everything service create book internal server error response a status code equal to that given
	return false
}

func (o *ABitOfEverythingServiceCreateBookInternalServerError) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the a bit of everything service create book internal server error response
}

func (o *ABitOfEverythingServiceCreateBookInternalServerError) Code() int {
	_ = "STUB: not implemented"
	return 0
}

func (o *ABitOfEverythingServiceCreateBookInternalServerError) Error() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceCreateBookInternalServerError) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceCreateBookInternalServerError) GetPayload() *models.ExamplepbErrorResponse {
	_ = "STUB: not implemented"
	return nil
}

func (o *ABitOfEverythingServiceCreateBookInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// response payload

// NewABitOfEverythingServiceCreateBookDefault creates a ABitOfEverythingServiceCreateBookDefault with default headers values
func NewABitOfEverythingServiceCreateBookDefault(code int) *ABitOfEverythingServiceCreateBookDefault {
	_ = "STUB: not implemented"
	return nil
}

/*
ABitOfEverythingServiceCreateBookDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ABitOfEverythingServiceCreateBookDefault struct {
	_statusCode int

	Payload *models.GoogleRPCStatus
}

// IsSuccess returns true when this a bit of everything service create book default response has a 2xx status code
func (o *ABitOfEverythingServiceCreateBookDefault) IsSuccess() bool {
	_ = "STUB: not implemented"
	return false
}

// IsRedirect returns true when this a bit of everything service create book default response has a 3xx status code
func (o *ABitOfEverythingServiceCreateBookDefault) IsRedirect() bool {
	_ = "STUB: not implemented"
	return false
}

// IsClientError returns true when this a bit of everything service create book default response has a 4xx status code
func (o *ABitOfEverythingServiceCreateBookDefault) IsClientError() bool {
	_ = "STUB: not implemented"
	return false
}

// IsServerError returns true when this a bit of everything service create book default response has a 5xx status code
func (o *ABitOfEverythingServiceCreateBookDefault) IsServerError() bool {
	_ = "STUB: not implemented"
	return false
}

// IsCode returns true when this a bit of everything service create book default response a status code equal to that given
func (o *ABitOfEverythingServiceCreateBookDefault) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the a bit of everything service create book default response
}

func (o *ABitOfEverythingServiceCreateBookDefault) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *ABitOfEverythingServiceCreateBookDefault) Error() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceCreateBookDefault) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceCreateBookDefault) GetPayload() *models.GoogleRPCStatus {
	_ = "STUB: not implemented"
	return nil
}

func (o *ABitOfEverythingServiceCreateBookDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// response payload
