// Code generated by go-swagger; DO NOT EDIT.

package a_bit_of_everything

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/grpc-ecosystem/grpc-gateway/v2/examples/internal/clients/abe/models"
)

// ABitOfEverythingServicePostOneofEnumReader is a Reader for the ABitOfEverythingServicePostOneofEnum structure.
type ABitOfEverythingServicePostOneofEnumReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ABitOfEverythingServicePostOneofEnumReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

// NewABitOfEverythingServicePostOneofEnumOK creates a ABitOfEverythingServicePostOneofEnumOK with default headers values
func NewABitOfEverythingServicePostOneofEnumOK() *ABitOfEverythingServicePostOneofEnumOK {
	_ = "STUB: not implemented"
	return nil
}

/*
ABitOfEverythingServicePostOneofEnumOK describes a response with status code 200, with default header values.

A successful response.
*/
type ABitOfEverythingServicePostOneofEnumOK struct {
	Payload any
}

// IsSuccess returns true when this a bit of everything service post oneof enum o k response has a 2xx status code
func (o *ABitOfEverythingServicePostOneofEnumOK) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this a bit of everything service post oneof enum o k response has a 3xx status code
	return false
}

func (o *ABitOfEverythingServicePostOneofEnumOK) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this a bit of everything service post oneof enum o k response has a 4xx status code
	return false
}

func (o *ABitOfEverythingServicePostOneofEnumOK) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this a bit of everything service post oneof enum o k response has a 5xx status code
	return false
}

func (o *ABitOfEverythingServicePostOneofEnumOK) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this a bit of everything service post oneof enum o k response a status code equal to that given
	return false
}

func (o *ABitOfEverythingServicePostOneofEnumOK) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the a bit of everything service post oneof enum o k response
}

func (o *ABitOfEverythingServicePostOneofEnumOK) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *ABitOfEverythingServicePostOneofEnumOK) Error() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServicePostOneofEnumOK) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServicePostOneofEnumOK) GetPayload() any {
	_ = "STUB: not implemented"
	return *new(any)
}

func (o *ABitOfEverythingServicePostOneofEnumOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// response payload
	return nil
}

// NewABitOfEverythingServicePostOneofEnumForbidden creates a ABitOfEverythingServicePostOneofEnumForbidden with default headers values
func NewABitOfEverythingServicePostOneofEnumForbidden() *ABitOfEverythingServicePostOneofEnumForbidden {
	_ = "STUB: not implemented"
	return nil
}

/*
ABitOfEverythingServicePostOneofEnumForbidden describes a response with status code 403, with default header values.

Returned when the user does not have permission to access the resource.
*/
type ABitOfEverythingServicePostOneofEnumForbidden struct {
	Payload any
}

// IsSuccess returns true when this a bit of everything service post oneof enum forbidden response has a 2xx status code
func (o *ABitOfEverythingServicePostOneofEnumForbidden) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this a bit of everything service post oneof enum forbidden response has a 3xx status code
	return false
}

func (o *ABitOfEverythingServicePostOneofEnumForbidden) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this a bit of everything service post oneof enum forbidden response has a 4xx status code
	return false
}

func (o *ABitOfEverythingServicePostOneofEnumForbidden) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this a bit of everything service post oneof enum forbidden response has a 5xx status code
	return false
}

func (o *ABitOfEverythingServicePostOneofEnumForbidden) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this a bit of everything service post oneof enum forbidden response a status code equal to that given
	return false
}

func (o *ABitOfEverythingServicePostOneofEnumForbidden) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the a bit of everything service post oneof enum forbidden response
}

func (o *ABitOfEverythingServicePostOneofEnumForbidden) Code() int {
	_ = "STUB: not implemented"
	return 0
}

func (o *ABitOfEverythingServicePostOneofEnumForbidden) Error() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServicePostOneofEnumForbidden) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServicePostOneofEnumForbidden) GetPayload() any {
	_ = "STUB: not implemented"
	return *new(any)
}

func (o *ABitOfEverythingServicePostOneofEnumForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// response payload
	return nil
}

// NewABitOfEverythingServicePostOneofEnumNotFound creates a ABitOfEverythingServicePostOneofEnumNotFound with default headers values
func NewABitOfEverythingServicePostOneofEnumNotFound() *ABitOfEverythingServicePostOneofEnumNotFound {
	_ = "STUB: not implemented"
	return nil
}

/*
ABitOfEverythingServicePostOneofEnumNotFound describes a response with status code 404, with default header values.

Returned when the resource does not exist.
*/
type ABitOfEverythingServicePostOneofEnumNotFound struct {
	Payload string
}

// IsSuccess returns true when this a bit of everything service post oneof enum not found response has a 2xx status code
func (o *ABitOfEverythingServicePostOneofEnumNotFound) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this a bit of everything service post oneof enum not found response has a 3xx status code
	return false
}

func (o *ABitOfEverythingServicePostOneofEnumNotFound) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this a bit of everything service post oneof enum not found response has a 4xx status code
	return false
}

func (o *ABitOfEverythingServicePostOneofEnumNotFound) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this a bit of everything service post oneof enum not found response has a 5xx status code
	return false
}

func (o *ABitOfEverythingServicePostOneofEnumNotFound) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this a bit of everything service post oneof enum not found response a status code equal to that given
	return false
}

func (o *ABitOfEverythingServicePostOneofEnumNotFound) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the a bit of everything service post oneof enum not found response
}

func (o *ABitOfEverythingServicePostOneofEnumNotFound) Code() int {
	_ = "STUB: not implemented"
	return 0
}

func (o *ABitOfEverythingServicePostOneofEnumNotFound) Error() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServicePostOneofEnumNotFound) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServicePostOneofEnumNotFound) GetPayload() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServicePostOneofEnumNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// response payload
	return nil
}

// NewABitOfEverythingServicePostOneofEnumIMATeapot creates a ABitOfEverythingServicePostOneofEnumIMATeapot with default headers values
func NewABitOfEverythingServicePostOneofEnumIMATeapot() *ABitOfEverythingServicePostOneofEnumIMATeapot {
	_ = "STUB: not implemented"
	return nil
}

/*
ABitOfEverythingServicePostOneofEnumIMATeapot describes a response with status code 418, with default header values.

I'm a teapot.
*/
type ABitOfEverythingServicePostOneofEnumIMATeapot struct {
	Payload models.ExamplepbNumericEnum
}

// IsSuccess returns true when this a bit of everything service post oneof enum i m a teapot response has a 2xx status code
func (o *ABitOfEverythingServicePostOneofEnumIMATeapot) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this a bit of everything service post oneof enum i m a teapot response has a 3xx status code
	return false
}

func (o *ABitOfEverythingServicePostOneofEnumIMATeapot) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this a bit of everything service post oneof enum i m a teapot response has a 4xx status code
	return false
}

func (o *ABitOfEverythingServicePostOneofEnumIMATeapot) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this a bit of everything service post oneof enum i m a teapot response has a 5xx status code
	return false
}

func (o *ABitOfEverythingServicePostOneofEnumIMATeapot) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this a bit of everything service post oneof enum i m a teapot response a status code equal to that given
	return false
}

func (o *ABitOfEverythingServicePostOneofEnumIMATeapot) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the a bit of everything service post oneof enum i m a teapot response
}

func (o *ABitOfEverythingServicePostOneofEnumIMATeapot) Code() int {
	_ = "STUB: not implemented"
	return 0
}

func (o *ABitOfEverythingServicePostOneofEnumIMATeapot) Error() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServicePostOneofEnumIMATeapot) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServicePostOneofEnumIMATeapot) GetPayload() models.ExamplepbNumericEnum {
	_ = "STUB: not implemented"
	return *new(models.ExamplepbNumericEnum)
}

func (o *ABitOfEverythingServicePostOneofEnumIMATeapot) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// response payload
	return nil
}

// NewABitOfEverythingServicePostOneofEnumInternalServerError creates a ABitOfEverythingServicePostOneofEnumInternalServerError with default headers values
func NewABitOfEverythingServicePostOneofEnumInternalServerError() *ABitOfEverythingServicePostOneofEnumInternalServerError {
	_ = "STUB: not implemented"
	return nil
}

/*
ABitOfEverythingServicePostOneofEnumInternalServerError describes a response with status code 500, with default header values.

Server error
*/
type ABitOfEverythingServicePostOneofEnumInternalServerError struct {
	Payload *models.ExamplepbErrorResponse
}

// IsSuccess returns true when this a bit of everything service post oneof enum internal server error response has a 2xx status code
func (o *ABitOfEverythingServicePostOneofEnumInternalServerError) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this a bit of everything service post oneof enum internal server error response has a 3xx status code
	return false
}

func (o *ABitOfEverythingServicePostOneofEnumInternalServerError) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this a bit of everything service post oneof enum internal server error response has a 4xx status code
	return false
}

func (o *ABitOfEverythingServicePostOneofEnumInternalServerError) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this a bit of everything service post oneof enum internal server error response has a 5xx status code
	return false
}

func (o *ABitOfEverythingServicePostOneofEnumInternalServerError) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this a bit of everything service post oneof enum internal server error response a status code equal to that given
	return false
}

func (o *ABitOfEverythingServicePostOneofEnumInternalServerError) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the a bit of everything service post oneof enum internal server error response
}

func (o *ABitOfEverythingServicePostOneofEnumInternalServerError) Code() int {
	_ = "STUB: not implemented"
	return 0
}

func (o *ABitOfEverythingServicePostOneofEnumInternalServerError) Error() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServicePostOneofEnumInternalServerError) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServicePostOneofEnumInternalServerError) GetPayload() *models.ExamplepbErrorResponse {
	_ = "STUB: not implemented"
	return nil
}

func (o *ABitOfEverythingServicePostOneofEnumInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// response payload

// NewABitOfEverythingServicePostOneofEnumDefault creates a ABitOfEverythingServicePostOneofEnumDefault with default headers values
func NewABitOfEverythingServicePostOneofEnumDefault(code int) *ABitOfEverythingServicePostOneofEnumDefault {
	_ = "STUB: not implemented"
	return nil
}

/*
ABitOfEverythingServicePostOneofEnumDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ABitOfEverythingServicePostOneofEnumDefault struct {
	_statusCode int

	Payload *models.GoogleRPCStatus
}

// IsSuccess returns true when this a bit of everything service post oneof enum default response has a 2xx status code
func (o *ABitOfEverythingServicePostOneofEnumDefault) IsSuccess() bool {
	_ = "STUB: not implemented"
	return false
}

// IsRedirect returns true when this a bit of everything service post oneof enum default response has a 3xx status code
func (o *ABitOfEverythingServicePostOneofEnumDefault) IsRedirect() bool {
	_ = "STUB: not implemented"
	return false
}

// IsClientError returns true when this a bit of everything service post oneof enum default response has a 4xx status code
func (o *ABitOfEverythingServicePostOneofEnumDefault) IsClientError() bool {
	_ = "STUB: not implemented"
	return false
}

// IsServerError returns true when this a bit of everything service post oneof enum default response has a 5xx status code
func (o *ABitOfEverythingServicePostOneofEnumDefault) IsServerError() bool {
	_ = "STUB: not implemented"
	return false
}

// IsCode returns true when this a bit of everything service post oneof enum default response a status code equal to that given
func (o *ABitOfEverythingServicePostOneofEnumDefault) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the a bit of everything service post oneof enum default response
}

func (o *ABitOfEverythingServicePostOneofEnumDefault) Code() int {
	_ = "STUB: not implemented"
	return 0
}

func (o *ABitOfEverythingServicePostOneofEnumDefault) Error() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServicePostOneofEnumDefault) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServicePostOneofEnumDefault) GetPayload() *models.GoogleRPCStatus {
	_ = "STUB: not implemented"
	return nil
}

func (o *ABitOfEverythingServicePostOneofEnumDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// response payload
