// Code generated by go-swagger; DO NOT EDIT.

package a_bit_of_everything

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/grpc-ecosystem/grpc-gateway/v2/examples/internal/clients/abe/models"
)

// ABitOfEverythingServiceCheckGetQueryParamsReader is a Reader for the ABitOfEverythingServiceCheckGetQueryParams structure.
type ABitOfEverythingServiceCheckGetQueryParamsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ABitOfEverythingServiceCheckGetQueryParamsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

// NewABitOfEverythingServiceCheckGetQueryParamsOK creates a ABitOfEverythingServiceCheckGetQueryParamsOK with default headers values
func NewABitOfEverythingServiceCheckGetQueryParamsOK() *ABitOfEverythingServiceCheckGetQueryParamsOK {
	_ = "STUB: not implemented"
	return nil
}

/*
ABitOfEverythingServiceCheckGetQueryParamsOK describes a response with status code 200, with default header values.

A successful response.
*/
type ABitOfEverythingServiceCheckGetQueryParamsOK struct {
	Payload *models.ExamplepbABitOfEverything
}

// IsSuccess returns true when this a bit of everything service check get query params o k response has a 2xx status code
func (o *ABitOfEverythingServiceCheckGetQueryParamsOK) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this a bit of everything service check get query params o k response has a 3xx status code
	return false
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsOK) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this a bit of everything service check get query params o k response has a 4xx status code
	return false
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsOK) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this a bit of everything service check get query params o k response has a 5xx status code
	return false
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsOK) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this a bit of everything service check get query params o k response a status code equal to that given
	return false
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsOK) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the a bit of everything service check get query params o k response
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsOK) Code() int {
	_ = "STUB: not implemented"
	return 0
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsOK) Error() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsOK) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsOK) GetPayload() *models.ExamplepbABitOfEverything {
	_ = "STUB: not implemented"
	return nil
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// response payload

// NewABitOfEverythingServiceCheckGetQueryParamsForbidden creates a ABitOfEverythingServiceCheckGetQueryParamsForbidden with default headers values
func NewABitOfEverythingServiceCheckGetQueryParamsForbidden() *ABitOfEverythingServiceCheckGetQueryParamsForbidden {
	_ = "STUB: not implemented"
	return nil
}

/*
ABitOfEverythingServiceCheckGetQueryParamsForbidden describes a response with status code 403, with default header values.

Returned when the user does not have permission to access the resource.
*/
type ABitOfEverythingServiceCheckGetQueryParamsForbidden struct {
	Payload any
}

// IsSuccess returns true when this a bit of everything service check get query params forbidden response has a 2xx status code
func (o *ABitOfEverythingServiceCheckGetQueryParamsForbidden) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this a bit of everything service check get query params forbidden response has a 3xx status code
	return false
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsForbidden) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this a bit of everything service check get query params forbidden response has a 4xx status code
	return false
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsForbidden) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this a bit of everything service check get query params forbidden response has a 5xx status code
	return false
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsForbidden) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this a bit of everything service check get query params forbidden response a status code equal to that given
	return false
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsForbidden) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the a bit of everything service check get query params forbidden response
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsForbidden) Code() int {
	_ = "STUB: not implemented"
	return 0
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsForbidden) Error() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsForbidden) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsForbidden) GetPayload() any {
	_ = "STUB: not implemented"
	return *new(any)
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// response payload
	return nil
}

// NewABitOfEverythingServiceCheckGetQueryParamsNotFound creates a ABitOfEverythingServiceCheckGetQueryParamsNotFound with default headers values
func NewABitOfEverythingServiceCheckGetQueryParamsNotFound() *ABitOfEverythingServiceCheckGetQueryParamsNotFound {
	_ = "STUB: not implemented"
	return nil
}

/*
ABitOfEverythingServiceCheckGetQueryParamsNotFound describes a response with status code 404, with default header values.

Returned when the resource does not exist.
*/
type ABitOfEverythingServiceCheckGetQueryParamsNotFound struct {
	Payload string
}

// IsSuccess returns true when this a bit of everything service check get query params not found response has a 2xx status code
func (o *ABitOfEverythingServiceCheckGetQueryParamsNotFound) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this a bit of everything service check get query params not found response has a 3xx status code
	return false
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsNotFound) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this a bit of everything service check get query params not found response has a 4xx status code
	return false
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsNotFound) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this a bit of everything service check get query params not found response has a 5xx status code
	return false
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsNotFound) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this a bit of everything service check get query params not found response a status code equal to that given
	return false
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsNotFound) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the a bit of everything service check get query params not found response
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsNotFound) Code() int {
	_ = "STUB: not implemented"
	return 0
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsNotFound) Error() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsNotFound) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsNotFound) GetPayload() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// response payload
	return nil
}

// NewABitOfEverythingServiceCheckGetQueryParamsIMATeapot creates a ABitOfEverythingServiceCheckGetQueryParamsIMATeapot with default headers values
func NewABitOfEverythingServiceCheckGetQueryParamsIMATeapot() *ABitOfEverythingServiceCheckGetQueryParamsIMATeapot {
	_ = "STUB: not implemented"
	return nil
}

/*
ABitOfEverythingServiceCheckGetQueryParamsIMATeapot describes a response with status code 418, with default header values.

I'm a teapot.
*/
type ABitOfEverythingServiceCheckGetQueryParamsIMATeapot struct {
	Payload models.ExamplepbNumericEnum
}

// IsSuccess returns true when this a bit of everything service check get query params i m a teapot response has a 2xx status code
func (o *ABitOfEverythingServiceCheckGetQueryParamsIMATeapot) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this a bit of everything service check get query params i m a teapot response has a 3xx status code
	return false
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsIMATeapot) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this a bit of everything service check get query params i m a teapot response has a 4xx status code
	return false
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsIMATeapot) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this a bit of everything service check get query params i m a teapot response has a 5xx status code
	return false
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsIMATeapot) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this a bit of everything service check get query params i m a teapot response a status code equal to that given
	return false
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsIMATeapot) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the a bit of everything service check get query params i m a teapot response
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsIMATeapot) Code() int {
	_ = "STUB: not implemented"
	return 0
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsIMATeapot) Error() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsIMATeapot) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsIMATeapot) GetPayload() models.ExamplepbNumericEnum {
	_ = "STUB: not implemented"
	return *new(models.ExamplepbNumericEnum)
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsIMATeapot) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// response payload
	return nil
}

// NewABitOfEverythingServiceCheckGetQueryParamsInternalServerError creates a ABitOfEverythingServiceCheckGetQueryParamsInternalServerError with default headers values
func NewABitOfEverythingServiceCheckGetQueryParamsInternalServerError() *ABitOfEverythingServiceCheckGetQueryParamsInternalServerError {
	_ = "STUB: not implemented"
	return nil
}

/*
ABitOfEverythingServiceCheckGetQueryParamsInternalServerError describes a response with status code 500, with default header values.

Server error
*/
type ABitOfEverythingServiceCheckGetQueryParamsInternalServerError struct {
	Payload *models.ExamplepbErrorResponse
}

// IsSuccess returns true when this a bit of everything service check get query params internal server error response has a 2xx status code
func (o *ABitOfEverythingServiceCheckGetQueryParamsInternalServerError) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this a bit of everything service check get query params internal server error response has a 3xx status code
	return false
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsInternalServerError) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this a bit of everything service check get query params internal server error response has a 4xx status code
	return false
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsInternalServerError) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this a bit of everything service check get query params internal server error response has a 5xx status code
	return false
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsInternalServerError) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this a bit of everything service check get query params internal server error response a status code equal to that given
	return false
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsInternalServerError) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the a bit of everything service check get query params internal server error response
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsInternalServerError) Code() int {
	_ = "STUB: not implemented"
	return 0
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsInternalServerError) Error() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsInternalServerError) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsInternalServerError) GetPayload() *models.ExamplepbErrorResponse {
	_ = "STUB: not implemented"
	return nil
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// response payload

// NewABitOfEverythingServiceCheckGetQueryParamsDefault creates a ABitOfEverythingServiceCheckGetQueryParamsDefault with default headers values
func NewABitOfEverythingServiceCheckGetQueryParamsDefault(code int) *ABitOfEverythingServiceCheckGetQueryParamsDefault {
	_ = "STUB: not implemented"
	return nil
}

/*
ABitOfEverythingServiceCheckGetQueryParamsDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ABitOfEverythingServiceCheckGetQueryParamsDefault struct {
	_statusCode int

	Payload *models.GoogleRPCStatus
}

// IsSuccess returns true when this a bit of everything service check get query params default response has a 2xx status code
func (o *ABitOfEverythingServiceCheckGetQueryParamsDefault) IsSuccess() bool {
	_ = "STUB: not implemented"
	return false
}

// IsRedirect returns true when this a bit of everything service check get query params default response has a 3xx status code
func (o *ABitOfEverythingServiceCheckGetQueryParamsDefault) IsRedirect() bool {
	_ = "STUB: not implemented"
	return false
}

// IsClientError returns true when this a bit of everything service check get query params default response has a 4xx status code
func (o *ABitOfEverythingServiceCheckGetQueryParamsDefault) IsClientError() bool {
	_ = "STUB: not implemented"
	return false
}

// IsServerError returns true when this a bit of everything service check get query params default response has a 5xx status code
func (o *ABitOfEverythingServiceCheckGetQueryParamsDefault) IsServerError() bool {
	_ = "STUB: not implemented"
	return false
}

// IsCode returns true when this a bit of everything service check get query params default response a status code equal to that given
func (o *ABitOfEverythingServiceCheckGetQueryParamsDefault) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the a bit of everything service check get query params default response
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsDefault) Code() int {
	_ = "STUB: not implemented"
	return 0
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsDefault) Error() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsDefault) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsDefault) GetPayload() *models.GoogleRPCStatus {
	_ = "STUB: not implemented"
	return nil
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// response payload
