// Code generated by go-swagger; DO NOT EDIT.

package a_bit_of_everything

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/grpc-ecosystem/grpc-gateway/v2/examples/internal/clients/abe/models"
)

// NewABitOfEverythingServiceCreateBodyParams creates a new ABitOfEverythingServiceCreateBodyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewABitOfEverythingServiceCreateBodyParams() *ABitOfEverythingServiceCreateBodyParams {
	_ = "STUB: not implemented"
	return nil
}

// NewABitOfEverythingServiceCreateBodyParamsWithTimeout creates a new ABitOfEverythingServiceCreateBodyParams object
// with the ability to set a timeout on a request.
func NewABitOfEverythingServiceCreateBodyParamsWithTimeout(timeout time.Duration) *ABitOfEverythingServiceCreateBodyParams {
	_ = "STUB: not implemented"
	return nil
}

// NewABitOfEverythingServiceCreateBodyParamsWithContext creates a new ABitOfEverythingServiceCreateBodyParams object
// with the ability to set a context for a request.
func NewABitOfEverythingServiceCreateBodyParamsWithContext(ctx context.Context) *ABitOfEverythingServiceCreateBodyParams {
	_ = "STUB: not implemented"
	return nil
}

// NewABitOfEverythingServiceCreateBodyParamsWithHTTPClient creates a new ABitOfEverythingServiceCreateBodyParams object
// with the ability to set a custom HTTPClient for a request.
func NewABitOfEverythingServiceCreateBodyParamsWithHTTPClient(client *http.Client) *ABitOfEverythingServiceCreateBodyParams {
	_ = "STUB: not implemented"
	return nil
}

/*
ABitOfEverythingServiceCreateBodyParams contains all the parameters to send to the API endpoint

	for the a bit of everything service create body operation.

	Typically these are written to a http.Request.
*/
type ABitOfEverythingServiceCreateBodyParams struct {

	/* Body.

	   Intentionally complicated message type to cover many features of Protobuf.
	*/
	Body *models.ExamplepbABitOfEverything

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the a bit of everything service create body params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ABitOfEverythingServiceCreateBodyParams) WithDefaults() *ABitOfEverythingServiceCreateBodyParams {
	_ = "STUB: not implemented"
	return nil

	// SetDefaults hydrates default values in the a bit of everything service create body params (not the query body).
	//
	// All values with no default are reset to their zero value.
}

func (o *ABitOfEverythingServiceCreateBodyParams) SetDefaults() {
	_ = "STUB: not implemented"
	// no default values defined for this parameter
	return
}

// WithTimeout adds the timeout to the a bit of everything service create body params
func (o *ABitOfEverythingServiceCreateBodyParams) WithTimeout(timeout time.Duration) *ABitOfEverythingServiceCreateBodyParams {
	_ = "STUB: not implemented"
	return nil
}

// SetTimeout adds the timeout to the a bit of everything service create body params
func (o *ABitOfEverythingServiceCreateBodyParams) SetTimeout(timeout time.Duration) {
	_ = "STUB: not implemented"
	return

	// WithContext adds the context to the a bit of everything service create body params
}

func (o *ABitOfEverythingServiceCreateBodyParams) WithContext(ctx context.Context) *ABitOfEverythingServiceCreateBodyParams {
	_ = "STUB: not implemented"
	return nil
}

// SetContext adds the context to the a bit of everything service create body params
func (o *ABitOfEverythingServiceCreateBodyParams) SetContext(ctx context.Context) {
	_ = "STUB: not implemented"

	// WithHTTPClient adds the HTTPClient to the a bit of everything service create body params
	return
}

func (o *ABitOfEverythingServiceCreateBodyParams) WithHTTPClient(client *http.Client) *ABitOfEverythingServiceCreateBodyParams {
	_ = "STUB: not implemented"
	return nil
}

// SetHTTPClient adds the HTTPClient to the a bit of everything service create body params
func (o *ABitOfEverythingServiceCreateBodyParams) SetHTTPClient(client *http.Client) {
	_ = "STUB: not implemented"
	return

	// WithBody adds the body to the a bit of everything service create body params
}

func (o *ABitOfEverythingServiceCreateBodyParams) WithBody(body *models.ExamplepbABitOfEverything) *ABitOfEverythingServiceCreateBodyParams {
	_ = "STUB: not implemented"
	return nil

	// SetBody adds the body to the a bit of everything service create body params
}

func (o *ABitOfEverythingServiceCreateBodyParams) SetBody(body *models.ExamplepbABitOfEverything) {
	_ = "STUB: not implemented"

	// WriteToRequest writes these params to a swagger request
	return
}

func (o *ABitOfEverythingServiceCreateBodyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}
