// Code generated by go-swagger; DO NOT EDIT.

package a_bit_of_everything

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// NewABitOfEverythingServiceDeleteParams creates a new ABitOfEverythingServiceDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewABitOfEverythingServiceDeleteParams() *ABitOfEverythingServiceDeleteParams {
	_ = "STUB: not implemented"
	return nil
}

// NewABitOfEverythingServiceDeleteParamsWithTimeout creates a new ABitOfEverythingServiceDeleteParams object
// with the ability to set a timeout on a request.
func NewABitOfEverythingServiceDeleteParamsWithTimeout(timeout time.Duration) *ABitOfEverythingServiceDeleteParams {
	_ = "STUB: not implemented"
	return nil
}

// NewABitOfEverythingServiceDeleteParamsWithContext creates a new ABitOfEverythingServiceDeleteParams object
// with the ability to set a context for a request.
func NewABitOfEverythingServiceDeleteParamsWithContext(ctx context.Context) *ABitOfEverythingServiceDeleteParams {
	_ = "STUB: not implemented"
	return nil
}

// NewABitOfEverythingServiceDeleteParamsWithHTTPClient creates a new ABitOfEverythingServiceDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewABitOfEverythingServiceDeleteParamsWithHTTPClient(client *http.Client) *ABitOfEverythingServiceDeleteParams {
	_ = "STUB: not implemented"
	return nil
}

/*
ABitOfEverythingServiceDeleteParams contains all the parameters to send to the API endpoint

	for the a bit of everything service delete operation.

	Typically these are written to a http.Request.
*/
type ABitOfEverythingServiceDeleteParams struct {

	// UUID.
	UUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the a bit of everything service delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ABitOfEverythingServiceDeleteParams) WithDefaults() *ABitOfEverythingServiceDeleteParams {
	_ = "STUB: not implemented"
	return nil

	// SetDefaults hydrates default values in the a bit of everything service delete params (not the query body).
	//
	// All values with no default are reset to their zero value.
}

func (o *ABitOfEverythingServiceDeleteParams) SetDefaults() {
	_ = "STUB: not implemented"
	// no default values defined for this parameter
	return
}

// WithTimeout adds the timeout to the a bit of everything service delete params
func (o *ABitOfEverythingServiceDeleteParams) WithTimeout(timeout time.Duration) *ABitOfEverythingServiceDeleteParams {
	_ = "STUB: not implemented"
	return nil
}

// SetTimeout adds the timeout to the a bit of everything service delete params
func (o *ABitOfEverythingServiceDeleteParams) SetTimeout(timeout time.Duration) {
	_ = "STUB: not implemented"
	return

	// WithContext adds the context to the a bit of everything service delete params
}

func (o *ABitOfEverythingServiceDeleteParams) WithContext(ctx context.Context) *ABitOfEverythingServiceDeleteParams {
	_ = "STUB: not implemented"
	return nil
}

// SetContext adds the context to the a bit of everything service delete params
func (o *ABitOfEverythingServiceDeleteParams) SetContext(ctx context.Context) {
	_ = "STUB: not implemented"

	// WithHTTPClient adds the HTTPClient to the a bit of everything service delete params
	return
}

func (o *ABitOfEverythingServiceDeleteParams) WithHTTPClient(client *http.Client) *ABitOfEverythingServiceDeleteParams {
	_ = "STUB: not implemented"
	return nil
}

// SetHTTPClient adds the HTTPClient to the a bit of everything service delete params
func (o *ABitOfEverythingServiceDeleteParams) SetHTTPClient(client *http.Client) {
	_ = "STUB: not implemented"
	return

	// WithUUID adds the uuid to the a bit of everything service delete params
}

func (o *ABitOfEverythingServiceDeleteParams) WithUUID(uuid string) *ABitOfEverythingServiceDeleteParams {
	_ = "STUB: not implemented"
	return nil

	// SetUUID adds the uuid to the a bit of everything service delete params
}

func (o *ABitOfEverythingServiceDeleteParams) SetUUID(uuid string) {
	_ = "STUB: not implemented"

	// WriteToRequest writes these params to a swagger request
	return
}

func (o *ABitOfEverythingServiceDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// path param uuid
