// Code generated by go-swagger; DO NOT EDIT.

package a_bit_of_everything

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// NewABitOfEverythingServiceCheckGetQueryParamsParams creates a new ABitOfEverythingServiceCheckGetQueryParamsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewABitOfEverythingServiceCheckGetQueryParamsParams() *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// NewABitOfEverythingServiceCheckGetQueryParamsParamsWithTimeout creates a new ABitOfEverythingServiceCheckGetQueryParamsParams object
// with the ability to set a timeout on a request.
func NewABitOfEverythingServiceCheckGetQueryParamsParamsWithTimeout(timeout time.Duration) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// NewABitOfEverythingServiceCheckGetQueryParamsParamsWithContext creates a new ABitOfEverythingServiceCheckGetQueryParamsParams object
// with the ability to set a context for a request.
func NewABitOfEverythingServiceCheckGetQueryParamsParamsWithContext(ctx context.Context) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// NewABitOfEverythingServiceCheckGetQueryParamsParamsWithHTTPClient creates a new ABitOfEverythingServiceCheckGetQueryParamsParams object
// with the ability to set a custom HTTPClient for a request.
func NewABitOfEverythingServiceCheckGetQueryParamsParamsWithHTTPClient(client *http.Client) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

/*
ABitOfEverythingServiceCheckGetQueryParamsParams contains all the parameters to send to the API endpoint

	for the a bit of everything service check get query params operation.

	Typically these are written to a http.Request.
*/
type ABitOfEverythingServiceCheckGetQueryParamsParams struct {

	// BoolValue.
	BoolValue *bool

	// BytesValue.
	//
	// Format: byte
	BytesValue *strfmt.Base64

	// DoubleValue.
	//
	// Format: double
	DoubleValue float64

	/* EnumValue.

	     - ZERO: ZERO means 0
	- ONE: ONE means 1

	    Default: "ZERO"
	*/
	EnumValue *string

	/* EnumValueAnnotation.

	     Numeric enum title

	Numeric enum description.

	 - ZERO: ZERO means 0
	 - ONE: ONE means 1

	     Default: "ZERO"
	*/
	EnumValueAnnotation *string

	// Fixed32Value.
	//
	// Format: int64
	Fixed32Value *int64

	// Fixed64Value.
	//
	// Format: uint64
	Fixed64Value *string

	/* FloatValue.

	   Float value field

	   Format: float
	   Default: 0.2
	*/
	FloatValue float32

	// Int32Value.
	//
	// Format: int32
	Int32Value *int32

	// Int64OverrideType.
	//
	// Format: int64
	Int64OverrideType *string

	// Int64Value.
	//
	// Format: int64
	Int64Value string

	/* MapValue.

	   map of numeric enum
	*/
	MapValue *string

	// MappedNestedValue.
	MappedNestedValue *string

	/* MappedStringValue.

	     Map of string title

	Map of string description.
	*/
	MappedStringValue *string

	// NestedAnnotationAmount.
	//
	// Format: int64
	NestedAnnotationAmount *int64

	/* NestedAnnotationOk.

	    DeepEnum description.

	- FALSE: FALSE is false.
	- TRUE: TRUE is true.

	    Default: "FALSE"
	*/
	NestedAnnotationOk *string

	// NestedPathEnumValue.
	//
	// Default: "GHI"
	NestedPathEnumValue *string

	// NonConventionalNameValue.
	NonConventionalNameValue *string

	// OneofEmpty.
	OneofEmpty *string

	// OneofString.
	OneofString *string

	/* OptionalStringField.

	   Test openapiv2 generation of required fields with annotation and jsonschema to reproduce
	*/
	OptionalStringField *string

	// OptionalStringValue.
	OptionalStringValue *string

	/* OutputOnlyStringViaFieldBehaviorAnnotation.

	   mark a field as readonly in Open API definition
	*/
	OutputOnlyStringViaFieldBehaviorAnnotation *string

	// PathEnumValue.
	//
	// Default: "ABC"
	PathEnumValue *string

	/* ProductID.

	     Test openapiv2 generation of repeated fields

	Only digits are allowed.
	*/
	ProductID []string

	/* RepeatedEnumAnnotation.

	     Repeated numeric enum title

	Repeated numeric enum description.

	 - ZERO: ZERO means 0
	 - ONE: ONE means 1
	*/
	RepeatedEnumAnnotation []string

	/* RepeatedEnumValue.

	    repeated enum value. it is comma-separated in query

	- ZERO: ZERO means 0
	- ONE: ONE means 1
	*/
	RepeatedEnumValue []string

	/* RepeatedStringAnnotation.

	     Repeated string title

	Repeated string description.
	*/
	RepeatedStringAnnotation []string

	// RepeatedStringValue.
	RepeatedStringValue []string

	// RequiredStringField1.
	RequiredStringField1 string

	// RequiredStringField2.
	RequiredStringField2 string

	/* RequiredStringViaFieldBehaviorAnnotation.

	   mark a field as required in Open API definition
	*/
	RequiredStringViaFieldBehaviorAnnotation string

	/* RequiredFieldBehaviorJSONNameCustom.

	   Test openapiv2 handling of required json_name fields
	*/
	RequiredFieldBehaviorJSONNameCustom string

	// RequiredFieldSchemaJSONNameCustom.
	RequiredFieldSchemaJSONNameCustom string

	// Sfixed32Value.
	//
	// Format: int32
	Sfixed32Value *int32

	// Sfixed64Value.
	//
	// Format: int64
	Sfixed64Value *string

	// SingleNestedAmount.
	//
	// Format: int64
	SingleNestedAmount *int64

	/* SingleNestedName.

	   name is nested field.
	*/
	SingleNestedName string

	/* SingleNestedOk.

	    DeepEnum description.

	- FALSE: FALSE is false.
	- TRUE: TRUE is true.

	    Default: "FALSE"
	*/
	SingleNestedOk *string

	// Sint32Value.
	//
	// Format: int32
	Sint32Value *int32

	// Sint64Value.
	//
	// Format: int64
	Sint64Value *string

	// StringValue.
	StringValue *string

	// TimestampValue.
	//
	// Format: date-time
	TimestampValue *strfmt.DateTime

	/* TrailingBoth.

	     Leading both

	Trailing both.
	*/
	TrailingBoth *string

	/* TrailingMultiline.

	     Leading multiline

	This is an example of a multi-line comment.

	Trailing multiline.
	*/
	TrailingMultiline *string

	/* TrailingOnly.

	   Trailing only
	*/
	TrailingOnly *string

	/* TrailingOnlyDot.

	   Trailing only dot.
	*/
	TrailingOnlyDot *string

	// Uint32Value.
	//
	// Format: int64
	Uint32Value *int64

	// Uint64Value.
	//
	// Format: uint64
	Uint64Value *string

	// UUID.
	//
	// Format: uuid
	UUID strfmt.UUID

	/* Uuids.

	   Specify a custom format of repeated field items
	*/
	Uuids []strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the a bit of everything service check get query params params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithDefaults() *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil

	// SetDefaults hydrates default values in the a bit of everything service check get query params params (not the query body).
	//
	// All values with no default are reset to their zero value.
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetDefaults() {
	_ = "STUB: not implemented"
	return
}

// WithTimeout adds the timeout to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithTimeout(timeout time.Duration) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetTimeout adds the timeout to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetTimeout(timeout time.Duration) {
	_ = "STUB: not implemented"
	return

	// WithContext adds the context to the a bit of everything service check get query params params
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithContext(ctx context.Context) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetContext adds the context to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetContext(ctx context.Context) {
	_ = "STUB: not implemented"

	// WithHTTPClient adds the HTTPClient to the a bit of everything service check get query params params
	return
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithHTTPClient(client *http.Client) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetHTTPClient adds the HTTPClient to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetHTTPClient(client *http.Client) {
	_ = "STUB: not implemented"
	return

	// WithBoolValue adds the boolValue to the a bit of everything service check get query params params
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithBoolValue(boolValue *bool) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetBoolValue adds the boolValue to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetBoolValue(boolValue *bool) {
	_ = "STUB: not implemented"
	return

	// WithBytesValue adds the bytesValue to the a bit of everything service check get query params params
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithBytesValue(bytesValue *strfmt.Base64) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetBytesValue adds the bytesValue to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetBytesValue(bytesValue *strfmt.Base64) {
	_ = "STUB: not implemented"
	return
}

// WithDoubleValue adds the doubleValue to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithDoubleValue(doubleValue float64) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetDoubleValue adds the doubleValue to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetDoubleValue(doubleValue float64) {
	_ = "STUB: not implemented"
	return
}

// WithEnumValue adds the enumValue to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithEnumValue(enumValue *string) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetEnumValue adds the enumValue to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetEnumValue(enumValue *string) {
	_ = "STUB: not implemented"
	return

	// WithEnumValueAnnotation adds the enumValueAnnotation to the a bit of everything service check get query params params
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithEnumValueAnnotation(enumValueAnnotation *string) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetEnumValueAnnotation adds the enumValueAnnotation to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetEnumValueAnnotation(enumValueAnnotation *string) {
	_ = "STUB: not implemented"
	return
}

// WithFixed32Value adds the fixed32Value to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithFixed32Value(fixed32Value *int64) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetFixed32Value adds the fixed32Value to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetFixed32Value(fixed32Value *int64) {
	_ = "STUB: not implemented"
	return
}

// WithFixed64Value adds the fixed64Value to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithFixed64Value(fixed64Value *string) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetFixed64Value adds the fixed64Value to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetFixed64Value(fixed64Value *string) {
	_ = "STUB: not implemented"
	return
}

// WithFloatValue adds the floatValue to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithFloatValue(floatValue float32) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetFloatValue adds the floatValue to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetFloatValue(floatValue float32) {
	_ = "STUB: not implemented"
	return
}

// WithInt32Value adds the int32Value to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithInt32Value(int32Value *int32) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetInt32Value adds the int32Value to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetInt32Value(int32Value *int32) {
	_ = "STUB: not implemented"
	return
}

// WithInt64OverrideType adds the int64OverrideType to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithInt64OverrideType(int64OverrideType *string) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetInt64OverrideType adds the int64OverrideType to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetInt64OverrideType(int64OverrideType *string) {
	_ = "STUB: not implemented"
	return
}

// WithInt64Value adds the int64Value to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithInt64Value(int64Value string) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetInt64Value adds the int64Value to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetInt64Value(int64Value string) {
	_ = "STUB: not implemented"
	return
}

// WithMapValue adds the mapValue to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithMapValue(mapValue *string) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetMapValue adds the mapValue to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetMapValue(mapValue *string) {
	_ = "STUB: not implemented"
	return

	// WithMappedNestedValue adds the mappedNestedValue to the a bit of everything service check get query params params
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithMappedNestedValue(mappedNestedValue *string) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetMappedNestedValue adds the mappedNestedValue to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetMappedNestedValue(mappedNestedValue *string) {
	_ = "STUB: not implemented"
	return
}

// WithMappedStringValue adds the mappedStringValue to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithMappedStringValue(mappedStringValue *string) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetMappedStringValue adds the mappedStringValue to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetMappedStringValue(mappedStringValue *string) {
	_ = "STUB: not implemented"
	return
}

// WithNestedAnnotationAmount adds the nestedAnnotationAmount to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithNestedAnnotationAmount(nestedAnnotationAmount *int64) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetNestedAnnotationAmount adds the nestedAnnotationAmount to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetNestedAnnotationAmount(nestedAnnotationAmount *int64) {
	_ = "STUB: not implemented"
	return
}

// WithNestedAnnotationOk adds the nestedAnnotationOk to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithNestedAnnotationOk(nestedAnnotationOk *string) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetNestedAnnotationOk adds the nestedAnnotationOk to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetNestedAnnotationOk(nestedAnnotationOk *string) {
	_ = "STUB: not implemented"
	return
}

// WithNestedPathEnumValue adds the nestedPathEnumValue to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithNestedPathEnumValue(nestedPathEnumValue *string) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetNestedPathEnumValue adds the nestedPathEnumValue to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetNestedPathEnumValue(nestedPathEnumValue *string) {
	_ = "STUB: not implemented"
	return
}

// WithNonConventionalNameValue adds the nonConventionalNameValue to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithNonConventionalNameValue(nonConventionalNameValue *string) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetNonConventionalNameValue adds the nonConventionalNameValue to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetNonConventionalNameValue(nonConventionalNameValue *string) {
	_ = "STUB: not implemented"
	return
}

// WithOneofEmpty adds the oneofEmpty to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithOneofEmpty(oneofEmpty *string) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetOneofEmpty adds the oneofEmpty to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetOneofEmpty(oneofEmpty *string) {
	_ = "STUB: not implemented"
	return
}

// WithOneofString adds the oneofString to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithOneofString(oneofString *string) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetOneofString adds the oneofString to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetOneofString(oneofString *string) {
	_ = "STUB: not implemented"
	return
}

// WithOptionalStringField adds the optionalStringField to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithOptionalStringField(optionalStringField *string) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetOptionalStringField adds the optionalStringField to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetOptionalStringField(optionalStringField *string) {
	_ = "STUB: not implemented"
	return
}

// WithOptionalStringValue adds the optionalStringValue to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithOptionalStringValue(optionalStringValue *string) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetOptionalStringValue adds the optionalStringValue to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetOptionalStringValue(optionalStringValue *string) {
	_ = "STUB: not implemented"
	return
}

// WithOutputOnlyStringViaFieldBehaviorAnnotation adds the outputOnlyStringViaFieldBehaviorAnnotation to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithOutputOnlyStringViaFieldBehaviorAnnotation(outputOnlyStringViaFieldBehaviorAnnotation *string) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetOutputOnlyStringViaFieldBehaviorAnnotation adds the outputOnlyStringViaFieldBehaviorAnnotation to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetOutputOnlyStringViaFieldBehaviorAnnotation(outputOnlyStringViaFieldBehaviorAnnotation *string) {
	_ = "STUB: not implemented"
	return
}

// WithPathEnumValue adds the pathEnumValue to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithPathEnumValue(pathEnumValue *string) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetPathEnumValue adds the pathEnumValue to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetPathEnumValue(pathEnumValue *string) {
	_ = "STUB: not implemented"
	return
}

// WithProductID adds the productID to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithProductID(productID []string) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetProductID adds the productId to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetProductID(productID []string) {
	_ = "STUB: not implemented"
	return

	// WithRepeatedEnumAnnotation adds the repeatedEnumAnnotation to the a bit of everything service check get query params params
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithRepeatedEnumAnnotation(repeatedEnumAnnotation []string) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetRepeatedEnumAnnotation adds the repeatedEnumAnnotation to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetRepeatedEnumAnnotation(repeatedEnumAnnotation []string) {
	_ = "STUB: not implemented"
	return
}

// WithRepeatedEnumValue adds the repeatedEnumValue to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithRepeatedEnumValue(repeatedEnumValue []string) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetRepeatedEnumValue adds the repeatedEnumValue to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetRepeatedEnumValue(repeatedEnumValue []string) {
	_ = "STUB: not implemented"
	return
}

// WithRepeatedStringAnnotation adds the repeatedStringAnnotation to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithRepeatedStringAnnotation(repeatedStringAnnotation []string) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetRepeatedStringAnnotation adds the repeatedStringAnnotation to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetRepeatedStringAnnotation(repeatedStringAnnotation []string) {
	_ = "STUB: not implemented"
	return
}

// WithRepeatedStringValue adds the repeatedStringValue to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithRepeatedStringValue(repeatedStringValue []string) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetRepeatedStringValue adds the repeatedStringValue to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetRepeatedStringValue(repeatedStringValue []string) {
	_ = "STUB: not implemented"
	return
}

// WithRequiredStringField1 adds the requiredStringField1 to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithRequiredStringField1(requiredStringField1 string) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetRequiredStringField1 adds the requiredStringField1 to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetRequiredStringField1(requiredStringField1 string) {
	_ = "STUB: not implemented"
	return
}

// WithRequiredStringField2 adds the requiredStringField2 to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithRequiredStringField2(requiredStringField2 string) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetRequiredStringField2 adds the requiredStringField2 to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetRequiredStringField2(requiredStringField2 string) {
	_ = "STUB: not implemented"
	return
}

// WithRequiredStringViaFieldBehaviorAnnotation adds the requiredStringViaFieldBehaviorAnnotation to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithRequiredStringViaFieldBehaviorAnnotation(requiredStringViaFieldBehaviorAnnotation string) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetRequiredStringViaFieldBehaviorAnnotation adds the requiredStringViaFieldBehaviorAnnotation to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetRequiredStringViaFieldBehaviorAnnotation(requiredStringViaFieldBehaviorAnnotation string) {
	_ = "STUB: not implemented"
	return
}

// WithRequiredFieldBehaviorJSONNameCustom adds the requiredFieldBehaviorJSONNameCustom to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithRequiredFieldBehaviorJSONNameCustom(requiredFieldBehaviorJSONNameCustom string) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetRequiredFieldBehaviorJSONNameCustom adds the requiredFieldBehaviorJsonNameCustom to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetRequiredFieldBehaviorJSONNameCustom(requiredFieldBehaviorJSONNameCustom string) {
	_ = "STUB: not implemented"
	return
}

// WithRequiredFieldSchemaJSONNameCustom adds the requiredFieldSchemaJSONNameCustom to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithRequiredFieldSchemaJSONNameCustom(requiredFieldSchemaJSONNameCustom string) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetRequiredFieldSchemaJSONNameCustom adds the requiredFieldSchemaJsonNameCustom to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetRequiredFieldSchemaJSONNameCustom(requiredFieldSchemaJSONNameCustom string) {
	_ = "STUB: not implemented"
	return
}

// WithSfixed32Value adds the sfixed32Value to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithSfixed32Value(sfixed32Value *int32) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetSfixed32Value adds the sfixed32Value to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetSfixed32Value(sfixed32Value *int32) {
	_ = "STUB: not implemented"
	return
}

// WithSfixed64Value adds the sfixed64Value to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithSfixed64Value(sfixed64Value *string) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetSfixed64Value adds the sfixed64Value to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetSfixed64Value(sfixed64Value *string) {
	_ = "STUB: not implemented"
	return
}

// WithSingleNestedAmount adds the singleNestedAmount to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithSingleNestedAmount(singleNestedAmount *int64) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetSingleNestedAmount adds the singleNestedAmount to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetSingleNestedAmount(singleNestedAmount *int64) {
	_ = "STUB: not implemented"
	return
}

// WithSingleNestedName adds the singleNestedName to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithSingleNestedName(singleNestedName string) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetSingleNestedName adds the singleNestedName to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetSingleNestedName(singleNestedName string) {
	_ = "STUB: not implemented"
	return
}

// WithSingleNestedOk adds the singleNestedOk to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithSingleNestedOk(singleNestedOk *string) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetSingleNestedOk adds the singleNestedOk to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetSingleNestedOk(singleNestedOk *string) {
	_ = "STUB: not implemented"
	return
}

// WithSint32Value adds the sint32Value to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithSint32Value(sint32Value *int32) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetSint32Value adds the sint32Value to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetSint32Value(sint32Value *int32) {
	_ = "STUB: not implemented"
	return
}

// WithSint64Value adds the sint64Value to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithSint64Value(sint64Value *string) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetSint64Value adds the sint64Value to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetSint64Value(sint64Value *string) {
	_ = "STUB: not implemented"
	return
}

// WithStringValue adds the stringValue to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithStringValue(stringValue *string) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetStringValue adds the stringValue to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetStringValue(stringValue *string) {
	_ = "STUB: not implemented"
	return
}

// WithTimestampValue adds the timestampValue to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithTimestampValue(timestampValue *strfmt.DateTime) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetTimestampValue adds the timestampValue to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetTimestampValue(timestampValue *strfmt.DateTime) {
	_ = "STUB: not implemented"
	return
}

// WithTrailingBoth adds the trailingBoth to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithTrailingBoth(trailingBoth *string) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetTrailingBoth adds the trailingBoth to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetTrailingBoth(trailingBoth *string) {
	_ = "STUB: not implemented"
	return
}

// WithTrailingMultiline adds the trailingMultiline to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithTrailingMultiline(trailingMultiline *string) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetTrailingMultiline adds the trailingMultiline to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetTrailingMultiline(trailingMultiline *string) {
	_ = "STUB: not implemented"
	return
}

// WithTrailingOnly adds the trailingOnly to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithTrailingOnly(trailingOnly *string) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetTrailingOnly adds the trailingOnly to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetTrailingOnly(trailingOnly *string) {
	_ = "STUB: not implemented"
	return
}

// WithTrailingOnlyDot adds the trailingOnlyDot to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithTrailingOnlyDot(trailingOnlyDot *string) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetTrailingOnlyDot adds the trailingOnlyDot to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetTrailingOnlyDot(trailingOnlyDot *string) {
	_ = "STUB: not implemented"
	return
}

// WithUint32Value adds the uint32Value to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithUint32Value(uint32Value *int64) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetUint32Value adds the uint32Value to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetUint32Value(uint32Value *int64) {
	_ = "STUB: not implemented"
	return
}

// WithUint64Value adds the uint64Value to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithUint64Value(uint64Value *string) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetUint64Value adds the uint64Value to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetUint64Value(uint64Value *string) {
	_ = "STUB: not implemented"
	return
}

// WithUUID adds the uuid to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithUUID(uuid strfmt.UUID) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil

	// SetUUID adds the uuid to the a bit of everything service check get query params params
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetUUID(uuid strfmt.UUID) {
	_ = "STUB: not implemented"

	// WithUuids adds the uuids to the a bit of everything service check get query params params
	return
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WithUuids(uuids []strfmt.UUID) *ABitOfEverythingServiceCheckGetQueryParamsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetUuids adds the uuids to the a bit of everything service check get query params params
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) SetUuids(uuids []strfmt.UUID) {
	_ = "STUB: not implemented"

	// WriteToRequest writes these params to a swagger request
	return
}

func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// query param boolValue

// query param bytesValue

// query param doubleValue

// query param enumValue

// query param enumValueAnnotation

// query param fixed32Value

// query param fixed64Value

// query param floatValue

// query param int32Value

// query param int64OverrideType

// query param int64Value

// query param mapValue

// query param mappedNestedValue

// query param mappedStringValue

// query param nestedAnnotation.amount

// query param nestedAnnotation.ok

// query param nestedPathEnumValue

// query param nonConventionalNameValue

// query param oneofEmpty

// query param oneofString

// query param optionalStringField

// query param optionalStringValue

// query param outputOnlyStringViaFieldBehaviorAnnotation

// query param pathEnumValue

// binding items for productId

// query array param productId

// binding items for repeatedEnumAnnotation

// query array param repeatedEnumAnnotation

// binding items for repeatedEnumValue

// query array param repeatedEnumValue

// binding items for repeatedStringAnnotation

// query array param repeatedStringAnnotation

// binding items for repeatedStringValue

// query array param repeatedStringValue

// query param requiredStringField1

// query param requiredStringField2

// query param requiredStringViaFieldBehaviorAnnotation

// query param required_field_behavior_json_name_custom

// query param required_field_schema_json_name_custom

// query param sfixed32Value

// query param sfixed64Value

// query param singleNested.amount

// path param singleNested.name

// query param singleNested.ok

// query param sint32Value

// query param sint64Value

// query param stringValue

// query param timestampValue

// query param trailingBoth

// query param trailingMultiline

// query param trailingOnly

// query param trailingOnlyDot

// query param uint32Value

// query param uint64Value

// query param uuid

// binding items for uuids

// query array param uuids

// bindParamABitOfEverythingServiceCheckGetQueryParams binds the parameter productId
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) bindParamProductID(formats strfmt.Registry) []string {
	_ = "STUB: not implemented"
	return nil
}

// explode []string

// string as string

// items.CollectionFormat: "multi"

// bindParamABitOfEverythingServiceCheckGetQueryParams binds the parameter repeatedEnumAnnotation
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) bindParamRepeatedEnumAnnotation(formats strfmt.Registry) []string {
	_ = "STUB: not implemented"
	return nil
}

// explode []string

// string as string

// items.CollectionFormat: "multi"

// bindParamABitOfEverythingServiceCheckGetQueryParams binds the parameter repeatedEnumValue
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) bindParamRepeatedEnumValue(formats strfmt.Registry) []string {
	_ = "STUB: not implemented"
	return nil
}

// explode []string

// string as string

// items.CollectionFormat: "multi"

// bindParamABitOfEverythingServiceCheckGetQueryParams binds the parameter repeatedStringAnnotation
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) bindParamRepeatedStringAnnotation(formats strfmt.Registry) []string {
	_ = "STUB: not implemented"
	return nil
}

// explode []string

// string as string

// items.CollectionFormat: "multi"

// bindParamABitOfEverythingServiceCheckGetQueryParams binds the parameter repeatedStringValue
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) bindParamRepeatedStringValue(formats strfmt.Registry) []string {
	_ = "STUB: not implemented"
	return nil
}

// explode []string

// string as string

// items.CollectionFormat: "multi"

// bindParamABitOfEverythingServiceCheckGetQueryParams binds the parameter uuids
func (o *ABitOfEverythingServiceCheckGetQueryParamsParams) bindParamUuids(formats strfmt.Registry) []string {
	_ = "STUB: not implemented"
	return nil
}

// explode []strfmt.UUID

// strfmt.UUID as string

// items.CollectionFormat: "multi"
