// Code generated by go-swagger; DO NOT EDIT.

package a_bit_of_everything

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/grpc-ecosystem/grpc-gateway/v2/examples/internal/clients/abe/models"
)

// ABitOfEverythingServiceCustomReader is a Reader for the ABitOfEverythingServiceCustom structure.
type ABitOfEverythingServiceCustomReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ABitOfEverythingServiceCustomReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

// NewABitOfEverythingServiceCustomOK creates a ABitOfEverythingServiceCustomOK with default headers values
func NewABitOfEverythingServiceCustomOK() *ABitOfEverythingServiceCustomOK {
	_ = "STUB: not implemented"
	return nil
}

/*
ABitOfEverythingServiceCustomOK describes a response with status code 200, with default header values.

A successful response.
*/
type ABitOfEverythingServiceCustomOK struct {
	Payload *models.ExamplepbABitOfEverything
}

// IsSuccess returns true when this a bit of everything service custom o k response has a 2xx status code
func (o *ABitOfEverythingServiceCustomOK) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this a bit of everything service custom o k response has a 3xx status code
	return false
}

func (o *ABitOfEverythingServiceCustomOK) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this a bit of everything service custom o k response has a 4xx status code
	return false
}

func (o *ABitOfEverythingServiceCustomOK) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this a bit of everything service custom o k response has a 5xx status code
	return false
}

func (o *ABitOfEverythingServiceCustomOK) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this a bit of everything service custom o k response a status code equal to that given
	return false
}

func (o *ABitOfEverythingServiceCustomOK) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the a bit of everything service custom o k response
}

func (o *ABitOfEverythingServiceCustomOK) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *ABitOfEverythingServiceCustomOK) Error() string { _ = "STUB: not implemented"; return "" }

func (o *ABitOfEverythingServiceCustomOK) String() string { _ = "STUB: not implemented"; return "" }

func (o *ABitOfEverythingServiceCustomOK) GetPayload() *models.ExamplepbABitOfEverything {
	_ = "STUB: not implemented"
	return nil
}

func (o *ABitOfEverythingServiceCustomOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// response payload

// NewABitOfEverythingServiceCustomForbidden creates a ABitOfEverythingServiceCustomForbidden with default headers values
func NewABitOfEverythingServiceCustomForbidden() *ABitOfEverythingServiceCustomForbidden {
	_ = "STUB: not implemented"
	return nil
}

/*
ABitOfEverythingServiceCustomForbidden describes a response with status code 403, with default header values.

Returned when the user does not have permission to access the resource.
*/
type ABitOfEverythingServiceCustomForbidden struct {
	Payload any
}

// IsSuccess returns true when this a bit of everything service custom forbidden response has a 2xx status code
func (o *ABitOfEverythingServiceCustomForbidden) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this a bit of everything service custom forbidden response has a 3xx status code
	return false
}

func (o *ABitOfEverythingServiceCustomForbidden) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this a bit of everything service custom forbidden response has a 4xx status code
	return false
}

func (o *ABitOfEverythingServiceCustomForbidden) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this a bit of everything service custom forbidden response has a 5xx status code
	return false
}

func (o *ABitOfEverythingServiceCustomForbidden) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this a bit of everything service custom forbidden response a status code equal to that given
	return false
}

func (o *ABitOfEverythingServiceCustomForbidden) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the a bit of everything service custom forbidden response
}

func (o *ABitOfEverythingServiceCustomForbidden) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *ABitOfEverythingServiceCustomForbidden) Error() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceCustomForbidden) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceCustomForbidden) GetPayload() any {
	_ = "STUB: not implemented"
	return *new(any)
}

func (o *ABitOfEverythingServiceCustomForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// response payload
	return nil
}

// NewABitOfEverythingServiceCustomNotFound creates a ABitOfEverythingServiceCustomNotFound with default headers values
func NewABitOfEverythingServiceCustomNotFound() *ABitOfEverythingServiceCustomNotFound {
	_ = "STUB: not implemented"
	return nil
}

/*
ABitOfEverythingServiceCustomNotFound describes a response with status code 404, with default header values.

Returned when the resource does not exist.
*/
type ABitOfEverythingServiceCustomNotFound struct {
	Payload string
}

// IsSuccess returns true when this a bit of everything service custom not found response has a 2xx status code
func (o *ABitOfEverythingServiceCustomNotFound) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this a bit of everything service custom not found response has a 3xx status code
	return false
}

func (o *ABitOfEverythingServiceCustomNotFound) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this a bit of everything service custom not found response has a 4xx status code
	return false
}

func (o *ABitOfEverythingServiceCustomNotFound) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this a bit of everything service custom not found response has a 5xx status code
	return false
}

func (o *ABitOfEverythingServiceCustomNotFound) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this a bit of everything service custom not found response a status code equal to that given
	return false
}

func (o *ABitOfEverythingServiceCustomNotFound) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the a bit of everything service custom not found response
}

func (o *ABitOfEverythingServiceCustomNotFound) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *ABitOfEverythingServiceCustomNotFound) Error() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceCustomNotFound) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceCustomNotFound) GetPayload() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceCustomNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// response payload
	return nil
}

// NewABitOfEverythingServiceCustomIMATeapot creates a ABitOfEverythingServiceCustomIMATeapot with default headers values
func NewABitOfEverythingServiceCustomIMATeapot() *ABitOfEverythingServiceCustomIMATeapot {
	_ = "STUB: not implemented"
	return nil
}

/*
ABitOfEverythingServiceCustomIMATeapot describes a response with status code 418, with default header values.

I'm a teapot.
*/
type ABitOfEverythingServiceCustomIMATeapot struct {
	Payload models.ExamplepbNumericEnum
}

// IsSuccess returns true when this a bit of everything service custom i m a teapot response has a 2xx status code
func (o *ABitOfEverythingServiceCustomIMATeapot) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this a bit of everything service custom i m a teapot response has a 3xx status code
	return false
}

func (o *ABitOfEverythingServiceCustomIMATeapot) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this a bit of everything service custom i m a teapot response has a 4xx status code
	return false
}

func (o *ABitOfEverythingServiceCustomIMATeapot) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this a bit of everything service custom i m a teapot response has a 5xx status code
	return false
}

func (o *ABitOfEverythingServiceCustomIMATeapot) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this a bit of everything service custom i m a teapot response a status code equal to that given
	return false
}

func (o *ABitOfEverythingServiceCustomIMATeapot) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the a bit of everything service custom i m a teapot response
}

func (o *ABitOfEverythingServiceCustomIMATeapot) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *ABitOfEverythingServiceCustomIMATeapot) Error() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceCustomIMATeapot) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceCustomIMATeapot) GetPayload() models.ExamplepbNumericEnum {
	_ = "STUB: not implemented"
	return *new(models.ExamplepbNumericEnum)
}

func (o *ABitOfEverythingServiceCustomIMATeapot) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// response payload
	return nil
}

// NewABitOfEverythingServiceCustomInternalServerError creates a ABitOfEverythingServiceCustomInternalServerError with default headers values
func NewABitOfEverythingServiceCustomInternalServerError() *ABitOfEverythingServiceCustomInternalServerError {
	_ = "STUB: not implemented"
	return nil
}

/*
ABitOfEverythingServiceCustomInternalServerError describes a response with status code 500, with default header values.

Server error
*/
type ABitOfEverythingServiceCustomInternalServerError struct {
	Payload *models.ExamplepbErrorResponse
}

// IsSuccess returns true when this a bit of everything service custom internal server error response has a 2xx status code
func (o *ABitOfEverythingServiceCustomInternalServerError) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this a bit of everything service custom internal server error response has a 3xx status code
	return false
}

func (o *ABitOfEverythingServiceCustomInternalServerError) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this a bit of everything service custom internal server error response has a 4xx status code
	return false
}

func (o *ABitOfEverythingServiceCustomInternalServerError) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this a bit of everything service custom internal server error response has a 5xx status code
	return false
}

func (o *ABitOfEverythingServiceCustomInternalServerError) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this a bit of everything service custom internal server error response a status code equal to that given
	return false
}

func (o *ABitOfEverythingServiceCustomInternalServerError) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the a bit of everything service custom internal server error response
}

func (o *ABitOfEverythingServiceCustomInternalServerError) Code() int {
	_ = "STUB: not implemented"
	return 0
}

func (o *ABitOfEverythingServiceCustomInternalServerError) Error() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceCustomInternalServerError) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceCustomInternalServerError) GetPayload() *models.ExamplepbErrorResponse {
	_ = "STUB: not implemented"
	return nil
}

func (o *ABitOfEverythingServiceCustomInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// response payload

// NewABitOfEverythingServiceCustomDefault creates a ABitOfEverythingServiceCustomDefault with default headers values
func NewABitOfEverythingServiceCustomDefault(code int) *ABitOfEverythingServiceCustomDefault {
	_ = "STUB: not implemented"
	return nil
}

/*
ABitOfEverythingServiceCustomDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ABitOfEverythingServiceCustomDefault struct {
	_statusCode int

	Payload *models.GoogleRPCStatus
}

// IsSuccess returns true when this a bit of everything service custom default response has a 2xx status code
func (o *ABitOfEverythingServiceCustomDefault) IsSuccess() bool {
	_ = "STUB: not implemented"
	return false
}

// IsRedirect returns true when this a bit of everything service custom default response has a 3xx status code
func (o *ABitOfEverythingServiceCustomDefault) IsRedirect() bool {
	_ = "STUB: not implemented"
	return false
}

// IsClientError returns true when this a bit of everything service custom default response has a 4xx status code
func (o *ABitOfEverythingServiceCustomDefault) IsClientError() bool {
	_ = "STUB: not implemented"
	return false
}

// IsServerError returns true when this a bit of everything service custom default response has a 5xx status code
func (o *ABitOfEverythingServiceCustomDefault) IsServerError() bool {
	_ = "STUB: not implemented"
	return false
}

// IsCode returns true when this a bit of everything service custom default response a status code equal to that given
func (o *ABitOfEverythingServiceCustomDefault) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the a bit of everything service custom default response
}

func (o *ABitOfEverythingServiceCustomDefault) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *ABitOfEverythingServiceCustomDefault) Error() string { _ = "STUB: not implemented"; return "" }

func (o *ABitOfEverythingServiceCustomDefault) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceCustomDefault) GetPayload() *models.GoogleRPCStatus {
	_ = "STUB: not implemented"
	return nil
}

func (o *ABitOfEverythingServiceCustomDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// response payload
