// Code generated by go-swagger; DO NOT EDIT.

package a_bit_of_everything

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/grpc-ecosystem/grpc-gateway/v2/examples/internal/clients/abe/models"
)

// ABitOfEverythingServiceDoubleColonReader is a Reader for the ABitOfEverythingServiceDoubleColon structure.
type ABitOfEverythingServiceDoubleColonReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ABitOfEverythingServiceDoubleColonReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

// NewABitOfEverythingServiceDoubleColonOK creates a ABitOfEverythingServiceDoubleColonOK with default headers values
func NewABitOfEverythingServiceDoubleColonOK() *ABitOfEverythingServiceDoubleColonOK {
	_ = "STUB: not implemented"
	return nil
}

/*
ABitOfEverythingServiceDoubleColonOK describes a response with status code 200, with default header values.

A successful response.
*/
type ABitOfEverythingServiceDoubleColonOK struct {
	Payload *models.ExamplepbABitOfEverything
}

// IsSuccess returns true when this a bit of everything service double colon o k response has a 2xx status code
func (o *ABitOfEverythingServiceDoubleColonOK) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this a bit of everything service double colon o k response has a 3xx status code
	return false
}

func (o *ABitOfEverythingServiceDoubleColonOK) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this a bit of everything service double colon o k response has a 4xx status code
	return false
}

func (o *ABitOfEverythingServiceDoubleColonOK) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this a bit of everything service double colon o k response has a 5xx status code
	return false
}

func (o *ABitOfEverythingServiceDoubleColonOK) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this a bit of everything service double colon o k response a status code equal to that given
	return false
}

func (o *ABitOfEverythingServiceDoubleColonOK) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the a bit of everything service double colon o k response
}

func (o *ABitOfEverythingServiceDoubleColonOK) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *ABitOfEverythingServiceDoubleColonOK) Error() string { _ = "STUB: not implemented"; return "" }

func (o *ABitOfEverythingServiceDoubleColonOK) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceDoubleColonOK) GetPayload() *models.ExamplepbABitOfEverything {
	_ = "STUB: not implemented"
	return nil
}

func (o *ABitOfEverythingServiceDoubleColonOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// response payload

// NewABitOfEverythingServiceDoubleColonForbidden creates a ABitOfEverythingServiceDoubleColonForbidden with default headers values
func NewABitOfEverythingServiceDoubleColonForbidden() *ABitOfEverythingServiceDoubleColonForbidden {
	_ = "STUB: not implemented"
	return nil
}

/*
ABitOfEverythingServiceDoubleColonForbidden describes a response with status code 403, with default header values.

Returned when the user does not have permission to access the resource.
*/
type ABitOfEverythingServiceDoubleColonForbidden struct {
	Payload any
}

// IsSuccess returns true when this a bit of everything service double colon forbidden response has a 2xx status code
func (o *ABitOfEverythingServiceDoubleColonForbidden) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this a bit of everything service double colon forbidden response has a 3xx status code
	return false
}

func (o *ABitOfEverythingServiceDoubleColonForbidden) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this a bit of everything service double colon forbidden response has a 4xx status code
	return false
}

func (o *ABitOfEverythingServiceDoubleColonForbidden) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this a bit of everything service double colon forbidden response has a 5xx status code
	return false
}

func (o *ABitOfEverythingServiceDoubleColonForbidden) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this a bit of everything service double colon forbidden response a status code equal to that given
	return false
}

func (o *ABitOfEverythingServiceDoubleColonForbidden) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the a bit of everything service double colon forbidden response
}

func (o *ABitOfEverythingServiceDoubleColonForbidden) Code() int {
	_ = "STUB: not implemented"
	return 0
}

func (o *ABitOfEverythingServiceDoubleColonForbidden) Error() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceDoubleColonForbidden) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceDoubleColonForbidden) GetPayload() any {
	_ = "STUB: not implemented"
	return *new(any)
}

func (o *ABitOfEverythingServiceDoubleColonForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// response payload
	return nil
}

// NewABitOfEverythingServiceDoubleColonNotFound creates a ABitOfEverythingServiceDoubleColonNotFound with default headers values
func NewABitOfEverythingServiceDoubleColonNotFound() *ABitOfEverythingServiceDoubleColonNotFound {
	_ = "STUB: not implemented"
	return nil
}

/*
ABitOfEverythingServiceDoubleColonNotFound describes a response with status code 404, with default header values.

Returned when the resource does not exist.
*/
type ABitOfEverythingServiceDoubleColonNotFound struct {
	Payload string
}

// IsSuccess returns true when this a bit of everything service double colon not found response has a 2xx status code
func (o *ABitOfEverythingServiceDoubleColonNotFound) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this a bit of everything service double colon not found response has a 3xx status code
	return false
}

func (o *ABitOfEverythingServiceDoubleColonNotFound) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this a bit of everything service double colon not found response has a 4xx status code
	return false
}

func (o *ABitOfEverythingServiceDoubleColonNotFound) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this a bit of everything service double colon not found response has a 5xx status code
	return false
}

func (o *ABitOfEverythingServiceDoubleColonNotFound) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this a bit of everything service double colon not found response a status code equal to that given
	return false
}

func (o *ABitOfEverythingServiceDoubleColonNotFound) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the a bit of everything service double colon not found response
}

func (o *ABitOfEverythingServiceDoubleColonNotFound) Code() int {
	_ = "STUB: not implemented"
	return 0
}

func (o *ABitOfEverythingServiceDoubleColonNotFound) Error() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceDoubleColonNotFound) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceDoubleColonNotFound) GetPayload() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceDoubleColonNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// response payload
	return nil
}

// NewABitOfEverythingServiceDoubleColonIMATeapot creates a ABitOfEverythingServiceDoubleColonIMATeapot with default headers values
func NewABitOfEverythingServiceDoubleColonIMATeapot() *ABitOfEverythingServiceDoubleColonIMATeapot {
	_ = "STUB: not implemented"
	return nil
}

/*
ABitOfEverythingServiceDoubleColonIMATeapot describes a response with status code 418, with default header values.

I'm a teapot.
*/
type ABitOfEverythingServiceDoubleColonIMATeapot struct {
	Payload models.ExamplepbNumericEnum
}

// IsSuccess returns true when this a bit of everything service double colon i m a teapot response has a 2xx status code
func (o *ABitOfEverythingServiceDoubleColonIMATeapot) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this a bit of everything service double colon i m a teapot response has a 3xx status code
	return false
}

func (o *ABitOfEverythingServiceDoubleColonIMATeapot) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this a bit of everything service double colon i m a teapot response has a 4xx status code
	return false
}

func (o *ABitOfEverythingServiceDoubleColonIMATeapot) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this a bit of everything service double colon i m a teapot response has a 5xx status code
	return false
}

func (o *ABitOfEverythingServiceDoubleColonIMATeapot) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this a bit of everything service double colon i m a teapot response a status code equal to that given
	return false
}

func (o *ABitOfEverythingServiceDoubleColonIMATeapot) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the a bit of everything service double colon i m a teapot response
}

func (o *ABitOfEverythingServiceDoubleColonIMATeapot) Code() int {
	_ = "STUB: not implemented"
	return 0
}

func (o *ABitOfEverythingServiceDoubleColonIMATeapot) Error() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceDoubleColonIMATeapot) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceDoubleColonIMATeapot) GetPayload() models.ExamplepbNumericEnum {
	_ = "STUB: not implemented"
	return *new(models.ExamplepbNumericEnum)
}

func (o *ABitOfEverythingServiceDoubleColonIMATeapot) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// response payload
	return nil
}

// NewABitOfEverythingServiceDoubleColonInternalServerError creates a ABitOfEverythingServiceDoubleColonInternalServerError with default headers values
func NewABitOfEverythingServiceDoubleColonInternalServerError() *ABitOfEverythingServiceDoubleColonInternalServerError {
	_ = "STUB: not implemented"
	return nil
}

/*
ABitOfEverythingServiceDoubleColonInternalServerError describes a response with status code 500, with default header values.

Server error
*/
type ABitOfEverythingServiceDoubleColonInternalServerError struct {
	Payload *models.ExamplepbErrorResponse
}

// IsSuccess returns true when this a bit of everything service double colon internal server error response has a 2xx status code
func (o *ABitOfEverythingServiceDoubleColonInternalServerError) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this a bit of everything service double colon internal server error response has a 3xx status code
	return false
}

func (o *ABitOfEverythingServiceDoubleColonInternalServerError) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this a bit of everything service double colon internal server error response has a 4xx status code
	return false
}

func (o *ABitOfEverythingServiceDoubleColonInternalServerError) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this a bit of everything service double colon internal server error response has a 5xx status code
	return false
}

func (o *ABitOfEverythingServiceDoubleColonInternalServerError) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this a bit of everything service double colon internal server error response a status code equal to that given
	return false
}

func (o *ABitOfEverythingServiceDoubleColonInternalServerError) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the a bit of everything service double colon internal server error response
}

func (o *ABitOfEverythingServiceDoubleColonInternalServerError) Code() int {
	_ = "STUB: not implemented"
	return 0
}

func (o *ABitOfEverythingServiceDoubleColonInternalServerError) Error() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceDoubleColonInternalServerError) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceDoubleColonInternalServerError) GetPayload() *models.ExamplepbErrorResponse {
	_ = "STUB: not implemented"
	return nil
}

func (o *ABitOfEverythingServiceDoubleColonInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// response payload

// NewABitOfEverythingServiceDoubleColonDefault creates a ABitOfEverythingServiceDoubleColonDefault with default headers values
func NewABitOfEverythingServiceDoubleColonDefault(code int) *ABitOfEverythingServiceDoubleColonDefault {
	_ = "STUB: not implemented"
	return nil
}

/*
ABitOfEverythingServiceDoubleColonDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ABitOfEverythingServiceDoubleColonDefault struct {
	_statusCode int

	Payload *models.GoogleRPCStatus
}

// IsSuccess returns true when this a bit of everything service double colon default response has a 2xx status code
func (o *ABitOfEverythingServiceDoubleColonDefault) IsSuccess() bool {
	_ = "STUB: not implemented"
	return false
}

// IsRedirect returns true when this a bit of everything service double colon default response has a 3xx status code
func (o *ABitOfEverythingServiceDoubleColonDefault) IsRedirect() bool {
	_ = "STUB: not implemented"
	return false
}

// IsClientError returns true when this a bit of everything service double colon default response has a 4xx status code
func (o *ABitOfEverythingServiceDoubleColonDefault) IsClientError() bool {
	_ = "STUB: not implemented"
	return false
}

// IsServerError returns true when this a bit of everything service double colon default response has a 5xx status code
func (o *ABitOfEverythingServiceDoubleColonDefault) IsServerError() bool {
	_ = "STUB: not implemented"
	return false
}

// IsCode returns true when this a bit of everything service double colon default response a status code equal to that given
func (o *ABitOfEverythingServiceDoubleColonDefault) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the a bit of everything service double colon default response
}

func (o *ABitOfEverythingServiceDoubleColonDefault) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *ABitOfEverythingServiceDoubleColonDefault) Error() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceDoubleColonDefault) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *ABitOfEverythingServiceDoubleColonDefault) GetPayload() *models.GoogleRPCStatus {
	_ = "STUB: not implemented"
	return nil
}

func (o *ABitOfEverythingServiceDoubleColonDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// response payload
