// Code generated by go-swagger; DO NOT EDIT.

package a_bit_of_everything

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/grpc-ecosystem/grpc-gateway/v2/examples/internal/clients/abe/models"
)

// NewABitOfEverythingServicePostRequiredMessageTypeParams creates a new ABitOfEverythingServicePostRequiredMessageTypeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewABitOfEverythingServicePostRequiredMessageTypeParams() *ABitOfEverythingServicePostRequiredMessageTypeParams {
	_ = "STUB: not implemented"
	return nil
}

// NewABitOfEverythingServicePostRequiredMessageTypeParamsWithTimeout creates a new ABitOfEverythingServicePostRequiredMessageTypeParams object
// with the ability to set a timeout on a request.
func NewABitOfEverythingServicePostRequiredMessageTypeParamsWithTimeout(timeout time.Duration) *ABitOfEverythingServicePostRequiredMessageTypeParams {
	_ = "STUB: not implemented"
	return nil
}

// NewABitOfEverythingServicePostRequiredMessageTypeParamsWithContext creates a new ABitOfEverythingServicePostRequiredMessageTypeParams object
// with the ability to set a context for a request.
func NewABitOfEverythingServicePostRequiredMessageTypeParamsWithContext(ctx context.Context) *ABitOfEverythingServicePostRequiredMessageTypeParams {
	_ = "STUB: not implemented"
	return nil
}

// NewABitOfEverythingServicePostRequiredMessageTypeParamsWithHTTPClient creates a new ABitOfEverythingServicePostRequiredMessageTypeParams object
// with the ability to set a custom HTTPClient for a request.
func NewABitOfEverythingServicePostRequiredMessageTypeParamsWithHTTPClient(client *http.Client) *ABitOfEverythingServicePostRequiredMessageTypeParams {
	_ = "STUB: not implemented"
	return nil
}

/*
ABitOfEverythingServicePostRequiredMessageTypeParams contains all the parameters to send to the API endpoint

	for the a bit of everything service post required message type operation.

	Typically these are written to a http.Request.
*/
type ABitOfEverythingServicePostRequiredMessageTypeParams struct {

	// Body.
	Body *models.ExamplepbRequiredMessageTypeRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the a bit of everything service post required message type params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ABitOfEverythingServicePostRequiredMessageTypeParams) WithDefaults() *ABitOfEverythingServicePostRequiredMessageTypeParams {
	_ = "STUB: not implemented"
	return nil

	// SetDefaults hydrates default values in the a bit of everything service post required message type params (not the query body).
	//
	// All values with no default are reset to their zero value.
}

func (o *ABitOfEverythingServicePostRequiredMessageTypeParams) SetDefaults() {
	_ = "STUB: not implemented"
	// no default values defined for this parameter
	return
}

// WithTimeout adds the timeout to the a bit of everything service post required message type params
func (o *ABitOfEverythingServicePostRequiredMessageTypeParams) WithTimeout(timeout time.Duration) *ABitOfEverythingServicePostRequiredMessageTypeParams {
	_ = "STUB: not implemented"
	return nil
}

// SetTimeout adds the timeout to the a bit of everything service post required message type params
func (o *ABitOfEverythingServicePostRequiredMessageTypeParams) SetTimeout(timeout time.Duration) {
	_ = "STUB: not implemented"
	return

	// WithContext adds the context to the a bit of everything service post required message type params
}

func (o *ABitOfEverythingServicePostRequiredMessageTypeParams) WithContext(ctx context.Context) *ABitOfEverythingServicePostRequiredMessageTypeParams {
	_ = "STUB: not implemented"
	return nil
}

// SetContext adds the context to the a bit of everything service post required message type params
func (o *ABitOfEverythingServicePostRequiredMessageTypeParams) SetContext(ctx context.Context) {
	_ = "STUB: not implemented"

	// WithHTTPClient adds the HTTPClient to the a bit of everything service post required message type params
	return
}

func (o *ABitOfEverythingServicePostRequiredMessageTypeParams) WithHTTPClient(client *http.Client) *ABitOfEverythingServicePostRequiredMessageTypeParams {
	_ = "STUB: not implemented"
	return nil
}

// SetHTTPClient adds the HTTPClient to the a bit of everything service post required message type params
func (o *ABitOfEverythingServicePostRequiredMessageTypeParams) SetHTTPClient(client *http.Client) {
	_ = "STUB: not implemented"
	return

	// WithBody adds the body to the a bit of everything service post required message type params
}

func (o *ABitOfEverythingServicePostRequiredMessageTypeParams) WithBody(body *models.ExamplepbRequiredMessageTypeRequest) *ABitOfEverythingServicePostRequiredMessageTypeParams {
	_ = "STUB: not implemented"
	return nil

	// SetBody adds the body to the a bit of everything service post required message type params
}

func (o *ABitOfEverythingServicePostRequiredMessageTypeParams) SetBody(body *models.ExamplepbRequiredMessageTypeRequest) {
	_ = "STUB: not implemented"

	// WriteToRequest writes these params to a swagger request
	return
}

func (o *ABitOfEverythingServicePostRequiredMessageTypeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}
